### PR TITLE
Fix crash in NTP servers GUI dialog on late network configuration

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1938168

### CODE REVIEW

**Comment by rvykydal** [comment]
The crash happens when trying to update an iterator from the Gtk model for list of NTP servers after the iterator becomes invalid (by clearing the model):

- User enters DateTime Spoke -> on spoke refresh the model refresh (of ntp server state) is started: for iterator ITR_X from the model
- THREAD_Y starts to check server pointed by ITR_X with ntp_server_workig() method
- User enters NTP configuration dialog -> model is reinitalized / cleared (servers/items are added from scratch)
- THREAD1 finishes the ntp_server_working() check and tries to update the ITR which no longer exists => crash

The issue is hit when the ntp_server_working takes too long (5 secs), ie longer than the time between entering the spoke and opening the NTP configuration dialog. For example when networking is configured later in the installation (like just before NTP configuration).

The crash showed with this
https://github.com/rvykydal/anaconda/commit/212eb1cf0b293f54e350c4bb0d666a5152cc0265
RVDBG debug info added:

[anaconda.crash.log](https://github.com/rhinstaller/anaconda/files/6172501/anaconda.crash.log)

If the `ntp_server_working` function is fast, eg network is activated early the refresh on spoke entry is fast enough to prevent the crash:

[anaconda.ok.log](https://github.com/rhinstaller/anaconda/files/6172503/anaconda.ok.log)

Seems to be related also to this change https://github.com/rhinstaller/anaconda/pull/2468
In upstream the code was completely rewritten in commit 15d2b2fb568df2c1a77cfb2baa703ae9f3da0f30

I think the safe fix for rhel8-branch would be checking the validity of iterator before using it as in this PR. In case of invalid itr there is no action so I think even the result should be correct.

We could probably also remove the model refresh (https://github.com/rhinstaller/anaconda/blob/e8714d7763f462deff4fc3f47bfb9fc5786fcae3/pyanaconda/ui/gui/spokes/datetime_spoke.py#L651) from spoke refresh method because the refreshed values are used/available (I think) only when the dialog is entered, and entering the dialog does reinitialization of the model anyway. Perhaps the refresh became useless (malign) after the https://github.com/rhinstaller/anaconda/pull/2468. I haven't found any reason for its existence but we should think twice I think.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you! And sorry for breaking it.

I'm actually amazed that we keep an iterator in the asynchronous call instead of just the server hostname. But I guess it's understandable how this came to be.

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Review by jkonecny12 — APPROVED** [review]
LGTM! Great work!

**Comment by JeongHyeon-Kim** [comment]
Thank for solving issue and record

**Pull request merged**
