### PR TITLE
Install python-copr and RedHat CA into anaconda-ci container

### PR DESCRIPTION
**Pull request by martinpitt**
This is a dependency of https://github.com/vojtechtrefny/copr-builder

Related: rhbz#1885635

----

This is a prerequisite for replacing the anaconda_daily_rhel_copr Jenkins job.

### CODE REVIEW

**Comment by martinpitt** [comment]
I built and deployed that new container on our internal github-runner already. The above unit-tests already ran with this new container.

**Comment by martinpitt** [comment]
I did *not* currently do this for the master branch. IIRC @jkonecny12 wanted to do the daily copr for Fedora with packit. If you change your mind, I'm happy to create a github action for the daily copr (should be fairly simple, we just need this PR for master, create a new secret for the Fedora COPR token, and a workflow that invokes copr-builder).

**Comment by martinpitt** [comment]
Argh, missing `Related:`, added to commit message.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Pull request merged**
