### PR TITLE
Split the packages configuration data

### PR DESCRIPTION
**Pull request by poncovka**
Use the `PackagesSelectionData` structure for the software selection and
the `PackagesConfigurationData` structure for the DNF and RPM configuration.

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by poncovka** [comment]
The failed tests are disabled in the daily runs, so this PR doesn't cause any regressions.

```
TEST                                                    | RESULT
--------------------------------------------------------+------------+
harddrive-install-tree                                  | FAILED     |
container                                               | SUCCESS    | 
harddrive-install-tree-relative                         | FAILED     |
packages-instlangs-1                                    | SUCCESS    | 
packages-weakdeps                                       | SUCCESS    | 
packages-instlangs-2                                    | SUCCESS    | 
groups-ignoremissing                                    | SUCCESS    | 
packages-ignoremissing                                  | SUCCESS    | 
packages-default                                        | SUCCESS    | 
groups-and-envs-1                                       | SUCCESS    | 
groups-and-envs-3                                       | SUCCESS    | 
packages-and-groups-1                                   | SUCCESS    | 
packages-and-groups-ignoremissing                       | SUCCESS    | 
module-ignoremissing                                    | SUCCESS    | 
packages-excludedocs                                    | SUCCESS    | 
module-install-4                                        | SUCCESS    | 
fedora-live-image-build                                 | SUCCESS    | 
addrepo                                                 | SUCCESS    | 
packages-instlangs-3                                    | SUCCESS    | 
groups-and-envs-2                                       | SUCCESS    | 
module-install-2                                        | TIMED OUT  | 
module-install-1                                        | TIMED OUT  | 
module-enable-many                                      | TIMED OUT  | 
module-enable-one-module-multiple-times                 | TIMED OUT  | 
module-install-3                                        | TIMED OUT  | 
module-install-many                                     | TIMED OUT  | 
module-install-one-module-multiple-profiles             | TIMED OUT  | 
module-non-default-profiles                             | TIMED OUT  | 
```

**Pull request merged**
