### PR TITLE
workflow: for kstest on PR use the new more specific test plan

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Comment by rvykydal** [comment]
Depends on https://github.com/rhinstaller/kickstart-tests/pull/737

**Comment by rvykydal** [comment]
The patch needs to be updated.

**Review by VladimirSlavik — APPROVED** [review]
How do I even check what this does? Acking anyway to not block this...

**Comment by rvykydal** [comment]
> How do I even check what this does? Acking anyway to not block this...

Sorry for not giving the details. Anyway, this PR is obsoleted by https://github.com/rhinstaller/anaconda/commit/1d8b8e9ce0f815ea179053076e2bcc333d2ca00c since which we are not using the testplan file for the workflow anymore. I'll open another PR to remove it.

**Pull request closed without merging**
