### PR TITLE
Port resolv conf fixes from master

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Thanks! I'm not sure how to interpret the test failures on `master` due to merge conflicts... otherwise LGTM.

**Comment by poncovka** [comment]
I don't think this mergable with the master branch. Maybe it should go to f36-release?

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Comment by rvykydal** [comment]
> I don't think this mergable with the master branch. Maybe it should go to f36-release?

You are right, seems so, I think I need advice from @M4rtinK

**Review by poncovka — APPROVED** [review]
Thanks!

**Pull request merged**
