### PR TITLE
Get back requirement of 'inst.' prefix

### PR DESCRIPTION
**Pull request by jkonecny12**
Compose tooling should be ready now. Let's go and test that! :)

Revert of #3346 .

*Resolves: rhbz#1947376*

### CODE REVIEW

**Comment by jkonecny12** [comment]
Revert of https://github.com/rhinstaller/anaconda/pull/3346 .

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by jstodola — APPROVED** [review]
Revert "Revert "...""
I hope it is the last revert :-)

**Comment by jkonecny12** [comment]
KS tests failed on the LVM issue :(.

**Review by VladimirSlavik — APPROVED** [review]

**Comment by jkonecny12** [comment]
Tested and it seems to be working correctly.

**Review by poncovka — APPROVED** [review]

**Pull request merged**
