### PR TITLE
Don't enter spokes after we leave the Summary hub

### PR DESCRIPTION
**Pull request by poncovka**
If we decide to automatically leave the Summary hub and start the installation,
don't allow to enter spokes from the Summary hub anymore. There might be some
unprocessed callbacks in the even queue.

Resolved: rhzb#1866022

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by poncovka** [comment]
The commit message was updated.

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Pull request merged**
