### PR TITLE
Update misc npm packages

### PR DESCRIPTION
**Pull request by VladimirSlavik**
I'll try to update as much as I can, adding more commits while tests keep passing... in the ideal case.

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Thanks!

**Review by poncovka — APPROVED** [review]

**Comment by VladimirSlavik** [comment]
If tests pass after this push, I'll interactively rebase and push last time.

There's something wrong with react and eslint that makes it a non-straightforward change. I can't tell and don't remember well either, but it was along the lines of something needed updating and wasn't released on "their" side.

For the record, I determined the last versions by running `npx npm-check-updates` in the `ui/webui` dir, and tried to work backwards in case something wasn't simple bump to latest.

**Comment by VladimirSlavik** [comment]
To bump eslint too, these resources might be useful.

* https://github.com/cockpit-project/starter-kit/pull/554/commits/3d490c6114ca49d573f040830ff4e230a740a5f9
* https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0

That's for another PR, I think I don't want to complicate this too much.

**Review by poncovka — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
Thanks a lot for looking into this! :) Looks as good to me as a NPM package update can look good.

**Pull request merged**
