### PR TITLE
Do not check ssl certificate if --noverifyssl is in kickstart (#1745064)

### PR DESCRIPTION
**Pull request by jstodola**
This PR fixes two problems with checking of ssl certificates:
1. Downloading of metadata ignored --noverifyssl in the kickstart file.
2. Additional repositories loaded from treeinfo were always checking ssl certificate. This is a problem for RHEL-8 and unified DVD.

Resolves: rhbz#1745064

### CODE REVIEW

**Review by poncovka — COMMENTED** [review]
Thanks for the fix! It looks good to me, but @jkonecny12 should see it as well.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Review by jkonecny12 — COMMENTED** [review]
Looks great but it needs to be tested properly first.

**Review by jkonecny12 — APPROVED** [review]
This is really hell to test it on Rawhide but finally. I've manage to do that. Works as expected, without this change the Anaconda will use repository as installation root and ignore other ``.treeinfo`` repositories and with this change it will correctly load ``.treeinfo`` and all repositories in it.

Thanks for this fix @jstodola!

**Pull request merged**
