### PR TITLE
Add the po-empty make target from master

### PR DESCRIPTION
**Pull request by atodorov**
Hi,
I find this very useful for local development since I don't have an account with Transifex. Please merge it in RHEL7 branch as well.

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me. Unless somebody sees an issue in this change, I'm going to merge this by the end of this week.

**Comment by clumens** [comment]
I think we need to open a new 7.2 bug for all this testing backporting first, and then either make a new branch to merge these things into until such time as 7.2 is open for commits, or just sit on them until then.  Also, we need to talk about how this is going to fit in with bug 1196721.  Consider this comment as applying to all the other test backporting pull requests, too.

**Comment by atodorov** [comment]
@clumens, FYI rhbz #1196721

**Comment by clumens** [comment]
Pushed manually, thanks.

**Pull request closed without merging**
