### PR TITLE
network: fix inst.dhcpclass boot option

### PR DESCRIPTION
**Pull request by rvykydal**
Transform it to dracut configuration option for NM initramfs generator so that
internal NM dhcp client can be used.

Resolves: rhbz#1870692

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me, same as the original. Thank you!

**Review by poncovka — APPROVED** [review]
Looks good to me.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Comment by rvykydal** [comment]
I've added fixup from rhel-8 branch.

**Review by VladimirSlavik — APPROVED** [review]

**Review by poncovka — APPROVED** [review]

**Pull request merged**
