### PR TITLE
network: default to addr-gen-mode eui64

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1873021

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Not really sure what's happening there but looks good code wise. :)

**Review by jkonecny12 — APPROVED** [review]
Looks good to me from code perspective but please add commit message explaining why this change is needed. I know there is a bug number but there should be a brief description even in the commit message.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me and +1 to the above. Thank you!

**Review by poncovka — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]
Looks great now.
Just a note, there is a typo ``Anoconda`` in commit message.

**Comment by rvykydal** [comment]
Ported to Fedora in https://github.com/rhinstaller/anaconda/pull/2851

**Pull request closed without merging**
