### PR TITLE
network: don't activate bond/team devices regardless of --activate (#…

### PR DESCRIPTION
**Pull request by rvykydal**
…1358795)

Resolves: rhbz#1358795

### CODE REVIEW

**Comment by jkonecny12** [comment]
Looks good to me.

**Comment by jkonecny12** [comment]
Is this working on master branch, or you will cherry-pick this to master?

**Comment by rvykydal** [comment]
I need to check. If it is I'd push it, if not I'll probably make a special master PR.

**Comment by jkonecny12** [comment]
OK, thank you for answer.

**Comment by rvykydal** [comment]
Pushed.

**Pull request closed without merging**
