### PR TITLE
translations and unicode

### PR DESCRIPTION
**Pull request by dashea**
Fix live not being translated and also crashing when it is translated. Also needs https://github.com/rhinstaller/blivet/pull/73

I managed to get through a live install in Russian with this but I'm sure to have missed something.

### CODE REVIEW

**Comment by vpodzime** [comment]
I don't quite understand one thing -- why do we need the first commit (Revert...) if we remove the LC_ALL definition from the environment in the one that follows (Consolidate...)? By the revert we loose the default encoding setup on live so if it's possible to keep it, it would be great. If not, does that mean that whenever LC_ALL is set in the environment prior/when running anaconda, translations are doomed?

**Comment by dashea** [comment]
I removed the LC_ALL liveinst commit because I don't think it ever actually worked.

$ env - python -c 'import sys; print(sys.getdefaultencoding())'
ascii
$ LC_ALL='en_US.UTF-8' python -c 'import sys; print(sys.getdefaultencoding())'
ascii

If I am missing something I will be happy to put it back.

**Comment by vpodzime** [comment]
Ha, so it "fixed" the issue for F21 for a moment by breaking translations instead of by fixing the default encoding. :) Thanks for the further explanation!

**Comment by dashea** [comment]
Pushed to f22-branch

**Pull request closed without merging**
