### PR TITLE
Enable the zram-generator service again (#1975881)

### PR DESCRIPTION
**Pull request by poncovka**
Install the `rust-zram-generator` package on the boot.iso image
to install and enable the `zram-generator` service.

Resolves: rhbz#1975881

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by poncovka** [comment]
Ported in https://github.com/rhinstaller/anaconda/pull/3492.

**Comment by poncovka** [comment]
The build requires a coordination with `rust-zram-generator`.

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Pull request merged**
