### PR TITLE
Add a bunch of gi.require_version calls

### PR DESCRIPTION
**Pull request by dashea**
pygobject differentiates between different versions of introspectable
libraries in about the dumbest way possible, and now it complains if we
don't play along.

### CODE REVIEW

**Comment by vpodzime** [comment]
Wow, this is stupid. But I don't see any better way so ACK.

**Comment by dashea** [comment]
Pushed.

**Comment by bcl** [comment]
Is there any way we could pull a map of these values from constants? Updating them all is going to be a bunch of search and replace.

**Comment by dashea** [comment]
> Is there any way we could pull a map of these values from constants? Updating them all is going to be a bunch of search and replace.

I guess so, but to me it seems like adding the constants imports is going to crud up the import blocks yet more. The values only change for major versions, so a change would presumably an API change that we'd have to deal with too.

Maybe we could have a method to just do all the imports at once, so before the from gi.repository bits you'd just call iutil.gi_require or something like that?

**Pull request closed without merging**
