### PR TITLE
Remove on_proxy_ok_clicked from Source spoke

### PR DESCRIPTION
**Pull request by jkonecny12**
This method is not used anywhere in the code now.

### CODE REVIEW

**Comment by vpodzime** [comment]
Did you find the place where the things from this method happen? If there's no such place in the code, we should hook it back somewhere instead.

**Comment by jkonecny12** [comment]
I'll look on that. I really don't know I found this by accident.

**Comment by jkonecny12** [comment]
Results from my investigation:

*This method is a leftover from commit:*

*"Make dialogs behave better with timed input validation"*
*SHA bb1c211*

**Comment by vpodzime** [comment]
Yeah, it looks like it can go. Thanks for the investigation. ;)

**Comment by jkonecny12** [comment]
Pushed

**Pull request closed without merging**
