### PR TITLE
Add the "Encrypt my data" checkbox to the custom partitioning spoke

### PR DESCRIPTION
**Pull request by poncovka**
Allow users to generate encrypted default partitioning to have the same
experience as with the automatic partitioning in the storage spoke.

Related: rhbz#1903786

### CODE REVIEW

**Comment by poncovka** [comment]
encrypt_data

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by poncovka** [comment]
Rebased.

**Comment by jstodola** [comment]
Aaaand.... anabot issue created: https://pagure.io/anabot/issue/3

**Pull request merged**
