### PR TITLE
Use pykickstart 3

### PR DESCRIPTION
**Pull request by poncovka**
**DO NOT MERGE**
Adapt anaconda's commands to pykickstart 3.

We cannot do deepcopy of the method command since pykickstart 3,
because it tries to do deepcopy of patterns. However, we shouldn't
do it anyway and the code where we used it should be rewritten.

TODO: Run the kickstart tests.

NOTE: The kdump addon fails when it tries to parse its section in
a kickstart file. However, when it is not specified, the installer is fine.

**Requires: pykickstart-3**

### CODE REVIEW

**Comment by M4rtinK** [comment]
Kdump addon PR for compatibility with Pykickstart 3:
https://github.com/daveyoung/kdump-anaconda-addon/pull/16

**Comment by M4rtinK** [comment]
jenkins, test this please

**Comment by poncovka** [comment]
Rebased, but there is still the problem with deep copy of kickstart data.

**Comment by poncovka** [comment]
Added a fix for deepcopy of the kickstart data in the storage.

**Comment by poncovka** [comment]
jenkins, test this please

**Comment by M4rtinK** [comment]
BTW, this is the deepcopy upstream Python issue: https://bugs.python.org/issue32668

Looks like we might be lucky and it is already fixed in latest Python versions.

**Comment by poncovka** [comment]
Jenkins, test this please.

**Pull request merged**
