### PR TITLE
network: use introspection data from libnm instead of libnm-glib

### PR DESCRIPTION
**Pull request by lkundrak**
The installer seems to be one of the few packages that drag in the old
library. Address that.

### CODE REVIEW

**Comment by lkundrak** [comment]
Ping?

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
Please ignore test result, we have some issues with repositories.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
Thank for this patch!

**Pull request merged**
