### PR TITLE
Apply onboot policy even when network was configured in UI.

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1856632

Brings back behaviour from RHEL 7 and RHEL 8.2

### CODE REVIEW

**Comment by rvykydal** [comment]
> LGTM
> If this behavior is also in Fedora than maybe we should use configuration files to solve this in future.

Yes, I was thinking about it but it would require reworking of policy setting we already have in configuration files, and here the situation is still quite unclean. I'll think about it more when porting the patch to Fedora.

**Comment by jkonecny12** [comment]
> > LGTM
> > If this behavior is also in Fedora than maybe we should use configuration files to solve this in future.
> 
> Yes, I was thinking about it but it would require reworking of policy setting we already have in configuration files, and here the situation is still quite unclean. I'll think about it more when porting the patch to Fedora.

In that case please create an issue for the future development. We can look on this later.

**Comment by rvykydal** [comment]
> > > LGTM
> > > If this behavior is also in Fedora than maybe we should use configuration files to solve this in future.
> > 
> > 
> > Yes, I was thinking about it but it would require reworking of policy setting we already have in configuration files, and here the situation is still quite unclean. I'll think about it more when porting the patch to Fedora.
> 
> In that case please create an issue for the future development. We can look on this later.

INSTALLER-2154

**Comment by rvykydal** [comment]
PR with port to Fedora: https://github.com/rhinstaller/anaconda/pull/2833

**Pull request merged**
