### PR TITLE
Remove the pwpolicy kickstart command

### PR DESCRIPTION
**Pull request by poncovka**
The command was deprecated in Fedora 34. Let's remove it.

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me, nice cleanup! :)

**Comment by poncovka** [comment]
> Looks good to me! The commit message should also mention that the `%anaconda` section is deprecated, as that's what happens.

The `%anaconda` section is already deprecated. I've just reorganized the code a little.

**Review by VladimirSlavik — APPROVED** [review]
Sorry - then it's fine as is!

**Pull request merged**
