### PR TITLE
timezone: for kickstart allow also timezones not offered by GUI

### PR DESCRIPTION
**Pull request by rvykydal**
Port of https://github.com/rhinstaller/anaconda/pull/1149 from RHEL 7.

TODO:

- [x] kickstart test

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
LGTM, thank you.

I assume we don't want to migrate to `zoneinfo` (as upstream) in a minor RHEL due to the changed list, right?

**Comment by rvykydal** [comment]
> LGTM, thank you.
> 
> I assume we don't want to migrate to `zoneinfo` (as upstream) in a minor RHEL due to the changed list, right?

I didn't find a reason why we should, so I'm trying to stay on a safer (afaik) side wrt changes in minor release.

**Comment by VladimirSlavik** [comment]
Agreed.

(That also means that we need to track the different valid timezone list as a change for RHEL 10.)

**Comment by rvykydal** [comment]
kickstart test: https://github.com/rhinstaller/kickstart-tests/pull/1032

**Pull request merged**
