### PR TITLE
timezone: for kickstart allow also timezones not offered by GUI

### PR DESCRIPTION
**Pull request by rvykydal**
Port of https://github.com/rhinstaller/anaconda/pull/1149 from RHEL 7.

TODO:
- [x] kickstart test

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]

**Comment by rvykydal** [comment]
kickstart test: https://github.com/rhinstaller/kickstart-tests/pull/1032

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well.

**Comment by jkonecny12** [comment]
Hi @rvykydal, just a heads-up I changed commit message to put one more bug to the list which should be solved by this too.

**Pull request merged**
