### PR TITLE
 webui: do not hardcode the pretty name in installation progress

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]

**Review by rvykydal — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
LGTM.

**Comment by KKoukiou** [comment]
Since we 're not delivering to f39 we can close all webui PRs on f39 branch? @jkonecny12

**Review by vojtechtrefny — APPROVED** [review]

**Comment by vojtechtrefny** [comment]
> Since we 're not delivering to f39 we can close all webui PRs on f39 branch? @jkonecny12

There is a plan to make webUI accessible from F39 with a boot option for testing so I guess we still want the fixes in there. So I guess we just have to wait for the beta freeze to be over to get this in.

**Comment by M4rtinK** [comment]
@KKoukiou @vojtechtrefny So I guess we can indeed close this now ?

**Pull request closed without merging**
