### PR TITLE
webui: tests: Fix WebUI end2end tests

### PR DESCRIPTION
**Pull request by velezd**
This should fix e2e webui tests.

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
I don't really understand this change. There is a single button containing 'Reboot' string on the page, so why you need to make the selector more specific.

**Comment by velezd** [comment]
There isn't a single button. This is sort of a workaround. The page contains footer hidden by css that has Back, Next and Reboot buttons in it.

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Pull request merged**
