### PR TITLE
Allow to disable the Localization module

### PR DESCRIPTION
**Pull request by poncovka**
Check whether the Localization DBus module is enabled before it is used.
It might be disabled in the Anaconda configuration file.

The installer should skip standalone GUI spokes that return False from their
`should_run` method. There are no standalone TUI spokes.

(cherry-picked from commits efc6278 and 1df4c77)

Related: rhbz#1834535

### CODE REVIEW

**Comment by poncovka** [comment]
Updated.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
