### PR TITLE
Add support for NPIV enabled zFCP devices

### PR DESCRIPTION
**Pull request by jstodola**
This change allows to use NPIV-enabled zFCP devices in anaconda. Such devices can be configured just based on their device number, WWPN and LUN are useless.
Also update the width of the "Add zFCP" dialog, since with additional text it would use the whole with of the screen.

Ported from https://github.com/rhinstaller/anaconda/pull/4188

Resolves: rhbz#1497086

### CODE REVIEW

**Comment by jstodola** [comment]
pykickstart-3.16.15-1.el8 is needed for the unit/rpm tests to pass.

**Review by rvykydal — APPROVED** [review]
Thank you

**Comment by jstodola** [comment]
Updated comments and user visible text based on feedback from @steffen-maier in https://github.com/rhinstaller/anaconda/pull/4188#pullrequestreview-1023617370

**Comment by steffen-maier** [comment]
> Should zfcp-attached be all lowercase?

I don't have a very strict opion. As zfcp developer, I kind of settled with lowercase as it's easier to type and any kind of uppercase variants such as zFCP or ZFCP seem somewhat made up to me. But then again I wasn't involved in creating the device driver so I might miss on earlier naming conventions. Feel free to change casing as you chose.

**Comment by VladimirSlavik** [comment]
As a former tech writer, I'd use "zFCP" when talking about the technology in general, which is the case here.

The other "right" option is to mark it up like `zfcp` when talking about some technical item where the case matters, such as package or tool. But that's not case here, I think?

**Comment by jstodola** [comment]
Just updated the label text (see https://github.com/rhinstaller/anaconda/pull/4188#issuecomment-1172878333 for details).
But unit-tests/rpm-tests are still failing with `fatal: It seems that there is already a rebase-merge directory, and I wonder if you are in the middle of another rebase....` developer's help is needed...

**Comment by VladimirSlavik** [comment]
The git problem went away somehow, but the tests now hit https://github.com/rhinstaller/pocketlint/issues/45.

**Review by jkonecny12 — APPROVED** [review]

**Pull request merged**
