### PR TITLE
Package install and debug message logging.

### PR DESCRIPTION
**Pull request by KosiehBarter**
This is rework of #214, where was major issue with logging translated
messages to anaconda.log file.

In this rework, this issue is fixed as well as code was cleaned from
previous junk made in attempt to add package logging support.

This rework is attempt to improve package logging, where untranslated
string is logged and translated string is returned back to GUI for user.

Personal thanks for JKonecny for giving details for translation and VPodzime for consultation.

Signed-off-by: Karel Valek <kvalek@redhat.com>

### CODE REVIEW

**Comment by vpodzime** [comment]
Other than the two issues reported by our tests (two unused imports) this looks good to me. Thanks for the rework!

**Comment by dashea** [comment]
Ignore the issue reported about progress.py not being in POTFILES.in. This is a bug in gettext_potfiles.py

**Comment by jkonecny12** [comment]
Don't we want to remove duplicate logging? It's here for some time now but when you call ``progress_report`` the string is logged in ``progress_message`` and ``progress_step`` too.
I'm thinking of removing the ``progress_step`` logging or add prefix there, now they have identical output so we don't know which method printed it.

**Comment by KosiehBarter** [comment]
LOCAL UPDATE - Based on JKonecny's suggestion, progress_step is commented and my local update is working correctly (no duplicated logs).

I am not commiting this change, because it is not designed for this topic. But I think it could be included as well, because of saving test run.

**Comment by vpodzime** [comment]
> Don't we want to remove duplicate logging? It's here for some time now but when you call progress_report the string is logged in progress_message and progress_step too.
> I'm thinking of removing the progress_step logging or add prefix there, now they have identical output so we don't know which method printed it.

Good catch. I think we should make use of the message in ``progress_step`` too, just append something like `` -- DONE`` to it so that we can see in the logs when the action started and when it was done.

**Comment by jkonecny12** [comment]
Good solution @vpodzime.
Could you please add it there @KosiehBarter?

**Comment by bcl** [comment]
Looks good to me.

**Comment by vpodzime** [comment]
Looks good to me too.

**Comment by KosiehBarter** [comment]
Cherry-picked locally and pushed.

**Pull request closed without merging**
