### PR TITLE
Backport NVMe-oF to RHEL-10

### PR DESCRIPTION
**Pull request by jkonecny12**
Backport of https://github.com/rhinstaller/anaconda/pull/4514 .

Resolves: [RHEL-27200](https://issues.redhat.com/browse/RHEL-27200)

### CODE REVIEW

**Review by KKoukiou — APPROVED** [review]

**Comment by jkonecny12** [comment]
/
/kickstart-test --testtype smoke

**Review by vojtechtrefny — APPROVED** [review]

**Review by jstodola — APPROVED** [review]
Just a basic testing passed - the installer shows a tab for NVMe/oF devices.
I wasn't able to do an installation to NVMe/oF device, since the initrd doesn't include the `nvmf` module yet to activate NVMe/TCP devices automatically.

**Comment by jkonecny12** [comment]
Thank you for testing!

**Comment by jkonecny12** [comment]
Update linked issue in the commit messages and rebased. No changes to the code.

**Pull request merged**
