### PR TITLE
Master nosetests directories 2

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Second round of test moves.

(Previous: #2901)

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
I think this should not conflict with anything recently opened, but I might be wrong.

**Review by jkonecny12 — APPROVED** [review]
LGTM! Not affecting me.

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Comment by poncovka** [comment]
> I think this should not conflict with anything recently opened, but I might be wrong.

I might have a conflict, but it doesn't matter.

**Comment by VladimirSlavik** [comment]
Thank you! Merging.

**Pull request merged**
