### PR TITLE
infra: Revert DNF 5 changes in containers

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Revert "Fix anaconda-rpm container for DNF5 (#infra)"

This reverts commit 3056776f5f41e08b0b9a5021fc44faaefdb2fade.

----

I am not sure how fast this will propagate and what it affects, so let's check the situation more than just merging this...

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Webui will need also revert of 613edf13fc813597920f2b12c9e8d9d3be80b530, I think, but I'm not including this here because it works on a different schedule.

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Review by vojtechtrefny — APPROVED** [review]

**Pull request merged**
