### PR TITLE
Mark a flaky pylint warning as a false positive (#infra)

### PR DESCRIPTION
**Pull request by poncovka**
The warning from `NetworkService.get_team_devices` about the `device_type` member of
`AttachedSubscription` class appears randomly, but it is always a false positive.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by jkonecny12 — APPROVED** [review]
Thanks for this. I encountered this issue again today.

Could you please add TODO to the code to know that we want to solve this issue in the future somehow?

**Comment by poncovka** [comment]
@jkonecny12, I think that it will disappear on its own with a new pylint, so it will be always listed in unused false positives.

**Comment by VladimirSlavik** [comment]
I believe I have seen a false positive disappear and reappear, so a TODO is unneeded, I think.

**Pull request merged**
