### PR TITLE
Add some basic storage kickstart tests

### PR DESCRIPTION
**Pull request by dwlehman**
I only tested these by installing with the ks files, verifying the results and, in some cases, running the `%post` manually with `set -x` to make sure things were behaving as intended.

### CODE REVIEW

**Comment by mulkieran** [comment]
To be correct, the Python code for percent test (third commit) should not use floating point computation and maybe test should show a little more flexibility on numeric value of percent. I'm happy to defer worrying about that until the first time the test detects a spurious error, though, which it may never do.

And, in the first commit, I'm puzzled why it's certain that blkid will have a LABEL key (if install ran correctly).

Other than that, it looks fine to me.

**Comment by dwlehman** [comment]
I thought floating point math would be adequate for the task given that we're only computing percentages. If this is not necessarily the case I should do it differently.

blkid will always have a `LABEL=` key for the root LV because I've specified `--label=root` in the logvol line that defines it.

**Comment by dwlehman** [comment]
New version with fixed virt-cat invocations. I verified that virt-cat can get stuff from LVs if specified as `/dev/<vg>/<lv>` or `/dev/mapper/<vg>-<lv>`.

**Comment by dwlehman** [comment]
pushed

**Pull request closed without merging**
