### PR TITLE
The NTP server dialog without entries shouldn't crash (#2001591)

### PR DESCRIPTION
**Pull request by poncovka**
Don't crash if there are no NTP servers in the dialog.

Resolves: rhbz#2001591

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me, thank you for the fix!

**Comment by poncovka** [comment]
Resolved pylint issues.

**Comment by VladimirSlavik** [comment]
IMO, feel free to merge. The code did not change such that a re-review would be needed...

**Pull request merged**
