### PR TITLE
Print warning for boot args without `inst.` prefix

### PR DESCRIPTION
**Pull request by jkonecny12**
Deprecate use of Anaconda boot arguments without `inst.` prefix. Our intention is to disable these completely in the future.

### CODE REVIEW

**Comment by poncovka** [comment]
The warning message is very vague. Shouldn't it say that the support will be removed in Fedora 34?

**Comment by jkonecny12** [comment]
Good point. I'll try to change it. However, I would like to avoid setting deadline for that, you never know what could happen.

**Comment by jkonecny12** [comment]
**UPDATED:**
* Improve both deprecation messages.

**Comment by jkonecny12** [comment]
What do you think now @poncovka ?

**Comment by VladimirSlavik** [comment]
I think you might want to change also `boot-options.rst`, especially the following sentence:

> Options specified without the ``inst`` prefix are
> recognized, but the prefix may be required in a future release.

**Comment by jkonecny12** [comment]
> I think you might want to change also `boot-options.rst`, especially the following sentence:
> 
> > Options specified without the `inst` prefix are
> > recognized, but the prefix may be required in a future release.

Good point. I'll do that.

**Comment by jkonecny12** [comment]
**UPDATED:**
* Implemented note from @VladimirSlavik, thanks!

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Comment by jkonecny12** [comment]
It's two weeks without objection. Merging now.

**Pull request merged**
