### PR TITLE
Deprecate nompath

### PR DESCRIPTION
**Pull request by VladimirSlavik**
SSIA.

~~Currently trying to test.~~

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Can test, does not work. Yay.

**Comment by poncovka** [comment]
The change should be documented in a release note.

**Review by poncovka — APPROVED** [review]
Looks good me. Thanks!

**Comment by VladimirSlavik** [comment]
/kickstart-test --testtype smoke

Sorry, added one more commit with docs for future me.

**Review by poncovka — APPROVED** [review]
Thanks for writing the documentation :-)

**Pull request merged**
