### PR TITLE
webui: catch exceptions from the backend in all actions

### PR DESCRIPTION
**Pull request by KKoukiou**
For this let's move criticalError to the central store.

### CODE REVIEW

**Comment by KKoukiou** [comment]
I advice whoever reviews this one to do it with ignoring whitespace changes; https://github.com/rhinstaller/anaconda/pull/5251/files?diff=unified&w=1

**Comment by KKoukiou** [comment]
Needs some work.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by adamkankovsky — APPROVED** [review]
I didn't find anything wrong. Looks good.

**Pull request merged**
