### PR TITLE
Use the software selection cache in GUI

### PR DESCRIPTION
**Pull request by poncovka**
Use the DNF manager and the software selection cache to choose environments
and groups in the graphical user interface.

Drop deprecated support for comps from the DNF payload.

### CODE REVIEW

**Comment by poncovka** [comment]
Can I ask for a review, please?

**Review by M4rtinK — APPROVED** [review]
Looks good to me. Quite some cleanup! :)

**Review by jkonecny12 — APPROVED** [review]
Looks great to me. I just have a few nitpicks below. Feel free to ignore them.

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
