### PR TITLE
Turn off audit instead of using a custom binary to trap output

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This runs `auditctl -e 0` instead of our custom binary that eats audit messages.

Depends on https://github.com/weldr/lorax/pull/1271

----

Previously:

- clean up most things audit in lorax templates
- install a custom replacement for auditd from the anaconda packages, again in templates
- run the replacement manually in anaconda

Now:

- keep audit things in templates as they are
- do not install the custom replacement binary in templates
- in anaconda, run `auditctl -e 0` instead of the custom binary

Overall goals remain the same and met:

- keep boot.iso small: this adds +200 KiB-ish
- do not run auditd to lower runtime memory requirements: still ok
- do not spam journal/syslog with audit messages: still ok

Note: Most audit messages come from dracut, where it is not turned off anyway.

----

Note 2: To have no audit messages, boot with `audit=0`

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me - nice cleanup! :)

**Comment by VladimirSlavik** [comment]
Hi Brian @bcl, could you please make another rawhide lorax release? The changes are merged but not released yet, so this is blocked...

**Comment by VladimirSlavik** [comment]
New lorax tagged, waiting for the repos... https://koji.fedoraproject.org/koji/buildinfo?buildID=2074269

**Pull request merged**
