### PR TITLE
Add "class" to password_policies

### PR DESCRIPTION
**Pull request by Rtoax**
For example:

```
    Password    Class
    1234        1
    1abc        2
    1aBC        3
    1aB!        4
```

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
@Rtoax thanks for the PR. 

Can you please describe the use case for this new feature? How does the class differs from the quality? Did not go through the code but I would like to see this in the commit message these information.

It's also missing tests; Probably to be inserted at: tests/unit_tests/pyanaconda_tests/modules/common/test_policy.py 

Before you put more effort on this give the team a short time to react on the desirability of this feature. 

CC @poncovka any thoughts?

**Comment by Rtoax** [comment]
> @Rtoax thanks for the PR.
> 
> Can you please describe the use case for this new feature? How does the class differs from the quality? Did not go through the code but I would like to see this in the commit message these information.
> 
> It's also missing tests; Probably to be inserted at: tests/unit_tests/pyanaconda_tests/modules/common/test_policy.py
> 
> Before you put more effort on this give the team a short time to react on the desirability of this feature.
> 
> CC @poncovka any thoughts?

This commit just do the same thing like libpwquality's `minclass` in `/etc/security/pwquality.conf`

# How/What to use/show

image

image

**Review by KKoukiou — COMMENTED** [review]
I see the libpwquality has a configuration option for the mean class. We are already using this library for validation password quality, and the checks for length are passed through that. 

I see minclass is a configurable option in the pwquality library, so it looks like more reasonable to work on that direction.

I see the checks for minlen are on this direction so probably the logic can be stolen from that. How do you see this? Are you satisfied with this solution direction?

**Comment by KKoukiou** [comment]
Closing because of long time inactivity. If you 're still actively interested feel free to ping to reopen.

**Pull request closed without merging**
