### PR TITLE
Do not set default fstype for blivet-gui

### PR DESCRIPTION
**Pull request by vojtechtrefny**
We do not loger need to do it here, see
https://github.com/storaged-project/blivet-gui/pull/141

---
We'll probably need to do a chain build together with blivet-gui for rawhide after both PRs get merged.

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
updates image for Fedora 30: https://vtrefny.fedorapeople.org/img/blivet-gui-fstype.img

**Comment by poncovka** [comment]
Could you also change the version of Blivet-GUI in the `.spec` file, please?

**Comment by vojtechtrefny** [comment]
> Could you also change the version of Blivet-GUI in the .spec file, please?

Fixed. New version of blivet-gui will be 2.1.12 but it will take week or two to release it.

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Pull request merged**
