### PR TITLE
Install support for non-ascii keyboard layouts (#1919483)

### PR DESCRIPTION
**Pull request by poncovka**
Non-ascii keyboard layouts require the kbd-legacy package.

Resolves: rhbz#1919483

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by AdamWill** [comment]
systemd-udev requires kbd, so that's probably not going anywhere.

**Comment by jkonecny12** [comment]
I'm using this PR to test coverage tests. Please feel free to ignore the failure and sorry for the noise here.

**Comment by AdamWill** [comment]
So this just missed the most recent package build, and now F34 has branched from Rawhide. We will definitely want this fix in F34 as well as Rawhide. Thanks!

**Comment by M4rtinK** [comment]
@AdamWill Noted, we will make sure this fix makes it to both F34 & Rawhide. :)

...once we fix some more [Autotools madness](https://github.com/rhinstaller/anaconda/pull/3164).

**Pull request merged**
