### PR TITLE
Fix IndexError: list index out of range (#1219004)

### PR DESCRIPTION
**Pull request by jkonecny12**
Add user input boundary test to text ui Timezone settings.

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me. We just may need to add the ``< 0`` check in some other places too.

**Comment by mulkieran** [comment]
I'm puzzled by a couple of things:
* why check ```keyid < 0``` since a negative index is valid in Python?
* why is an ```IndexError``` accessing in ```_regions``` array considered a normal behavior...i.e. why is the int key that is out of array bounds still useful to input()'s caller
* what about the access that uses keyid in ```self._timezones[args][keyid]``` expression? why is it not necessary to worry about ```IndexError``` in that case?

**Comment by jkonecny12** [comment]
> why check keyid < 0 since a negative index is valid in Python?

Yes it's valid but it's confusing for the user. I think it's better to set nothing than set something confusing.

> why is an IndexError accessing in _regions array considered a normal behavior...i.e. why is the int key that is out of array bounds still useful to input()'s caller

I think this is normal behavior of event processing. There is possible to return ``INPUT_PROCESSED`` instead but I think it's not so clean as this solution. What if someone add some special option later or add default choice to 0 key.

> what about the access that uses keyid in self._timezones[args][keyid] expression? why is it not necessary to worry about IndexError in that case?

Yeah that is my fail. I'll fix the pull request because now it's crashing in the inner choice :( . Sorry for that.

**Comment by jkonecny12** [comment]
Pull request is updated now.

**Comment by vpodzime** [comment]
Same comments as @mulkieran had, but I think both are okay to be addressed when pushing the patch.

**Comment by vpodzime** [comment]
Looks good to me now.

**Comment by jkonecny12** [comment]
Pushed.
Thank you @vpodzime and @mulkieran for your responses. They were valuable.

**Pull request closed without merging**
