### PR TITLE
Decode wifi SSIDs into strings. (#1240398)

### PR DESCRIPTION
**Pull request by dashea**
Use the chardet module to try to detect what encoding the SSID uses.
Add a column to the wireless network ListStore in the network spoke to
store the original byte sequence (also encoded as a string because GLib
is awful at storing byte sequences).

### CODE REVIEW

**Comment by cgwalters** [comment]
Ok, this is because `type_name_mangle("GBytes")` -> `gbytes_get_type`.  This is clearly a GTK+ bug but in the meantime you could work around it by doing:

```
from gi.repository import GLib
GLib.Bytes # Force the gtype to be registered by side effect
```

This having to force types to be registered to use Glade has been a pain point with it forever.

**Comment by dashea** [comment]
> Ok, this is because type_name_mangle("GBytes") -> gbytes_get_type. This is clearly a GTK+ bug but in the meantime you could work around it by doing:

$ cat test.py 
```
#!/usr/bin/python3

import gi
gi.require_version('Gtk', '3.0')

from gi.repository import Gtk, GLib

GLib.Bytes

builder = Gtk.Builder.new_from_file('test.glade')
store = builder.get_object('test_store')

store.append(['asdf', b'asdf'])

window = builder.get_object('test_window')
window.connect('delete-event', Gtk.main_quit)
window.show_all()
Gtk.main()
```

$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    store.append(['asdf', b'asdf'])
  File "/usr/lib64/python3.4/site-packages/gi/overrides/Gtk.py", line 956, in append
    return self._do_insert(-1, row)
  File "/usr/lib64/python3.4/site-packages/gi/overrides/Gtk.py", line 947, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib64/python3.4/site-packages/gi/overrides/Gtk.py", line 857, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib64/python3.4/site-packages/gi/overrides/Gtk.py", line 875, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib64/python3.4/site-packages/gi/overrides/GObject.py", line 218, in __init__
    self.set_value(py_value)
  File "/usr/lib64/python3.4/site-packages/gi/overrides/GObject.py", line 283, in set_value
    self.set_boxed(py_value)
  File "/usr/lib64/python3.4/site-packages/gi/overrides/GObject.py", line 231, in set_boxed
    _gobject._gvalue_set(self, boxed)
TypeError: Expected Boxed

**Comment by cgwalters** [comment]
The list store doesn't know how to auto-coerce Python `bytes` to GBytes, so you'd need:

```
store.append(['asdf', GLib.Bytes.new(b'asdf')])
```

**Comment by dashea** [comment]
Updated to use GBytes, dumped the chardet module in favor of a libnm-util function that does the same thing, and changed nm._settings_for_ap to leave the SSID as bytes when looking up a connection by ssid.

Tested with ASCII and UTF-8 SSIDs. It's not able to connect to a latin-1 SSID but it looks like that's a NM bug: NetworkManager is crashing and it appears to be because nm_utils_ssid_to_utf8 is returning NULL on the other end of the dbus call.

**Comment by dashea** [comment]
Actually, what I could have done is just set the column type to PyObject and not worry about boxing and unboxing at all. So maybe one more try at this, tomorrow.

**Comment by cgwalters** [comment]
Definitely, that makes a lot of sense.  Using `GBytes` is useful when you have large buffers (e.g. wrapping `GMappedFile`) that is mostly passed between C -> binding -> C, then you don't pay for lots of memcpy.  But that doesn't apply here.

**Comment by dashea** [comment]
Updated to store Python's byte array type instead of GLib's

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by dashea** [comment]
Pushed.

**Pull request closed without merging**
