### PR TITLE
Python 3 Anaconda

### PR DESCRIPTION
**Pull request by M4rtinK**
This pull request changes Anaconda to use Python 3 as requested in the "Python 3 as Default" Fedora change proposal[0] and tracked in bug 1014220[1]. All Python 2-only dependencies are also dropped and replaced by Python 3 equivalents. Please note that this is a forward port to Python 3 without keeping Python 2 compatibility.

[0] https://fedoraproject.org/wiki/Changes/Python_3_as_Default
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1014220

### CODE REVIEW

**Comment by vpodzime** [comment]
Weeeee!!!!! :) I think you can drop the bug reference in all the commits above.

**Comment by M4rtinK** [comment]
@vpodzime I've actually used it on purpose and would like to keep it, so that we can easily identify the Python 3 supports commits in the future.

**Comment by M4rtinK** [comment]
@clumens makeupdates is using just some version comparison code from yum-utils, I'll look for a different provider of that (I'm sure DNF needs to have something similar).

**Comment by jkonecny12** [comment]
This PR looks ok to me.

**Comment by M4rtinK** [comment]
Pushed manually.

**Pull request closed without merging**
