### PR TITLE
Improve RHS summary strings in multiselection (#1265620)

### PR DESCRIPTION
**Pull request by jkonecny12**
The code is better for reading and especially for translation now.
The strings are using old ``%`` formatting now which is better for the tests.

*Related: rhbz#1265620*

It's follow-up on the PR https://github.com/rhinstaller/anaconda/pull/483. @dashea is it good now?

### CODE REVIEW

**Comment by dashea** [comment]
It like the new select_tmpl (minus the context), but this commit does change how the strings are displayed. The product name is no longer displayed in bold, and on the "0 of x mount points" lines, only the numbers are shown in gray instead of the full line.

**Comment by dashea** [comment]
One other note on the product name, and using markup in format strings in general: parameters inserted into markup strings should be escaped using pyanaconda.ui.gui.utils.escape_markup. There's normally a check for it but the usage here tricks the pocketlint test.

**Comment by jkonecny12** [comment]
Ahh sorry I'm a fool. How I could missed that. 
I'll do the updated version and I'll remove the context.

It's nice to see the patch you created. I'll leave this commit in the old style but I'm going to use the new style in future.

**Comment by jkonecny12** [comment]
Updated.
I hope it's good now.

**Comment by dashea** [comment]
Looks good now, thanks

**Comment by jkonecny12** [comment]
Pushed. Thank you.

**Pull request closed without merging**
