### PR TITLE
Fix Packit configuration for f36-release branch (#infra)

### PR DESCRIPTION
**Pull request by jkonecny12**
By changing the propose downstream here we should get releases on this branch to the correct downstream branch.

See https://github.com/packit/packit-service/issues/1298 for more info.

### CODE REVIEW

**Comment by jkonecny12** [comment]
This is blocked because the Fedora branching is not yet available. There is no such target now.

**Review by poncovka — APPROVED** [review]
Thanks!

**Review by VladimirSlavik — COMMENTED** [review]
The branching docs should be adjusted too. Please mention this file as one of the places to change something, and if it makes sense, describe the changes needed.

**Review by VladimirSlavik — APPROVED** [review]

**Comment by jkonecny12** [comment]
Good point with the docs.

**Comment by jkonecny12** [comment]
> The branching docs should be adjusted too. Please mention this file as one of the places to change something, and if it makes sense, describe the changes needed.
> 
> Edit: Ah, of course docs need to be changed on master. Will ack this.

https://github.com/rhinstaller/anaconda/pull/3827

**Comment by jkonecny12** [comment]
Fedora branching is now finished. Everything should be in place. (except pykickstart)

**Comment by jstodola** [comment]
@jkonecny12 🛌

**Comment by jkonecny12** [comment]
Failed KS tests are not related to this PR.

**Pull request merged**
