### PR TITLE
Remove 'linear' from list of expected MD RAID levels

### PR DESCRIPTION
**Pull request by vojtechtrefny**
RHEL 10 version of #5672

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good, thanks!

**Comment by KKoukiou** [comment]
Still blocked on https://issues.redhat.com/browse/RHEL-38386

**Comment by KKoukiou** [comment]
Sorry this is now available in latest RHEL 10 nightly compose, we can merge.
@jstodola are you ok with this?

**Pull request merged**
