### PR TITLE
infra: automate koji build and bodhi update actions with packit

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
@VladimirSlavik are the failures relevant? seems like not?

**Comment by VladimirSlavik** [comment]
Absolutely irrelevant. Infrastructure check tries to ensure that only infrastructure changes (see `.structure-config`) happen in the PR with label "infrastructure".

**Review by VladimirSlavik — CHANGES_REQUESTED** [review]
This should not be in the upstream repo, but in dist-git. From https://packit.dev/docs/configuration/downstream/koji_build :

> A Packit config file needs to be in the dist-git repository to allow this job to be triggered.

**Comment by KKoukiou** [comment]
> This should not be in the upstream repo, but in dist-git. From https://packit.dev/docs/configuration/downstream/koji_build :
> 
> > A Packit config file needs to be in the dist-git repository to allow this job to be triggered.

The packit config file is in the upstream repository and it's auto-synced to the dist-git. https://packit.dev/docs/configuration#files_to_sync 

So the while packit configuration belongs to the upstream packit.cfg.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by jkonecny12** [comment]
Sorry for late comment but is there a reason to not enable this also for all supported Fedoras? Packit have an alias for that from what I remember.

**Comment by KKoukiou** [comment]
@jkonecny12 I believe it's enabled https://github.com/rhinstaller/anaconda/pull/5354/commits/e52952e4027b41b11a0964b7cd13239525a9745c#diff-553da68308bd33d94ee7dfc179ad50968916c37c7a58452f707454e918724015R88 on the template file.

Of course now we are on master branch so the rawhide was only affected. When we branch out fedora-40 it will be updated correctly.

**Pull request merged**
