### PR TITLE
Add a new separator after the default keyboard layout

### PR DESCRIPTION
**Pull request by poncovka**
Improve the code. Separators shouldn't provide a layout.

**Related:** https://github.com/rhinstaller/anaconda/pull/3667#issuecomment-954910287

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
LGTM, thanks!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks!

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by poncovka** [comment]
Updated. I fixed a function for matching layouts based on the typed string.

**Review by jkonecny12 — APPROVED** [review]
Looks even better.

**Pull request merged**
