### PR TITLE
network: add support for --no-activate kickstart opton (#1277975)

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1277975

This will allow to override special default of first network command
which is --activate.

### CODE REVIEW

**Comment by jkonecny12** [comment]
Looks good to me.

**Comment by jkonecny12** [comment]
When there will be new version of pykickstart available (tomorrow should be fine, it's from COPR), please run the Jenkins test again.

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
jenkins, test this please

**Pull request merged**
