### PR TITLE
Sync po/Makefile.am with master and install git in the rpm container

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
Attempt to fix: https://gitlab.com/redhat/centos-stream/rpms/anaconda/-/merge_requests/102

**Review by jkonecny12 — APPROVED** [review]
I guess it's correct. There are some changes which I'm not sure why it's there.
Ideally please make check that we understand everything what is changing and why.

**Review by jkonecny12 — APPROVED** [review]

**Comment by jkonecny12** [comment]
Looks good to me now.

**Pull request merged**
