### PR TITLE
infra: do not run manual kickstart tests on PR

### PR DESCRIPTION
**Pull request by rvykydal**
Depends on: https://github.com/rhinstaller/kickstart-tests/pull/1003

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thank you! Looks good to me, even if it's very minimalistic. For now, it's certainly enough of a step forward.

**Comment by VladimirSlavik** [comment]
To expand on the minimalistic part: I believe this makes it so that one cannot run these tests, even if explicitly listed. However, that's fine, I think - one can run the tests locally after all. And this is miles better than having to look through the results for every. single. detail. on. every. test.

For a complete solution we'd have to add an argument to enable/disable this, parse the args in more detail for that, and add logic to select the skip array variable based on branch name.

**Comment by rvykydal** [comment]
@VladimirSlavik yes, it is very minimalistic. When I tried to think about more complex stuff I started to believe that having the `--testtype` and `--skip-testtypes` API already available via the comment, together with the info in https://github.com/rhinstaller/kickstart-tests/blob/master/containers/runner/skip-testtypes, should be enough for the user to construct the set on his own.

**Comment by VladimirSlavik** [comment]
Yes, I agree it's too complex. There's also the issue of different ignore lists for different types of runs.

**Pull request merged**
