### PR TITLE
Remove RpmDb setup for OSTree payloads

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Related to https://fedoraproject.org/wiki/Changes/RelocateRPMToUsr

Resolves: [rhbz#2050428](https://bugzilla.redhat.com/show_bug.cgi?id=2050428)

@cgwalters - Can you please take a look? Basically I have no idea what I'm doing, but it seems to work, except it somehow worked before too, so... `¯\_(ツ)_/¯`

### CODE REVIEW

**Comment by cgwalters** [comment]
systemd-tmpfiles is only really relevant for content in `/var`.  Since the rpmdb is now (correctly) in `/usr`, I think we can just delete the lines of code that talk about `/var/lib/rpm` entirely.

**Comment by VladimirSlavik** [comment]
Thank you, I will try to remove these and see if it still works. Given installation worked just fine both before and after the path change, I think that's correct and will work too.

**Comment by VladimirSlavik** [comment]
/kickstart-test --testtype smoke

Yes, removing "it" seems to work just fine.

**Review by M4rtinK — APPROVED** [review]
Looks good  to me, thanks! :)

**Review by poncovka — APPROVED** [review]
Thanks!

**Comment by VladimirSlavik** [comment]
Oops! Sorry, fixed.

**Pull request merged**
