### PR TITLE
Modernize javascript (fedora-welcome)

### PR DESCRIPTION
**Pull request by fmuellner**
Both the javascript standards and support in gjs/gnome have changed quite a bit since the code was originally written. Update the code to match the current best practices (without changing any of the logic or UI).

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me, thank you!

**Comment by VladimirSlavik** [comment]
@fmuellner did you test these changes? If not, how would one do that?

**Comment by fmuellner** [comment]
> @fmuellner did you test these changes? If not, how would one do that?

Yes. I copied liveinst.desktop, changed the Exec line to `/usr/bin/true` and moved the file to `~/.local/share/applications`. Then I created this fake liveinst command in `~/.local/bin`:
```
#!/bin/sh
notify-send -h boolean:transient:true "Pretend I'm a snake"
```

After that, `fedora-welcome.js` can be run normally on the host.

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks a lot! :)

**Comment by VladimirSlavik** [comment]
Ah, ok, thanks. I will try this also on the live media. I suspect that's just a formality, but you never know...

**Review by jkonecny12 — APPROVED** [review]
Thanks for your help!

**Pull request closed without merging**
