### PR TITLE
Replace the mpath flag with a configuration option

### PR DESCRIPTION
**Pull request by VladimirSlavik**
SSIA... another flag goes, hopefully with less fuss.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
I hope to fix all the test comparisons in a subsequent PR just for that. I am changing too much of that file right now.

**Comment by poncovka** [comment]
I did some digging in the history and I think that `inst.nompath` should work the same way as `inst.nodmraid`. Blivet actually has a flag called `multipath`, that we happily ignore and Blivet doesn't use at all. That's suspicious. It would be good to figure it out, because the option might end up in `User Interface` instead of the `Storage` section based on the current usage.

@vojtechtrefny, what do you think?

**Comment by vojtechtrefny** [comment]
> I did some digging in the history and I think that `inst.nompath` should work the same way as `inst.nodmraid`. Blivet actually has a flag called `multipath`, that we happily ignore and Blivet doesn't use at all. That's suspicious.

AFAICT we don't use the `multipath` flag at all and haven't been using it for years. Looks like we stopped using it when we stopped writing our own `multipath.conf` in this [commit](https://github.com/storaged-project/blivet/commit/e35af4fc7a75764b9c7a8aa082dc0e3a3fa791d8). If `nompath` should work like `nodmraid` it most likely didn't work like that for 8+ years.

**Comment by jkonecny12** [comment]
If it is not used for such long than I would suggest to remove it from Anaconda. Ideally to remove logic and leave just a boot option with deprecation notice and remove even the boot option on next-next Fedora?

**Comment by VladimirSlavik** [comment]
So there are really two things to be seen here:
- There is no actual storage-related logic (de)activated by the flag. Blivet is removing the last traces of this.
- The GUI is still changed by this option.

So there are really two ways forward:
- Take this PR and amend it to use the right conf section.
- Deprecate the option so that it can be removed later, which still removes the flag which is the actual goal here.

**Comment by jkonecny12** [comment]
Good point that it's changing GUI.

**Comment by VladimirSlavik** [comment]
We might instead try something like #3597...

**Comment by poncovka** [comment]
I would like to point out that `nompath` seems to disable the `multipathd` service. Is it possible that `nompath` without the `inst.` prefix somehow worked before we started to require the prefix? Maybe we should just support `nompath` instead of `inst.nompath`.

**Comment by VladimirSlavik** [comment]
Oh, that sounds pretty probable, actually. Just wonderful. In that case I think we should instead check if the multipath thingy is turned off, it knows better than we do when that is the case.

**Comment by jkonecny12** [comment]
> I would like to point out that `nompath` seems to disable the `multipathd` service. Is it possible that `nompath` without the `inst.` prefix somehow worked before we started to require the prefix? Maybe we should just support `nompath` instead of `inst.nompath`.

If this is true then we should probably also backport this solution to RHEL-9 because the issue will be even there.

**Comment by poncovka** [comment]
@jstodola, do you have any insights on this topic?

**Comment by VladimirSlavik** [comment]
I discussed this with Jan in person, and he thought removing the remains of mpath stuff would be best.

**Comment by jstodola** [comment]
Yes, I don't believe we need to have a mechanism to hide the Multipath tab (we do not have boot arguments to hide the SAN or NVDIMM tabs either). I would prefer to remove the hiding code, show the Multipath tab always and stop supporting the `inst.nosmt` boot argument (supposing it only affect the GUI). #3597 looks like a good direction to me.

**Pull request closed without merging**
