### PR TITLE
rhvh: fix EULA path for RHV-H

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Bug-Url: https://bugzilla.redhat.com/1949431
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

### CODE REVIEW

**Comment by poncovka** [comment]
Hi, the following changes should fix the unit tests:

```
diff --git a/tests/nosetests/pyanaconda_tests/product_test.py b/tests/nosetests/pyanaconda_tests/product_test.py
index d8c511ff20..8308f5c1d7 100644
--- a/tests/nosetests/pyanaconda_tests/product_test.py
+++ b/tests/nosetests/pyanaconda_tests/product_test.py
@@ -320,21 +320,23 @@ class ProductConfigurationTestCase(unittest.TestCase):
 
         self.assertListEqual(difference, expected_difference)
 
-    def _compare_product_files(self, file_name, other_file_name):
+    def _compare_product_files(self, file_name, other_file_name, ignored_sections=()):
         parser = create_parser()
         read_config(parser, os.path.join(PRODUCT_DIR, file_name))
 
         other_parser = create_parser()
         read_config(other_parser, os.path.join(PRODUCT_DIR, other_file_name))
 
-        # The defined sections should be the same.
-        self.assertEqual(parser.sections(), other_parser.sections())
+        # Ignore the specified and product-related sections.
+        ignored_sections += ("Product", "Base Product")
 
-        for section in parser.sections():
-            # Skip the product-related sections.
-            if section in ("Product", "Base Product"):
-                continue
+        sections = set(parser.sections()).difference(ignored_sections)
+        other_sections = set(other_parser.sections()).difference(ignored_sections)
 
+        # Otherwise, the defined sections should be the same.
+        self.assertEqual(sections, other_sections)
+
+        for section in sections:
             # The defined options should be the same.
             self.assertEqual(parser.options(section), other_parser.options(section))
 
@@ -344,7 +346,7 @@ class ProductConfigurationTestCase(unittest.TestCase):
 
     def ovirt_and_rhvh_test(self):
         """Test the similarity of oVirt Node Next with Red Hat Virtualization Host."""
-        self._compare_product_files("rhvh.conf", "ovirt.conf")
+        self._compare_product_files("rhvh.conf", "ovirt.conf", ignored_sections=("License", ))
 
     def valid_product_test(self):
         content = dedent("""

```

I can push them to your branch if you want to.

**Comment by sandrobonazzola** [comment]
yes please

**Comment by sandrobonazzola** [comment]
Added your suggested patch for the tests.

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
