### PR TITLE
Fix exclude arguments of tar payload extracting.

### PR DESCRIPTION
**Pull request by rvykydal**
The intention is to exclude subdirectories of the root directory.  --exclude
"sys/*" would exclude also /usr/include/sys/*.

Resolves: rhbz#1924118

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Looks good to me.

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by rvykydal** [comment]
PR with port to Fedora: https://github.com/rhinstaller/anaconda/pull/3142

**Pull request merged**
