### PR TITLE
Do not set platform-specific defaults in kstests workflow (#infra)

### PR DESCRIPTION
**Pull request by rvykydal**
They are loaded automatically based on --platform setting now.

### CODE REVIEW

**Comment by rvykydal** [comment]
@jkonecny12 Should I open PRs also for some other branch?

**Comment by VladimirSlavik** [comment]
No, kickstart tests are started by event that uses only workflows on master.

**Comment by rvykydal** [comment]
@VladimirSlavik thanks! Merging

**Pull request merged**
