### PR TITLE
Disable anaconda-core's requirement on subscription-manager on CentOS

### PR DESCRIPTION
**Pull request by carlwgeorge**
Resolves: rhbz#1984959

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. Thanks!

**Comment by jkonecny12** [comment]
Ignore the test failure. It is a dependency issue because of something else. I have to investigate that.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well.

**Pull request merged**
