### PR TITLE
WebUI: simplify translation formatting

### PR DESCRIPTION
**Pull request by jelly**
ngettext is for translations which can be one byte and two bytes.

### CODE REVIEW

**Review by KKoukiou — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]

**Review by rvykydal — APPROVED** [review]
Thank you

**Comment by jelly** [comment]
> There's literally a number in the output, so it's a message that can vary according to that number. The English string does not change, but is that true for all languages?

How would a translator figure that out? As both strings end up in the translation frontend as "$0 selected".

**Comment by VladimirSlavik** [comment]
Translators know what plurals are, especially when the translation UI shows them as such...

**Comment by KKoukiou** [comment]
This was correct as it was for the reason that @VladimirSlavik mentioned. Look at the italian translation for example.

[kkoukiou@sequioa anaconda]$ cat ui/webui/po/it.po | grep -A2 '0 selected' 
msgid "$0 selected"
msgid_plural "$0 selected"
msgstr[0] "$0 selezionato"
msgstr[1] "$0 selezionati"

**Pull request closed without merging**
