### PR TITLE
Clean up repositories for CI (#infra)

### PR DESCRIPTION
**Pull request by poncovka**
* Fix an id of the CRB repository.
* Don't use CRB and Buildroot to install lorax.
* Temporarily use the Buildroot repository for the ISO build.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well.

**Review by jkonecny12 — APPROVED** [review]
Thanks a lot for this!

**Pull request merged**
