### PR TITLE
Fixes in tui software selection

### PR DESCRIPTION
**Pull request by poncovka**
Some small fixes in the tui software selection spoke and the yum payload:

* If the software selection is defined by a kickstart file, we should remember it and use it until a new software selection is made. Resolves: rhbz#1371229
* The software spoke should not be initialized in the `status` method, but in the `initialize` method.
* If the `checkSoftwareSelection` finds a dependency error, we should report an error instead of showing the source changed message. Resolves: rhbz#979307
* Payload should be released also in a case that a dependency error is found.
* Release can raise an exception if we try to release resources from different threads. That should not happen and we should fix these cases. However, we don't want the installer to fail because of that either. Therefore, all exceptions from release will be catched and logged only.

### CODE REVIEW

**Comment by rvykydal** [comment]
Looks good to me.
I wonder if we can be comparing _selected None and 0 in status property of the patched file but I think it wouldn't change the behavior anyhow so perhaps never mind.

**Comment by M4rtinK** [comment]
jenkins, test this please

**Comment by M4rtinK** [comment]
(re-triggering tests now that the redundant & broken help content generation step has been removed from the makefile)

**Comment by poncovka** [comment]
Fixed and added new commits with fixes of bugs I have found.

**Comment by rvykydal** [comment]
Looks good to me, but each commit should have a rhbz Resolves/Related reference so please add them (two are missing it).

**Comment by poncovka** [comment]
Fixed.

**Pull request merged**
