### PR TITLE
RHEL-9: infra: bumpver: Fix wrong locale comming from JIRA

### PR DESCRIPTION
**Pull request by jkonecny12**
JIRA account is the one what define responses locale. Unfortunately this can't be changed from REST API. At the end it means that we need to use ID of the statuses instead of their name.

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me & seems to have worked when I tried it, thanks! :)

Rather insane that Jira behaves this way. :D

**Comment by jkonecny12** [comment]
Now it's tested and fixed the behavior.

Also I improved RHEL detection for the script which now doesn't depend on the git branch name anymore.

**Comment by jkonecny12** [comment]
@jstodola I'm changing the makebumver script here which is not in the list of infra files. I wonder, shouldn't I add it there?

**Comment by jkonecny12** [comment]
Added the `makebumpver` and related files into the infra files so they should be green on the `infrastructure-check` GH workflow.

**Review by M4rtinK — APPROVED** [review]
Looks good to me & worked when I tried it, thanks! :)

**Pull request merged**
