### PR TITLE
Fixed gtk warnings

### PR DESCRIPTION
**Pull request by poncovka**
Fixed most of the gtk warnings, the missing upper bar in spokes and some small problems with styles.
The remaining warnings should be caused by other components or they are probably bugs in gtk.

Resolves: rhbz#1433943
Resolves: rhbz#1439766

### CODE REVIEW

**Comment by poncovka** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
I am about to merge this commit of this PR:
https://github.com/rhinstaller/anaconda/pull/1006/commits/0b40f7b8e2799dd3932c52d4746ca8eb7bde0168
earlier as
https://github.com/rhinstaller/anaconda/pull/1012
so we don't have to wait for new Gtk in buildroot to prevent the related deadlocks.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by vpodzime** [comment]
Wooohoooo!

**Pull request merged**
