### PR TITLE
payload: raise exception on non zero exit code from rsync

### PR DESCRIPTION
**Pull request by KKoukiou**
Relevant to: rhbz#2326532

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

Really wondering why we ever did it like this, ignoring non-zero return codes. That's a time bomb essentially. :P

**Review by M4rtinK — COMMENTED** [review]
Actually, shouldn't this already handle the error state ?


```
        if reader.rc == 11:
            raise PayloadInstallationError(
                "Failed to install image: "
                "{} exited with code {}".format(cmd, reader.rc)
            )
```

Either way I think it should be at least remove - as far as I can tell, its referring to the `reader` variable that was removed.

**Comment by KKoukiou** [comment]
> Actually, shouldn't this already handle the error state ?
> 
> ```
>         if reader.rc == 11:
>             raise PayloadInstallationError(
>                 "Failed to install image: "
>                 "{} exited with code {}".format(cmd, reader.rc)
>             )
> ```
> 
> Either way I think it should be at least remove - as far as I can tell, its referring to the `reader` variable that was removed.

On my system it fails with return code 10, Input / Output socket error.

**Comment by jkonecny12** [comment]
Don't we return back this behavior?
https://bugzilla.redhat.com/show_bug.cgi?id=2231388

The code removed here was a fix for the bug.

**Comment by KKoukiou** [comment]
> Don't we return back this behavior? https://bugzilla.redhat.com/show_bug.cgi?id=2231388
> 
> The code removed here was a fix for the bug.

That commits that fixed the bug did much more than 

> Don't we return back this behavior? https://bugzilla.redhat.com/show_bug.cgi?id=2231388
> 
> The code removed here was a fix for the bug.

In the commits that fixes this bug, I can see how the added args to rsync were correctly added:
```
            "--info=flist2,name,progress2",  # show progress after each file
            "--no-inc-recursive",  # force calculating total work in advance
```

Ignoring exit codes though is incorrect, we should always throw error, on exceptions from rsync.
In you prefer the raise_on_nonzero there, I could achieve the same with:

```
        if reader.rc != 0:
```
Instead of the current
```
        if reader.rc == 11:
```

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Pull request merged**
