### PR TITLE
Change a confusing message for headless systems

### PR DESCRIPTION
**Pull request by poncovka**
Let's change the confusing message 'DISPLAY variable not set'.

Related: rhbz#1638791

### CODE REVIEW

**Comment by poncovka** [comment]
Ported from https://github.com/rhinstaller/anaconda/pull/1808.

**Comment by jkonecny12** [comment]
Do we really need this message translated? If not please remove the translation function.

**Comment by poncovka** [comment]
> Do we really need this message translated? If not please remove the translation function.

We translate most of the messages at this point of the installation. If we don't want them to be translated, we should change all of them.

**Comment by jkonecny12** [comment]
Maybe, on the other hand we are adding unnecessary work to translators. So if we can decide now, I would rather decide and change it before we add new work for people.

**Pull request merged**
