### PR TITLE
config the dnf-langpacks plugin

### PR DESCRIPTION
**Pull request by dashea**

### CODE REVIEW

**Comment by dashea** [comment]
It may also be worthwhile to add a kickstart test for this

**Comment by vpodzime** [comment]
Looks good to me other than the comment above. A test would be great, @KosiehBarter, could you have a look at this and try to come up with a test for this?

**Comment by KosiehBarter** [comment]
KS Test: Will do.

**Comment by KosiehBarter** [comment]
With applied patch (https://patch-diff.githubusercontent.com/raw/rhinstaller/anaconda/pull/222.patch) returns error, more in http://paste.fedoraproject.org/246056/73963121/.

Tested against Fedora 23 (anaconda 23.16-1).

**Comment by dashea** [comment]
> With applied patch (https://patch-diff.githubusercontent.com/raw/rhinstaller/anaconda/pull/222.patch) returns error, more in http://ur1.ca/n6bd8.
> 
> Tested against Fedora 23 (anaconda 23.16-1).

That's a separate issue not related to this patch. And since it's related to threads, sometimes it happens and sometimes it doesn't.

**Comment by dashea** [comment]
Modified and pushed.

**Pull request closed without merging**
