### PR TITLE
Support bond device activated in initramfs from kickstart

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1940919

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by jkonecny12** [comment]
What about having a test for this?

**Comment by rvykydal** [comment]
@jkonecny12 - thanks for reminding me, I updated the unit tests

**Review by poncovka — APPROVED** [review]

**Pull request merged**
