### PR TITLE
Fix inst.proxy configuration in dracut to allow stage2 image download

### PR DESCRIPTION
**Pull request by jkonecny12**
Fix proxy is not used when downloading stage2 image.

This fix is handling two cases:

* kickstart has `url --proxy` which should be used also to download stage2 image with proxy
* `inst.proxy` is not used by dracut to download stuff (like stage2 image)
* do not request `inst.` prefix for `proxy` kernel boot argument because that is valid option for Dracut (and maybe others) 

*Resolves: rhbz#2177219*

Backport of: https://github.com/rhinstaller/anaconda/pull/4794

### CODE REVIEW

**Comment by jkonecny12** [comment]
**REBASED** to get rid of the annoying red test (should be resolved but won't be executed here again).

**Comment by VladimirSlavik** [comment]
Is there anything preventing us from merging this? I don't think so?

**Comment by jkonecny12** [comment]
Missing KS test. Otherwise it's ready.

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Pull request merged**
