### PR TITLE
network: document edge case of resolv.conf missing for %post scripts …

### PR DESCRIPTION
**Pull request by rvykydal**
…(#2101527)

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Review by poncovka — APPROVED** [review]
I would include the workaround into the text, it is just a few lines. Otherwise, it looks great!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]
Thank you!

**Pull request merged**
