### PR TITLE
Cancel planned manual update of system time on turning ntp on

### PR DESCRIPTION
**Pull request by rvykydal**
The PR is based on https://github.com/rhinstaller/anaconda/pull/3590
by bitcoffee.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks!

**Review by poncovka — APPROVED** [review]
Thanks!

**Review by jkonecny12 — CHANGES_REQUESTED** [review]
Please change the commit message. We should avoid links to GitHub. You know in the future the GitHub may not exists and the information will be lost.

Could you pleas copy the message in the commit directly?

**Comment by rvykydal** [comment]
> Please change the commit message. We should avoid links to GitHub. You know in the future the GitHub may not exists and the information will be lost.
> 
> Could you pleas copy the message in the commit directly?

Doesn't make much sense to me, but I'll try.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me now. Thanks!

**Pull request merged**
