### PR TITLE
Change screensaver handling to dasbus, drop safe_dbus

### PR DESCRIPTION
**Pull request by VladimirSlavik**
We need to keep the D-Bus session up and live all the time, or the inhibition stops. So we need to keep the proxy object somehow.

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Comment by VladimirSlavik** [comment]
I set out to rewrite this to follow the form we use in the modules. Turns out that's not a good idea.

I can have a custom bus with custom `_get_connection` that sets the euid, that's fine. So I have a `MessageBus` and `DBusServiceIdentifier`. But all calls on the bus must happen with the right euid again. Overriding `__getitem__` in an `InterfaceProxy` won't work because that is only the getting, not calling. Writing a custom class just to set euid which I will do anyway does not seem like it helps anything... So in the end only the identifier helps, because it deduplicates the DBus strings.

**Review by poncovka — APPROVED** [review]
Looks good to me!

**Comment by poncovka** [comment]
> I set out to rewrite this to follow the form we use in the modules. Turns out that's not a feasible idea.
> 
> I can have a custom bus with custom `_get_connection` that sets the euid, that's fine. So I have a `MessageBus` and `DBusServiceIdentifier`. But all calls on the bus must happen with the right euid again. Overriding `__getitem__` in an `InterfaceProxy` won't work because that is only the getting, not calling. Writing a custom class just to set euid which I will do anyway does not seem like it helps anything... So in the end only the identifier helps, because it deduplicates the DBus strings.

Thanks for looking into that :-)

**Comment by VladimirSlavik** [comment]
Yup, it's a shame that did not work :(

**Pull request merged**
