### PR TITLE
infra: Pylint should use the GTK 3 library to analyze our code

### PR DESCRIPTION
**Pull request by poncovka**
Ported from https://github.com/rhinstaller/anaconda/pull/4572 and https://github.com/rhinstaller/anaconda/pull/4568.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thanks!

**Comment by VladimirSlavik** [comment]
@TomasTomecek would you happen to know why the testing farm gives 37 instead of 38? The config looks like this:

```
  - job: propose_downstream
    trigger: release
    dist_git_branches: f38

  - job: tests
    trigger: pull_request
    targets:
      - fedora-latest

  - job: copr_build
    trigger: commit
    targets:
      - fedora-latest
    branch: fedora-38
    owner: "@rhinstaller"
    project: Anaconda-devel
    (...)

```

**Comment by TomasTomecek** [comment]
@VladimirSlavik fedora-latest implies the latest stable release: it will turn into F38 once it will be officially released. I think we don't have an alias for the "latest Fedora release that is not rawhide".

**Comment by poncovka** [comment]
> fedora-latest implies the latest stable release: it will turn into F38 once it will be officially released. I think we don't have an alias for the "latest Fedora release that is not rawhide".

@TomasTomecek, I suggest to change [your documentation](https://packit.dev/docs/configuration/#aliases) in that case. It says:

* `fedora-latest` — the last versioned Fedora (not a Rawhide), regardless if it’s released or still under development.
* `fedora-latest-stable` — the latest released Fedora version (e.g. fedora-35).

Or maybe I am looking at the wrong place.

**Comment by TomasTomecek** [comment]
> > fedora-latest implies the latest stable release: it will turn into F38 once it will be officially released. I think we don't have an alias for the "latest Fedora release that is not rawhide".
> 
> @TomasTomecek, I suggest to change [your documentation](https://packit.dev/docs/configuration/#aliases) in that case. It says:
> 
> * `fedora-latest` — the last versioned Fedora (not a Rawhide), regardless if it’s released or still under development.
> * `fedora-latest-stable` — the latest released Fedora version (e.g. fedora-35).
> 
> Or maybe I am looking at the wrong place.

oh, I replied without consulting our documentation. And I remember it wrong, let me open an issue then, because this is clearly a bug based on the docs.

**Pull request merged**
