### PR TITLE
infra: switch from using templating to using reusable matrix

### PR DESCRIPTION
**Pull request by KKoukiou**
This replaces the templating logic to matrix for all workflow iterating over supported branches variable.

This will enable us to get rid of the custom jinja rendering and the workflow duplication with the templates.

### CODE REVIEW

**Comment by jkonecny12** [comment]
Is there a reason why to create a new `.supported_branches.json` as extraction from the current configuration file?

**Comment by KKoukiou** [comment]
> Is there a reason why to create a new `.supported_branches.json` as extraction from the current configuration file?

I dont think workflow files can parse yml? I saw only example with json in the examples in the docs.

**Comment by jkonecny12** [comment]
BTW this work here is great prerequisite for better pot files update on l10n branch.

**Comment by jkonecny12** [comment]
We agreed with @KKoukiou to avoid unnecessary changes and just finish what we have now. We can do more improvements later.

**Pull request closed without merging**
