### PR TITLE
Initial DNF 3 compatibility fixes

### PR DESCRIPTION
**Pull request by AdamWill**
DNF 3 recently landed in Rawhide. With these changes, I can at least complete a default network install, and also do some package selection from the GUI, without anything crashing. The correct packages appear to get installed, and the installed system boots.

### CODE REVIEW

**Comment by M4rtinK** [comment]
jenkins, test this please

**Comment by M4rtinK** [comment]
@AdamWill One last thing - can you rebase this on top of modularization-devel ? Once that is done I can do an Anaconda build right away.

**Comment by AdamWill** [comment]
Done.

**Comment by AdamWill** [comment]
@sgallagher

**Pull request merged**
