### PR TITLE
ovirt: move /var/tmp and /var/crash to own partition

### PR DESCRIPTION
**Pull request by poncovka**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2057475
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

Resolves: rhbz#2057475
**Ported from:** https://github.com/rhinstaller/anaconda/pull/3888

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by VladimirSlavik** [comment]
We won't be getting kickstart tests here, because "Branch rhel-8.6 is not supported by kickstart tests yet!" - see https://github.com/rhinstaller/anaconda/runs/5466138667?check_suite_focus=true

**Comment by rvykydal** [comment]
> We won't be getting kickstart tests here, because "Branch rhel-8.6 is not supported by kickstart tests yet!" - see https://github.com/rhinstaller/anaconda/runs/5466138667?check_suite_focus=true

Yes, the tests passed on rhel-8 branch so believe we should be ok for this PR.

**Review by jkonecny12 — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks! :)

**Pull request merged**
