### PR TITLE
network: fix obtaining of s390 options of a wired connection

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1850199

### CODE REVIEW

**Comment by rvykydal** [comment]
I need to update the tests.

**Comment by jstodola** [comment]
Tested together with a fix from https://github.com/rhinstaller/anaconda/pull/2680 - the installation was successful.
Thank you, Radek.

**Comment by rvykydal** [comment]
Tests updated

**Comment by rvykydal** [comment]
PR with port to master: https://github.com/rhinstaller/anaconda/pull/2713

**Comment by rvykydal** [comment]
Port to master merged.

**Pull request merged**
