### PR TITLE
Add table of branches to README

### PR DESCRIPTION
**Pull request by jkonecny12**
This table can be used by contributors to pick correct branch where they want to make their contribution.

### CODE REVIEW

**Comment by jkonecny12** [comment]
I think we want to make this table visible on the first look in the repository. Because we're getting questions about where to contribute from people who knows the contribution guidelines.

Other than that, yes, we can replace the order even though that this seems more logical to me. You are looking for a branch based on where you want to contribute not opposite.

**Comment by poncovka** [comment]
I guess that the problem is that the style of our README doesn't really work anymore. It will always look weird to add some reasonable content to all these shouts and one-liner sentences.

About the order, it is about the length of the cells. The branch names will have very similar length, but the descriptions can be very different. With the current order, it might be harder to read the table. But that's up to you.

**Comment by jkonecny12** [comment]
True, OK. I'll change that.

**Comment by jkonecny12** [comment]
**UPDATED:**
* Moved from readme to contributions document

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Comment by jkonecny12** [comment]
**UPDATED:**
* Removed RHEL-7 because Anaconda can't update that now.
* Switch `rhel-8` to `rhel-X` to make this more general.

**Review by poncovka — APPROVED** [review]

**Pull request merged**
