### PR TITLE
Use simpleline with glib

### PR DESCRIPTION
**Pull request by jkonecny12**
This PR https://github.com/rhinstaller/python-simpleline/pull/35 have to be merged before!

### CODE REVIEW

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by M4rtinK** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Pull request merged**
