### PR TITLE
network: fix crash on AP configuration of wireless device

### PR DESCRIPTION
**Pull request by rvykydal**
This is a fixup of incomplete fix in
commit b40af3de6b93c7d26f605807247b3cc5c2426bf2

Resolves: rhbz#1847681

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]
LGTM!
Just wonder if we shouldn't have some kind of tests for this?

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Comment by jkonecny12** [comment]
Please rebase this PR otherwise these tests are testing ``rhel-8`` branch instead of this PR.

**Comment by rvykydal** [comment]
Obsoleted by https://github.com/rhinstaller/anaconda/pull/2977

**Pull request closed without merging**
