### PR TITLE
Don't block the start of the Network module by the hostname service

### PR DESCRIPTION
**Pull request by poncovka**
When the Network module is started, it shouldn't wait for the hostname service.
It should connect to the hostname service from the loop after it is initialized
and published. Otherwise, the activation of services might time out.

Related: rhbz#1919380

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
