### PR TITLE
Remove the locale list from zanata.xml

### PR DESCRIPTION
**Pull request by dashea**
Zanata now manages this information on the server side and no longer
includes it in the exported config file. Also, if the information on the
server gets out of sync with the information in zanata.xml it causes a
really confusing 403 error.

### CODE REVIEW

**Comment by dashea** [comment]
Added a patch to avoid an out-of-sync LINGUAS by getting out of the LINGUAS business.

And for what it's worth the test failure is because of the weak deps thing I pushed earlier, since that version of pykickstart hasn't hit dl.fp.o yet.

**Comment by jkonecny12** [comment]
Looks good to me.

**Comment by vpodzime** [comment]
Looks good to me. I hope you don't mind if I do the same in libbytesize. :)

**Comment by dashea** [comment]
No good, need to take a different approach with LINGUAS.

**Pull request closed without merging**
