### PR TITLE
Remove unused variable from makeupdates script

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]

**Review by vojtechtrefny — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well.

**Review by jkonecny12 — APPROVED** [review]

**Comment by martinpitt** [comment]
FTR, cockpit CI tests were broken since yesterday, sorry about that. Fixed in https://github.com/cockpit-project/cockpituous/pull/558 and I retried all failed PRs. So should be good now.

**Comment by KKoukiou** [comment]
The rpm-build and testing-farm failures are because of the packit recent breakage.

**Pull request merged**
