### PR TITLE
Change fedora-welcome to rhel-welcome

### PR DESCRIPTION
**Pull request by rvykydal**
Related: rhbz#1650295

Port of commit a419276f9c4a4081cb21d95dd71f4eb400948e35

### CODE REVIEW

**Comment by M4rtinK** [comment]
Though for longer term I wonder if we might want to just have three sets of the desktop and javascript files (Fedore, RHEL, CentOS), as they hardly ever change & we would be ready for any future rebases, major releases & CentOS unbranding.

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
> Though for longer term I wonder if we might want to just have three sets of the desktop and javascript files (Fedore, RHEL, CentOS), as they hardly ever change & we would be ready for any future rebases, major releases & CentOS unbranding.

Ideally if you can switch them by configuration. Not sure if that can be implemented. That way even others which are not part of the code-base could easily add their own and switch by the configuration file.

**Pull request merged**
