### PR TITLE
Remove biospart support

### PR DESCRIPTION
**Pull request by jkonecny12**
Remove ``biospart`` support from KS and HDD installation source. These were not implemented and I would be surprised if we would ever add the support.

Blocked by https://github.com/pykickstart/pykickstart/pull/333.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well.

**Review by poncovka — APPROVED** [review]
Looks good to me.

**Comment by jkonecny12** [comment]
**UPDATED:**
* Increase required pykickstart version
* Use new pykickstart HardDrive command

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
