### PR TITLE
webui: Show partition size on review page

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Comment by marusak** [comment]
I have seen couple of times build error:
```
make[7]: Entering directory '/work/bots/make-checkout-workdir/ui/webui'
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
fatal: expected 'acknowledgments'
```

Any idea what is this about? Last time force push worked.

**Review by KKoukiou — COMMENTED** [review]
Needs one pixel test update!

**Comment by KKoukiou** [comment]
> I have seen couple of times build error:
> 
> ```
> make[7]: Entering directory '/work/bots/make-checkout-workdir/ui/webui'
> error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
> fatal: expected 'acknowledgments'
> ```
> 
> Any idea what is this about? Last time force push worked.

i don't know - this appeared first time on friday, saw this in another PR.

**Review by KKoukiou — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks! :)

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Pull request merged**
