### PR TITLE
Use the DNF manager instead of the DNF base

### PR DESCRIPTION
**Pull request by poncovka**
Extend the DNF manager, so it can be used instead of the DNF base.

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by jkonecny12 — APPROVED** [review]
Looks really great! Thanks a lot for creating the DNF Manager the code is much cleaner!

**Comment by poncovka** [comment]
Rebased.

**Pull request merged**
