### PR TITLE
webui: Upgrade to react 18 and enable the new concurrent renderer

### PR DESCRIPTION
**Pull request by KKoukiou**
docs: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

(Please let @M4rtinK review too.)

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

BTW, we had some issues with animations using a lot of CPU, mainly on GTK3 WebKit running the local web view in VMs (but possibly elsewhere, we are still looking into it). Any chance the multi-threaded rendering could possibly help with this ?

**Comment by KKoukiou** [comment]
> Looks good to me, thanks! :)
> 
> BTW, we had some issues with animations using a lot of CPU, mainly on GTK3 WebKit running the local web view in VMs (but possibly elsewhere, we are still looking into it). Any chance the multi-threaded rendering could possibly help with this ?

Not really. This is more of help for components which need to process a lot of data before being ready to render.

**Pull request merged**
