### PR TITLE
Update branching settings for RHEL 8.6 (#infra)

### PR DESCRIPTION
**Pull request by jkonecny12**
This includes repositories and worflows.

https://github.com/rhinstaller/anaconda-l10n/pull/24

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Comment by jkonecny12** [comment]
@jstodola asking for review here, thanks!

**Review by jstodola — APPROVED** [review]

**Pull request merged**
