### PR TITLE
Fix infrastructure check

### PR DESCRIPTION
**Pull request by jkonecny12**
Add missing dotfiles files.
Rebase the code before running the checks.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by jkonecny12** [comment]
Still broken... something doesn't play nice here.

**Comment by jkonecny12** [comment]
Yep, rebase in the workflow should help to solve the issue. Rebasing of this PR manually seems to worked.

**Review by VladimirSlavik — APPROVED** [review]

**Pull request merged**
