### PR TITLE
WIP: webui: fix obsolete button label

### PR DESCRIPTION
**Pull request by peberanek**
Default WebUI test (ui/webui/test/integration/default.py) fails because of an obsolete button label.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Thank you! A few notes:
- Please don't include merge commits in the PR.
- You will have to update the pixel test references - https://github.com/rhinstaller/anaconda/blob/master/ui/webui/test/README.rst#how-to-fix-failed-pixel-tests

**Comment by rvykydal** [comment]
Thank you for the heads-up. I'll try to update the integration tests to reflect the change https://github.com/rhinstaller/anaconda/pull/4767 which is intentional.

**Comment by peberanek** [comment]
> @peberanek where are the tests failing (what image are you testing) ? I think the problem is that the initegration tests are using common test library which was updated for the #4767 change which is not in the tested artifact (yet).

@rvykydal The test was a part of a new Permian workflow for WebUI testing - the test script was a copy of `ui/webui/test/integration/default.py`. Once I changed all instances of string `"Erase data and install"` to `"Erase disks and install"` it passed.
@velezd Can you, please, provide info about what image are we testing or other context that might be important? Thanks.

**Comment by rvykydal** [comment]
Yes, our daily integration tests fail as well (because the tested image has not been updated yet): https://github.com/rhinstaller/anaconda/actions/runs/5062910016

**Pull request closed without merging**
