### PR TITLE
Rhel9 covscan fixes (1)

### PR DESCRIPTION
**Pull request by VladimirSlavik**
These are fixes for the errors marked as `[important]`.

Related to #3277, fixes some of [rhbz#1938677](https://bugzilla.redhat.com/show_bug.cgi?id=1938677).

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks! :)

**Review by poncovka — APPROVED** [review]

**Comment by VladimirSlavik** [comment]
Blocked because I must manually validate that this actually works. The changes in dracut are related to functionality that has no kickstart tests, AFAICT.

**Comment by VladimirSlavik** [comment]
Verified, the dracut changes work as intended. I tested only one of them (kickstart on hd) since they are all identical.

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by poncovka — APPROVED** [review]

**Pull request merged**
