### PR TITLE
Extend the DBus API of the Payloads service

### PR DESCRIPTION
**Pull request by poncovka**
Move some methods from the payload modules to the main service.
Drop the support for the pre-installation tasks.

Some of the installation tasks don't depend on the type of the payload
module, so include them by default on the service-level.

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Looks good to me.
I've moved from blocklist to denylist in:
https://github.com/rhinstaller/anaconda/pull/3202
https://github.com/rhinstaller/anaconda/pull/3203
(it seems kernel is going to use denylist).
So maybe adapt this PR to be consistent with the above PRs (use denylist) or use the blacklist and I'll update my (conflicting) PRs after this one is merged ?
Or I can open new PR for blocklist -> denylist but that may get a bit confusing ...

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by poncovka** [comment]
Rebased and tested.

**Pull request merged**
