### PR TITLE
Disable hub and spoke user account for Fedora Design Suite

### PR DESCRIPTION
**Pull request by luyatshimbalanga**
This commit disables hub and spoke user account in favour of Fedora Workstation style approach. This pull requests also disable the pull apps that accidentally triggered the merge.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
The points in https://github.com/rhinstaller/anaconda/pull/4550#issuecomment-1427854257 are still valid:

> This will need extending tests. See eg. https://github.com/rhinstaller/anaconda/pull/3680/files for where to look. The tests might be slightly different these days, but once you know where to look, it's just copypasta and changing the strings to match your new config.

Once we are finished iterating on this PR, it would be good to squash the commits into one. I could do that for you if you wish. But let's worry about that later!

**Comment by luyatshimbalanga** [comment]
> The points in [#4550 (comment)](https://github.com/rhinstaller/anaconda/pull/4550#issuecomment-1427854257) are still valid:
> 
> > This will need extending tests. See eg. https://github.com/rhinstaller/anaconda/pull/3680/files for where to look. The tests might be slightly different these days, but once you know where to look, it's just copypasta and changing the strings to match your new config.
> 
> Once we are finished iterating on this PR, it would be good to squash the commits into one. I could do that for you if you wish. But let's worry about that later!

Please do. Thanks Vladimir!

**Comment by VladimirSlavik** [comment]
I thought adding the test would be fine. But you tested me! The file was in the wrong directory: D

**Comment by luyatshimbalanga** [comment]
> I thought adding the test would be fine. But you tested me! The file was in the wrong directory: D

Will it be possible to add on F38 branch as well via cherry pick?

**Comment by VladimirSlavik** [comment]
Yes, I think so.

**Review by VladimirSlavik — APPROVED** [review]

**Pull request merged**
