### PR TITLE
Wait for all background threads to finish before filling installation…

### PR DESCRIPTION
**Pull request by M4rtinK**
… task queue

Otherwise installation tasks, such as the installation task that
transfers subscription tokens, will be scheduled based on stale data
(eq. system is not subscribed as the subscription thread is still
running).

By waiting for all background processing threads to finish before
assembling the installation task queue, we will make sure all tasks are
correctly scheduled based on up to data data - eq. system was
successfully registered, so the token transfer task needs to transfer
the relevant subscription tokens to the target system.

(cherry picked from commit 734befd4c4c5ce5e8bc73732455d87b672598f3c)

Related: rhbz#1824422
Related: rhbz#2017428

### CODE REVIEW

**Comment by M4rtinK** [comment]
This is the upstream port of RHEL 8 PR #3704.

**Review by poncovka — APPROVED** [review]
Thanks!

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Pull request merged**
