### PR TITLE
Fix setting of ipv6 addr gen mode

### PR DESCRIPTION
**Pull request by rvykydal**
Port of upstream PRs https://github.com/rhinstaller/anaconda/pull/2846 and https://github.com/rhinstaller/anaconda/pull/2845

### CODE REVIEW

**Comment by rvykydal** [comment]
Kickstart tests PR: https://github.com/rhinstaller/kickstart-tests/pull/496

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Review by jkonecny12 — APPROVED** [review]
Looks good to me, although I would like to see tests for this.

**Comment by rvykydal** [comment]
> Looks good to me, although I would like to see tests for this.



Looks good to me, although I would like to see tests for this.

**Comment by jkonecny12** [comment]
Thanks, I was more thinking about having some unit-tests but this is also solution :).

**Pull request merged**
