### PR TITLE
webui: tests: add info on how to run these in a toolbox

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by VladimirSlavik — COMMENTED** [review]
LGTM, please add `#docs` in commit message though.

**Review by jkonecny12 — APPROVED** [review]
Looks great to me. Thanks!

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks! :)

**Pull request merged**
