### PR TITLE
backported gettext updates from master

### PR DESCRIPTION
**Pull request by atodorov**
Hi guys,
I'm not sure about removal of this line:
potcheckfile = checkfile + ".h"

but as far as I can tell it should be the correct thing to do. There are both .glade and .glade.h files and I think the .h files need to go. Everything else appears to be OK. 

Please comment.

### CODE REVIEW

**Comment by atodorov** [comment]
Hi David,
I think it looks fine now.

**Comment by dashea** [comment]
Yeah, that looks fine. Could you squash the two commits and do a push --force? It looks kind of silly to change a line and then just change it back it the next commit, and this is still at the point where history can be rewritten :-)

**Comment by atodorov** [comment]
Here you go.

**Comment by clumens** [comment]
This was auto-closed by github when I rebased rhel7-branch.  Reopening so I can do something with it.

**Comment by clumens** [comment]
The first chunk is no longer necessary, but the second chunk is.  I'll send this out with a bunch of other test-related stuff.  Thanks.

**Pull request closed without merging**
