### PR TITLE
Add support for rootpw --allow-ssh

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#2033849
Port of https://github.com/rhinstaller/anaconda/pull/4154

### CODE REVIEW

**Comment by rvykydal** [comment]
Depends on https://github.com/pykickstart/pykickstart/pull/411

**Review by poncovka — APPROVED** [review]
Thanks!

**Review by VladimirSlavik — APPROVED** [review]

**Comment by rvykydal** [comment]
Waiting for pykickstart in nightly compose to re-run unit tests.

**Review by poncovka — APPROVED** [review]

**Pull request merged**
