### PR TITLE
webui: language information should be fetched also for live media

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Oh, so this fixes the case where on Live media the language list is not populated ? Nice! 

(With all the ongoing stuff, it sometimes hard for me to find which PR refers to which issue/effort due to lack of context.) 

Looks good to me code wise. :)

**Comment by KKoukiou** [comment]
> Oh, so this fixes the case where on Live media the language list is not populated ? Nice!
> 
> (With all the ongoing stuff, it sometimes hard for me to find which PR refers to which issue/effort due to lack of context.)
> 
> Looks good to me code wise. :)

On live media the language screen is hidden, but we need still to load the languages because of the review screen. Prevoysly the review screen would just crash on live media - because of the missing localization data.

**Comment by M4rtinK** [comment]
> On live media the language screen is hidden, but we need still to load the languages because of the review screen. Prevoysly the review screen would just crash on live media - because of the missing localization data.

Oh, right - thanks for the explanation! :)

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
