### PR TITLE
Fix up a quote escaping in release-periodically workflow.

### PR DESCRIPTION
**Pull request by rvykydal**
Follow up of commit 5aefbcce42fff50e67ed1c14f865712aced498bd

Failed here: https://github.com/rhinstaller/anaconda/actions/runs/3880330022/jobs/6618299104

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Thank you!

**Review by VladimirSlavik — APPROVED** [review]
Thank you! It's amazing how many quotes I can get wrong :-/

**Comment by rvykydal** [comment]
Quoting + escaping = fun forever

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks! :)

**Pull request merged**
