### PR TITLE
infra: improve logic for ignoring unrelated commits in the makebumpver 

### PR DESCRIPTION
**Pull request by KKoukiou**
So that we can soon enable the release workflow in RHEL as well.

### CODE REVIEW

**Comment by jkonecny12** [comment]
I was thinking about this too but I'm not sure that we want to miss translation updates in the release notes. This might be interesting for community to have.

**Comment by KKoukiou** [comment]
> I was thinking about this too but I'm not sure that we want to miss translation updates in the release notes. This might be interesting for community to have.

The problem with keeping this in is that the makebumpver now fails (if you dont use the Skip which adds all commits) on the missing RHEL tickets for translation commits.
So either we remove these from the changelog completely or we need RHEl tickets (which we dont :P)

Also since translation updates are automated and happen on weekly basis - each release has translation upadates. It's nothing special.

**Review by jkonecny12 — APPROVED** [review]
Good point. LGTM!

**Pull request merged**
