### PR TITLE
Move product.py to core

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Refactoring in advance of adding D-Bus API for this and such.

~~Not sure how far I will go with this yet, so no TODO list.~~ Let's take it piecewise. This is a good foundation, is still reasonably sized, and it does not makes sense to mix in the other changes that will have their own challenges.

~~Side note - the changes have potential to break initial setup due to touching the UI class constructor.~~ Disproved by kickstart tests below.

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Btw. I have a feeling that the OSCAP add-on is actually using this functionality.

**Comment by VladimirSlavik** [comment]
Waiting to coordinate with oscap folks. Presumably it would be better to wait with this until after branching.

**Review by M4rtinK — APPROVED** [review]
Looks good to me - much cleaner now, thanks! :)

**Comment by M4rtinK** [comment]
Just a small typo in one of the commit messages:

>  Replace all uses of product values via constants
> 
> This means, do not import anything from product to constants that **woudl** be
> then re-imported elsewhere from constants.

**Comment by VladimirSlavik** [comment]
OSCAP people say this is fine for rawhide, so I'd wait for when we do the branching, unless we absolutely require this for webui.

**Comment by VladimirSlavik** [comment]
Rebased to lastest master.

**Pull request merged**
