### PR TITLE
Fix ELN containers somewhat

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This fixes a large part of the ELN container builds.

Unfortunately, there are still missing `BuildRequires` so it can't be tested completely: `Error: Unable to find a match: libtimezonemap-devel >= 0.4.1-2`.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
@sgallagher do you think this would be correct? Or is the absence of `Everything` repo a bug?

**Comment by VladimirSlavik** [comment]
So, now it dies on missing `xisxwayland`, which is not even in the listings. Ow.

**Comment by VladimirSlavik** [comment]
Some more findings:
- The RPM build container is also missing `python3-polib` for the very first install step.
- Our repo file is entirely redundant now that Everything is retired.

**Comment by sgallagher** [comment]
> Used a debug repo as suggested above. The following packages are the only ones missing in ELN repos to successfully build the anaconda containers:
> 
> ```
> xisxwayland

This is missing because https://github.com/minimization/content-resolver-input/blob/master/configs/sst_installer-anaconda.yaml does not include `anaconda-live`, which is the only thing that pulls it in. Please update the content resolver input.


> python3-polib
> ```

What is this used for? In Fedora Rawhide I only see:
```
$ dnf --release rawhide repoquery --whatrequires python3-polib --enablerepo=*source --recursive
Last metadata expiration check: 0:01:35 ago on Wed 13 Jul 2022 11:58:49 AM EDT.
python-proteus-0:4.0.2-17.fc35.noarch
python3-ipatests-0:4.10.0-1.fc37.noarch
python3-pocketlint-0:0.23-1.fc37.noarch
python3-zanata-client-0:1.5.3-12.fc37.noarch
trytond-0:4.0.4-19.fc35.noarch
trytond-account-0:4.0.3-17.fc35.noarch
trytond-account-be-0:4.0.0-17.fc35.noarch
trytond-account-de-skr03-0:4.0.0-17.fc35.noarch
trytond-account-invoice-0:4.0.2-17.fc35.noarch
trytond-account-invoice-history-0:4.0.1-17.fc35.noarch
trytond-account-invoice-line-standalone-0:4.0.1-17.fc35.noarch
trytond-account-product-0:4.0.2-17.fc35.noarch
trytond-account-statement-0:4.0.2-17.fc35.noarch
trytond-account-stock-anglo-saxon-0:4.0.1-17.fc35.noarch
trytond-account-stock-continental-0:4.0.1-17.fc35.noarch
trytond-analytic-account-0:4.0.1-17.fc35.noarch
trytond-analytic-invoice-0:4.0.1-17.fc35.noarch
trytond-analytic-purchase-0:4.0.1-17.fc35.noarch
trytond-analytic-sale-0:4.0.1-17.fc35.noarch
trytond-company-0:4.0.3-17.fc35.noarch
trytond-company-work-time-0:4.0.1-17.fc35.noarch
trytond-country-0:4.0.1-17.fc35.noarch
trytond-currency-0:4.0.1-17.fc35.noarch
trytond-dashboard-0:4.0.1-17.fc35.noarch
trytond-google-maps-0:4.0.2-17.fc35.noarch
trytond-ldap-authentication-0:4.0.1-17.fc35.noarch
trytond-mysql-0:4.0.4-19.fc35.noarch
trytond-openoffice-0:4.0.4-19.fc35.noarch
trytond-party-0:4.0.2-17.fc35.noarch
trytond-party-siret-0:4.0.0-17.fc35.noarch
trytond-pgsql-0:4.0.4-19.fc35.noarch
trytond-product-0:4.0.1-17.fc35.noarch
trytond-product-cost-fifo-0:4.0.1-17.fc35.noarch
trytond-product-cost-history-0:4.0.0-17.fc35.noarch
trytond-product-price-list-0:4.0.0-17.fc35.noarch
trytond-project-0:4.0.1-17.fc35.noarch
trytond-project-plan-0:4.0.1-17.fc35.noarch
trytond-project-revenue-0:4.0.1-17.fc35.noarch
trytond-purchase-0:4.0.3-17.fc35.noarch
trytond-purchase-invoice-line-standalone-0:4.0.0-17.fc35.noarch
trytond-sale-0:4.0.3-17.fc35.noarch
trytond-sale-opportunity-0:4.0.1-17.fc35.noarch
trytond-sale-price-list-0:4.0.0-17.fc35.noarch
trytond-sqlite-0:4.0.4-19.fc35.noarch
trytond-stock-0:4.0.3-17.fc35.noarch
trytond-stock-forecast-0:4.0.0-17.fc35.noarch
trytond-stock-inventory-location-0:4.0.1-17.fc35.noarch
trytond-stock-location-sequence-0:4.0.1-17.fc35.noarch
trytond-stock-product-location-0:4.0.0-17.fc35.noarch
trytond-stock-supply-0:4.0.1-17.fc35.noarch
trytond-stock-supply-day-0:4.0.0-17.fc35.noarch
trytond-timesheet-0:4.0.1-17.fc35.noarch
```

None of that looks terribly relevant.

**Comment by VladimirSlavik** [comment]
Thank you, this is all very helpful.

Some context - Our unit tests require containers, so we build these. We initially ran unit tests on ELN too, but that kept failing and was very confusing. One had to learn what works this week and read the test results accordingly. So, we dropped ELN from the tests on PRs and kept just the container builds, which do run the tests too to verify the result. But now that just keeps failing too, which beings us to this very PR.

So, as I understand it, to fix this by not modifying our side, we'd need to
- Declare we want the `-live` package available in ELN too. I suppose that turns it into a question "what is the cost of having the package in ELN vs. the benefit of enabling our container builds".
- Declare we want pocketlint, which is something we use only in unit tests - ditto.

As I see it, this is a clash inherent in the "minimization" vs. "upstream testing".

**Comment by sgallagher** [comment]
If anaconda-live isn't desired in ELN proper, then the correct solution here would be to add it to ELN-Extras, which is essentially the preview for EPEL 10.

**Comment by VladimirSlavik** [comment]
After team discussion, we decided to hack the rest - polib is in pip, and xisx... is optional for the actual running code.

I will try do that in further commits to this.

**Comment by VladimirSlavik** [comment]
Hacked as per above. Results:
- Unit test container runs and everything, the missing upstream release of dill fails the tests same as rawhide which is expected = mostly success.
- RPM test container builds. The actual test then tries to install all anaconda packages, among which is the -live one, which does require the xisx-thing, so it fails. The error itself is more verbose though: 
```
Error: 
 Problem 1: conflicting requests
  - nothing provides dracut-live needed by anaconda-dracut-37.10-1.el120.x86_64
 Problem 2: conflicting requests
  - nothing provides udisks2-iscsi needed by anaconda-install-env-deps-37.10-1.el120.x86_64
  - nothing provides isomd5sum >= 1.0.10 needed by anaconda-install-env-deps-37.10-1.el120.x86_64
 Problem 3: conflicting requests
  - nothing provides brltty needed by anaconda-install-img-deps-37.10-1.el120.x86_64
  - nothing provides gnome-kiosk needed by anaconda-install-img-deps-37.10-1.el120.x86_64
  - nothing provides xorg-x11-drivers needed by anaconda-install-img-deps-37.10-1.el120.x86_64
  - nothing provides xrandr needed by anaconda-install-img-deps-37.10-1.el120.x86_64
  - nothing provides zram-generator needed by anaconda-install-img-deps-37.10-1.el120.x86_64
 Problem 4: conflicting requests
  - nothing provides xisxwayland needed by anaconda-live-37.10-1.el120.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
make: *** [Makefile.am:294: container-rpm-test] Error 1
```

This, at least, is somewhat useful, even if a failure of the main goal, because it's what the tests say is broken.

I believe the practical outcome is that ELN (who?) should consider if adding `anaconda-img-deps` to the content resolver is a good idea or not. If ELN is supposed to be self-hosting, then certainly, if not, it's probably easier for all of us to pretend ELN is fine, and stop trying to have the containers at all costs.

**Review by poncovka — APPROVED** [review]
Thanks!

**Comment by sgallagher** [comment]
> I believe the practical outcome is that ELN (who?) should consider if adding `anaconda-img-deps` to the content resolver is a good idea or not. If ELN is supposed to be self-hosting, then certainly, if not, it's probably easier for all of us to pretend ELN is fine, and stop trying to have the containers at all costs.

ELN contains only packages that are required for RHEL 10. However, ELN-Extras exists as a preview of what will become EPEL 10 and is where you should put supporting packages that don't belong in RHEL proper.

**Comment by VladimirSlavik** [comment]
I added https://github.com/minimization/content-resolver-input/pull/723 to get the additional dependencies.

Meanwhile nodejs is broken in ELN...

**Comment by sgallagher** [comment]
> Meanwhile nodejs is broken in ELN...

Can you be more specific? (And preferably open a detailed ticket at https://github.com/fedora-eln/eln/issues/) ?

**Comment by VladimirSlavik** [comment]
For completeness - the node problems were actually rawhide fixes that weren't conditional. This should be fixed with the last changes pushed.

**Comment by VladimirSlavik** [comment]
The last push worked for me, so if tests turn out ok, we could have this working again...

**Comment by VladimirSlavik** [comment]
This indeed fixes building the containers, but not the whole job, just the build. The subsequent tests fail for ELN, because pylint is broken there, probably same as rawhide, and the `anaconda-live` subpackage is installed even if its dependencies are missing.

https://github.com/VladimirSlavik/anaconda/runs/7649885885?check_suite_focus=true

**Comment by poncovka** [comment]
@VladimirSlavik shouldn't the `anaconda-live` subpackage be excluded from our spec file on RHEL and ELN?

**Comment by VladimirSlavik** [comment]
There isn't anything special in the spec file, so it is built and tested. The exclusion is probably just that nobody puts it into a repo.

**Review by poncovka — APPROVED** [review]
Thank you!

**Comment by VladimirSlavik** [comment]
I think that the rest of the issues can be fixed later or separately, this seems adequate to move us in the right direction.

**Pull request merged**
