### PR TITLE
Remove --ignore-broken test

### PR DESCRIPTION
**Pull request by jkonecny12**
This has to be backported to rhel-9.0 branch.

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Thanks! I can handle the port to upstream and make the test skippable for RHEL.

**Review by jstodola — APPROVED** [review]
We don't ship this file in anaconda srpm. (so I approve)

**Review by rvykydal — APPROVED** [review]
Thank you

**Review by VladimirSlavik — APPROVED** [review]

**Pull request merged**
