### PR TITLE
Port GUI kernel switcher for ARM 64k

### PR DESCRIPTION
**Pull request by OndrejZobal**
Port https://github.com/rhinstaller/anaconda/pull/4689 to upstream.

Adds a combo box allowing user to select kernel-64k in the software selection spoke

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. Thanks!

**Comment by OndrejZobal** [comment]
I am sorry there were some issues with the TUI port and the test were missing. In my latest force push I have replaced is_arm with is_aarch64. It should all be good now.

**Review by jkonecny12 — APPROVED** [review]
Thanks for spotting that and fixing.

**Comment by OndrejZobal** [comment]
Oh, what made those kickstart tests sad?

**Comment by jkonecny12** [comment]
I'm not able to test this reasonably on Fedora because the required kernel is not available there. However, kickstart tests are successful and we have a unit tests.

**Comment by AdamWill** [comment]
I think this broke composes. `match_available_packages` is a method of the anaconda `DNFManager` class, but this seems to try to use it on an instance of the `DNFPayload` class, causing this crash:

aarch64crash

this caused https://pagure.io/releng/failed-composes/issue/5212 .

**Comment by AdamWill** [comment]
Reverted downstream, we have time to consider a proper fix upstream. Please don't cut a new release and build it in Fedora without fixing this, though.

**Comment by jkonecny12** [comment]
@VladimirSlavik please don't do a new release before we have revert or fix.

**Comment by jkonecny12** [comment]
The issue is that the original RHEL-9 code don't have payload as Anaconda module but master have. So we need to use module for this.

**Comment by jkonecny12** [comment]
@AdamWill I have a revert for now: https://github.com/rhinstaller/anaconda/pull/4958
We don't have time now for a proper fix.

I wonder why this wasn't caught by our kickstart tests...

**Comment by VladimirSlavik** [comment]
+1 for dismay at the kickstart test success.

**Comment by AdamWill** [comment]
well, for a start, this will only happen on aarch64. also, the affected code is in the UI stuff, so if you're doing unattended kickstart installs without a display attached, maybe the UI code just doesn't trigger?

**Comment by AdamWill** [comment]
btw, if you're wondering why openQA update tests didn't catch it - we don't run the update tests on aarch64 because I don't have enough aarch64 worker capacity :(

**Comment by VladimirSlavik** [comment]
> maybe the UI code just doesn't trigger

Sounds like the root cause.

**Pull request merged**
