### PR TITLE
Update the bootloader configuration after live installation

### PR DESCRIPTION
**Pull request by martinezjavier**
The GRUB configuration was changed to not store the kernel cmdline as a
variable in the grubenv file anymore, but instead in the BLS snippets.

But this change broke the live installations because the kernel-install
grub2 plugin now takes the kernel cmdline from /proc/cmdline. That means
the BLS snippets will have the cmdline used to boot the live install and
not the one needed to boot the installed rootfs.

To make sure that the BLS files have the expected cmdline, call to the
grub2-mkconfig tool after all the kernel have been installed.

Resolves: rhbz#1836020

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>

### CODE REVIEW

**Comment by poncovka** [comment]
Jenkins, test this please.

**Comment by martinezjavier** [comment]
@jkonecny12 thanks for the review, I've done the suggested changes. Now `pylint` doesn't complain anymore.

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by AdamWill** [comment]
using `execInSysroot` should automatically log the command the result, shouldn't it?

**Comment by poncovka** [comment]
@AdamWill, yes, it should be in `program.log`.

**Comment by VladimirSlavik** [comment]
Yes, it does. However my suggestion was more about following the pattern in the method - other "sections" of code there always log what is about to happen.

**Pull request merged**
