### PR TITLE
Disable anaconda-core's requirement on subscription-manager on CentOS

### PR DESCRIPTION
**Pull request by carlwgeorge**
Resolves: rhbz#1984958

### CODE REVIEW

**Comment by jkonecny12** [comment]
Port to master will be done from https://github.com/rhinstaller/anaconda/pull/3535.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. Thanks!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well.

**Pull request merged**
