### PR TITLE
Don't offer encrypting for Atomic Host installclass (#1267905)

### PR DESCRIPTION
**Pull request by rvykydal**
Atomic Host does not include cryptsetup.

Resolves: rhbz#1267905

This is "work in progress" patch by Chris. To me it seems quite complete (ie ACK). I rebased it for top of rhel7-branch and tested with locally built RHELAH 7.3 installer. Also tested that it does not interfere with mainline installer (GUI and kickstart).

The only thing that came up to me is that we might rather want to make the "Encrypt" checkboxes insensitive instead of hiding them, but I don't have strong preference.

### CODE REVIEW

**Comment by jkonecny12** [comment]
As far as I understand, it looks good to me.

**Comment by jkonecny12** [comment]
There is a style guide check error:
```
Bad string filesystem found at pyanaconda/kickstart.py:298 pyanaconda/kickstart.py:1080 pyanaconda/kickstart.py:1401 pyanaconda/kickstart.py:1595. Try file system instead.
```

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by rvykydal** [comment]
Closing as cryptsetup will be added to 7.3 Atomic Host

**Pull request closed without merging**
