### PR TITLE
GUI fixes

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Resolves [rhbz#2025078](https://bugzilla.redhat.com/show_bug.cgi?id=2025078), [rhbz#2025076](https://bugzilla.redhat.com/show_bug.cgi?id=2025076), [rhbz#2025072](https://bugzilla.redhat.com/show_bug.cgi?id=2025072).

- Saving with new Glade wrecks diffs, sorry.
- No screenshots because the changes are too small.

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Thank you!

**Comment by VladimirSlavik** [comment]
This was so tiny, it does not need release notes. Perhaps the amount of bugs filed for these tiny issues inflates the perceived importance?

**Pull request merged**
