### PR TITLE
Do not crash on network --device link with wireless device

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#2051235

### CODE REVIEW

**Comment by rvykydal** [comment]
We need to create rhel-8.7 branch and an rebase the PR on it.

**Review by poncovka — APPROVED** [review]
Thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Review by VladimirSlavik — APPROVED** [review]
Thanks!

**Pull request merged**
