### PR TITLE
Log the environment of DBus modules

### PR DESCRIPTION
**Pull request by poncovka**
Write the environment variables of DBus modules to logs to simplify debugging.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thank you, this will be useful!

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Comment by M4rtinK** [comment]
I guess we don't store anything sensitive in the environment variables of the modules right now, but are we sure the environment start otherwise clean & don't get stuff from say user set shell variables/bashrc or similar ? 

Otherwise there would be a chance up with sensitive data being present in logs say when a user starts Anaconda as a process for installation into a directory/image, same thing for reusable build VMs.

**Comment by jkonecny12** [comment]
In that case, what about logging this only with the `inst.debug` flag?

**Pull request closed without merging**
