### PR TITLE
Add kickstart tests to test btrfs installation

### PR DESCRIPTION
**Pull request by vojtechtrefny**
First test: simple installation
Second test: installation over multiple devices with RAID

Signed-off-by: Vojtech Trefny <vtrefny@redhat.com>

### CODE REVIEW

**Comment by clumens** [comment]
I don't have time to do a proper review right now, but I did notice one thing that dlehman and I talked about the other day.  I don't think you want to start the filenames with "storage-", because it's just going to make file completion more obnoxious.  It's obvious that it's storage on the basis on it being a btrfs-related thing.

**Comment by vpodzime** [comment]
I agree with @clumens. If we want to mark tests as storage-related, we could put them in a subdirectory.

Other then that, I'm just not sure about the installation source ``url --url=ftp://mirror.utexas.edu/pub/fedora/linux/development/$releasever/$basearch/os/`` -- should rather be dl.fedoraproject.org, I think. The rest looks good to me.

**Comment by vojtechtrefny** [comment]
Updated version:
- new file name (without storage prefix)
- fixed mirror
- fixed path for RESULT file

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by vojtechtrefny** [comment]
Totally forgot to push this...

**Pull request closed without merging**
