### PR TITLE
prune some dead code

### PR DESCRIPTION
**Pull request by dashea**

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me for *master*. Otherwise we need to keep in mind addons that are advised to use our utility functions instead of writing their own.

**Comment by dashea** [comment]
Maybe leave mkdirChain but just implement it as a os.makedirs call?

**Comment by vpodzime** [comment]
> Maybe leave mkdirChain but just implement it as a os.makedirs call?

Sounds good to me.

**Comment by dashea** [comment]
Modified and pushed.

**Pull request closed without merging**
