### PR TITLE
Run restorecon in chroot when handling home dirs

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Running `restorecon` needs chroot to sysroot so as to have correct absolute paths. At the point when users are handled, payload has been already installed, so the SELinux policy is already present and we can just do it.

Related: [rhbz#2069305](https://bugzilla.redhat.com/show_bug.cgi?id=2069305) - to be ported for that, eventually. Note that some parts of this change require Python 3.9+, so this can't be ported 1:1 to RHEL 8 where the problem has been originally reported.

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Comment by VladimirSlavik** [comment]
Fixed 2/3 test fails, need to think more about the last one, I don't want to lose testing the real effects...

**Review by jkonecny12 — APPROVED** [review]
Looks great to me after the test fix.

**Comment by jkonecny12** [comment]
I wonder why is this not necessary on RHEL-9. I guess it wasn't easy to reproduce it there because it's harder to have bad relabeling?

@VladimirSlavik do you think we should backport this to 9 too?

**Comment by VladimirSlavik** [comment]
Why didn't we see this earlier? No idea. Maybe the label is not tested anywhere. Additionally, the file is reused if it exists, so if something creates it before we try to change it, it might have the right label. Finally, restorecon *does* run, just with a wrong path to the file, so there is no hard error.

Backport to RHEL-9? Maybe. The reported bug could be a problem. (The other call affects only reused /home on "pet" type machines, and I think such users are also the ones likely to turn off SELinux and not notice.)

**Comment by VladimirSlavik** [comment]
Can you please review the part with `def _filter_exec(*args, **kwargs):` ? That's the new part, and probably most controversial.

**Comment by VladimirSlavik** [comment]
I just realized I might need to alter this further. In previous PRs, using `restorecon` had to be an optional thing because it might not be installed with some payloads. The previous version of code ran restorecon from the inst.env., so we knew it exists.

**Comment by achilleas-k** [comment]
I added this info the bug already but I wanted to chime in here as well in case anything is still unclear.

> I wonder why is this not necessary on RHEL-9. I guess it wasn't easy to reproduce it there because it's harder to have bad relabeling?

Exactly, yes.  The edge-case that lead me to discover this was that `useradd` had a bug where it wouldn't apply the correct labels to a home directory when the home dir parameter had a trailing slash.  In RHEL 9.0 this is fixed, so Anaconda's `restorecon` isn't necessary in the general case, but probably still a good fallback for any other edge cases where a home or .ssh directory might not be labelled correctly on creation.

**Comment by VladimirSlavik** [comment]
@achilleas-k Now I'm actually curious - do you know if useradd is *expected* to set the contexts? Because if so, we should drop the restorecon instead.

**Comment by achilleas-k** [comment]
> @achilleas-k Now I'm actually curious - do you know if useradd is _expected_ to set the contexts? Because if so, we should drop the restorecon instead.

https://github.com/shadow-maint/shadow/blob/9cdb5251b6c30487a7d935a1a7827f493249479d/src/useradd.c#L2225-L2230
The `create_home()` function in `useradd` sets the file contexts here.

You can observer the bug I mentioned with the trailing slash pretty easily by running the following in RHEL 8.6 (or older):

```bash
#!/usr/bin/env bash

set -e

sudo useradd -m -d /home/slash/  slash
sudo useradd -m -d /home/noslash noslash

sudo -u slash   mkdir /home/slash/.ssh
sudo -u noslash mkdir /home/noslash/.ssh

sudo ls -ladZ /home/{slash,noslash}/.ssh

rpm -qv shadow-utils
```

For me this results in:
```
drwxr-xr-x. 2 noslash noslash unconfined_u:object_r:ssh_home_t:s0 6 Apr  4 11:37 /home/noslash/.ssh
drwxr-xr-x. 2 slash   slash   unconfined_u:object_r:default_t:s0  6 Apr  4 11:37 /home/slash/.ssh
shadow-utils-4.6-14.el8.x86_64
```

I'm not entirely sure when this was fixed, but in RHEL 9.0 with `shadow-utils` v4.9 this doesn't happen.
Could be https://github.com/shadow-maint/shadow/pull/323 but I haven't confirmed.

**Comment by VladimirSlavik** [comment]
Thank you, that makes it clear. I can also confirm the RHEL 9 behavior is same on Rawhide.

I will split the commit into two, same as the two calls. One needs fixing, technically also on RHEL 8 although probably unused. The other call needs fixing in RHEL-8 and probably removing in upstream.

**Comment by VladimirSlavik** [comment]
Here's an archived version before implementing the changes outlined above: [0001-Run-restorecon-in-chroot-when-handling-home-dirs.zip](https://github.com/rhinstaller/anaconda/files/8513046/0001-Run-restorecon-in-chroot-when-handling-home-dirs.zip)

**Comment by VladimirSlavik** [comment]
I changed this to use a wrapper that solves all the conditions to ignore.

**Pull request merged**
