### PR TITLE
Create LVM devices file

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Write the LVM devices file with all PVs, to keep the previous behavior. Then, copy it to the new system.

Remove the `%post` script that did the same.

Resolves: [rhbz#2011329](https://bugzilla.redhat.com/show_bug.cgi?id=2011329)

Tests TODO, code ready.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
I am not sure how to actually make the tests pass. The blivet version needed for this is waiting to be <something> together with anaconda, so we won't get it, so the tests will always fail. I am not even sure what could the unit tests need, currently they fail on the one import so we won't know that they are broken...

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Comment by VladimirSlavik** [comment]
Nightly is ok. Code works. Still need to run tests though.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. Thanks!

**Review by poncovka — APPROVED** [review]
Thank you!

**Review by jstodola — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks! :)

**Comment by VladimirSlavik** [comment]
Note to self: When porting to upstream, add tests. Coverage of the module with this task is only 44%.

**Comment by VladimirSlavik** [comment]
Ported in #4292.

**Pull request merged**
