### PR TITLE
Simplify the implementation for the DBus interface for Users module

### PR DESCRIPTION
**Pull request by poncovka**
Call `DBusData.to_structure_list` to simplify the code.

### CODE REVIEW

**Comment by poncovka** [comment]
Codecov is just a little confused.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by VladimirSlavik** [comment]
From human perspective you replaced some special code paths with already existing universal code paths, so it's a net reduction, which is good.

Unfortunately Codecov is exactly right, but too simplistic about counting = too dumb to know what matters. From the mechanistic percent-counter perspective, replacing tested code paths with other also tested code paths decreases the amount of tested code paths, while the amount of untested code paths remains the same. So technically less % coverage is correct.

I love how this is all proven by no change to tests needed.

**Pull request merged**
