### PR TITLE
Mark the rhsm and syspurpose kickstart commands as useless (#1921787)

### PR DESCRIPTION
**Pull request by poncovka**
The main process shouldn't work with kickstart commands of DBus modules.
The `rhsm` and `syspurpose` commands are handled by the Subscription module.

Resolves: rhbz#1921787

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by M4rtinK — APPROVED** [review]
Hmm, must have been a leftover from the earlier implementations.
Thanks for the cleanup! :)

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by poncovka** [comment]
The backport is resolved by: https://github.com/rhinstaller/anaconda/pull/3156

**Pull request merged**
