### PR TITLE
Add kickstart test to test hostname

### PR DESCRIPTION
**Pull request by jkonecny12**
Test is easy:

* set network hostname 
* test it in the post section

### CODE REVIEW

**Comment by vpodzime** [comment]
> From what I found there is three ways how to test hostname.
> 1) By hostname
> 2) By reading /etc/hostname
> 3) By hostnamectl --static
> 
> I could test all the three but I think they all do the same thing i.e. cat /etc/hostname.

I think we need to care most about the output of ``hostnamectl --static`` as that will be more and more used in the future and it may gather data from multiple places which we need to cover all.

**Comment by vpodzime** [comment]
But now I realized that it wouldn't work as one would expect, I guess. It's probably again a fancy DBus thing that does nothing useful in combination with ``chroot()``. So just checking the ``/etc/hostname`` looks as the best choice here to me.

**Comment by jkonecny12** [comment]
Good point with the ``hostnamectl --static`` I will test it.

**Comment by jkonecny12** [comment]
I added ``hostnamectl --static &> /root/TEST`` to my kickstart file and I get proper output (the TEST file was in /mnt/sysimage/root/) with proper content. So it seems to me as posible solution for testing.

**Comment by vpodzime** [comment]
> I added hostnamectl --static &> /root/TEST to my kickstart file and I get proper output (the TEST file was in /mnt/sysimage/root/) with proper content. So it seems to me as posible solution for testing.

That however tests a different thing. It's only my theory (based on quite a lot of disappointing experience with these "systemd-ish" services), but I think ``hostnamectl --static`` does a DBus call and the current runtime configuration is checked, not the configuration in the chroot (i.e. installed system).

**Comment by jkonecny12** [comment]
So the ``/etc/hostname`` is the priority but I'm thinking of testing ``hostnamectl --static`` too. Even if this is read from the original system instead of chroot it could be tested.
What do you think?

**Comment by vpodzime** [comment]
Yes, we could test that here as well. And at some point we may also add kickstart tests that test other phases of the installation process -- e.g. the hostname should be set in the installation environment way early than in the ``%post`` phase. But that's a separate issue.

**Comment by jkonecny12** [comment]
Ok it's settled I change the tests to ``/etc/hostname`` and ``hostnamectl --static``.

I want to ask one more question it's related to my other PR too (https://github.com/rhinstaller/anaconda/pull/117 and https://github.com/rhinstaller/anaconda/pull/115). I'm using **network-*** prefix now but from I found in PR https://github.com/rhinstaller/anaconda/pull/118 you didn't want the prefix. So I change this to without prefix variants.

So this test will be named as hostname.[ks|sh]. Other tests will be renamed in the same manner. Do you agree @vpodzime, @clumens ?

**Comment by clumens** [comment]
Yeah, stripping out the network- prefix seems like a good idea here too.

**Comment by jkonecny12** [comment]
Thank you much.
I'm going to do the changes locally and push it.

**Pull request closed without merging**
