### PR TITLE
add translation badge

### PR DESCRIPTION
**Pull request by Jibec**

### CODE REVIEW

**Comment by M4rtinK** [comment]
Looks like the README file changes since the PR has been submitted. Could je rebase the pull request ? Thanks in advance! :)

**Comment by Jibec** [comment]
Please don't be lazy, just take the content and include it wherever you'll find it appropriate.

**Comment by VladimirSlavik** [comment]
#2335 is the rebased variant...

**Comment by VladimirSlavik** [comment]
Obsoleted by the now-merged #2335.

**Pull request closed without merging**
