### PR TITLE
remove authconfig support

### PR DESCRIPTION
**Pull request by pbrezina**
Authconfig compatibility tool (from authselect-compat) will be removed from Fedora 35:
https://fedoraproject.org/wiki/Changes/RemoveAuthselectCompatPackage

### CODE REVIEW

**Comment by pbrezina** [comment]
CI failed with `test_useless_command_map` is it correct to remove these commands like this (by removing the code) or should I do it differently?

**Comment by VladimirSlavik** [comment]
> CI failed with `test_useless_command_map` is it correct to remove these commands like this (by removing the code) or should I do it differently?

Yes, the tests are expected to do that, you will have to change them too.

**Comment by VladimirSlavik** [comment]
The kickstart tests all succeeded, except for authconfig which must fail. I think that's a success.

(Recording here because these results will disappear, once the fixed unit tests are force-pushed.)

**Comment by pbrezina** [comment]
Can you give me any hint how to update the failing test? I don't know where the 'auth' keyword is comming from.

**Comment by poncovka** [comment]
@pbrezina, the tests require a new pykickstart with the related changes. I will test it locally today.

**Review by poncovka — APPROVED** [review]
The code was tested locally. The changes look good to me. Thank you!

**Pull request merged**
