### PR TITLE
Remove support for metacity

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1961104

### CODE REVIEW

**Comment by poncovka** [comment]
Shouldn't we remove also the fallback code that tries to run `metacity`?

**Comment by rvykydal** [comment]
> Shouldn't we remove also the fallback code that tries to run `metacity`?

Oh we should, thank you:)

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Review by VladimirSlavik — APPROVED** [review]
LGTM, thank you!

**Review by jkonecny12 — APPROVED** [review]
Looks great to me! Thanks to this we should not need Build-root repository anymore. I'll create PR for that after this is merged!

**Pull request merged**
