### PR TITLE
Allow setting up bridge for fetching isntaller image from kickstart (…

### PR DESCRIPTION
**Pull request by rvykydal**
…#1373360)

Patch by Masahiro Matsuya <mmatsuya@redhat.com>

Resolves: rhbz#1373360

The bridge configuration is limited to what dracut allows with bridge= cmdline
option, ie using dracut default options for the bridge and slaves. Anaconda
will try re-activate the bridge via NM with bridge options from kickstart after
switchroot.

### CODE REVIEW

**Comment by rvykydal** [comment]
Checked to be working with kickstart test https://github.com/rhinstaller/kickstart-tests/blob/master/bridge-no-bootopts-net.ks.in

**Comment by M4rtinK** [comment]
BTW, there is a typo in the name of one of the commits:

Allow setting up bridge for fetching **isntaller** image from kickstart (#1373360)

**Comment by rvykydal** [comment]
Replaced caught Exception with GLib.GError.

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by M4rtinK** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Pull request merged**
