### PR TITLE
Do not run disabled kstests by default

### PR DESCRIPTION
**Pull request by rvykydal**
Depends on https://github.com/rhinstaller/kickstart-tests/pull/1138

### CODE REVIEW

**Comment by jkonecny12** [comment]
If possible, I would like to have as much as possible logic in the scripts. It's much easier to debug these compared to GH workflows.

**Comment by rvykydal** [comment]
> If possible, I would like to have as much as possible logic in the scripts. It's much easier to debug these compared to GH workflows.

Agreed, seems now is the time, I'll try to move the logic into generate-permian-query.py (also for /test-platforms workflow as I promised in https://github.com/rhinstaller/kickstart-tests/pull/1076#issuecomment-1993791814)

**Comment by rvykydal** [comment]
> > If possible, I would like to have as much as possible logic in the scripts. It's much easier to debug these compared to GH workflows.
> 
> Agreed, seems now is the time, I'll try to move the logic into generate-permian-query.py (also for /test-platforms workflow as I promised in [rhinstaller/kickstart-tests#1076 (comment)](https://github.com/rhinstaller/kickstart-tests/pull/1076#issuecomment-1993791814))

Updated the PR, requires https://github.com/rhinstaller/kickstart-tests/pull/1138/commits/8e2baf4cf6db0cd47310794b230d584012a868ec

**Comment by rvykydal** [comment]
@jkonecny12 the kickstart-test support is merged so I'd like to get this reviewed - to be available for use.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. 

I just wonder why we have special script for genereting arguments for second script.  I wonder if this generation shouldn't be part of the final script instead of this "complication". Anyway, that is for a different discussion.

Thanks!

**Comment by rvykydal** [comment]
> Looks good to me.
> 
> I just wonder why we have special script for genereting arguments for second script. I wonder if this generation shouldn't be part of the final script instead of this "complication". Anyway, that is for a different discussion.
> 
> Thanks!

The first script generates arguments that can be used by (passed to) launch script (the second transforms its cmdline API to permian tplib API). So the first script could be used in workflows not using permian (like the travis one kickstart-tests repo)

**Pull request merged**
