### PR TITLE
Allow to disable the Users module

### PR DESCRIPTION
**Pull request by poncovka**
Check whether the Users DBus module is enabled before it is used.
It might be disabled in the Anaconda configuration file.

(cherry-picked from a commit 675e26f)

Related: rhbz#1834535

### CODE REVIEW

**Comment by poncovka** [comment]
kickstart --testtype smoke

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by poncovka** [comment]
kickstart --testtype smoke

**Pull request merged**
