### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by poncovka**
Remove code that we no longer use.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Please check with @M4rtinK that the sensitive logger is not used in the still-unported registration code. Otherwise LGTM, thank you!

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by jkonecny12** [comment]
> Please check with @M4rtinK that the sensitive logger is not used in the still-unported registration code. Otherwise LGTM, thank you!

Also did we checked this these changes won't break InitialSetup in some way?

**Comment by poncovka** [comment]
> Please check with @M4rtinK that the sensitive logger is not used in the still-unported registration code.

I've checked the `rhel-9` branch. The sensitive logger is used only for geolocation.

> Also did we checked this these changes won't break InitialSetup in some way?

I've checked the initial setup code. It doesn't use any of these.

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

**Pull request merged**
