### PR TITLE
Fix for "Kickstart installation fails with error SettingsNotFoundError: SettingsNotFoundError('p7p1',)" (#1197960)

### PR DESCRIPTION
**Pull request by jkonecny12**
Network interfaces are read from NetworkManager via DBus but not all
interfaces must be registered when anaconda starts. This could result in
reading non-existing configuration file in initialization of Network
spoke.

This fix will dump configuration files for every new interface in every
refresh of the Network spoke.

Resolves: rhbz#1197960

Implemented changes from closed pull request https://github.com/rhinstaller/anaconda/pull/96

### CODE REVIEW

**Comment by dashea** [comment]
Does this only happen in text installs, or does the GUI spoke need to be updated as well?

**Comment by jkonecny12** [comment]
Only for text installs.

In GUI there is an event loop with registered callbacks for DBus NetworkManager events (events like add device). This is problem in text mode where is no event loop therefore we can't register callback so easily.

**Comment by jkonecny12** [comment]
This fix will be pushed to Rhel7 but after rebase so I didn't set label now.

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by jkonecny12** [comment]
Pushed

**Pull request closed without merging**
