### PR TITLE
webui - Fix pixel test failure due to string being translated

### PR DESCRIPTION
**Pull request by M4rtinK**
Our translation checking pixel test started to fail due to one of the
English strings being translated to German.

So we need to update the reference image in the reference image repo (done)
and also update the reference to the reference repo in Anaconda repo
(this PR).

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Thanks!

**Comment by M4rtinK** [comment]
Oops, had old checkout of the submodule so it overwrote some of the files by old ones. :P Try nr. 2. :D

**Review by VladimirSlavik — APPROVED** [review]

**Comment by M4rtinK** [comment]
Seems to be all good now, pixel test wise. :)

**Review by poncovka — APPROVED** [review]

**Pull request merged**
