### PR TITLE
Change absolute shebangs to /usr/bin/env equivalents

### PR DESCRIPTION
**Pull request by Epsilqn**
Current shebangs for executed files gave a direct path to where they would be located on most systems. With the current official Anaconda targets, this is not an issue. Some distributions however place their installations of Bourne, BASH, and Python at other locations. They may not have /bin symlinked to /usr/bin or may install in an entirely different location. /usr/bin/env is more consistent as it can support wherever an interpreter is located no matter the target system, and env is found at /usr/bin/env on almost every distribution.

### CODE REVIEW

**Comment by Epsilqn** [comment]
The PEP8 issue has been corrected.

**Comment by jkonecny12** [comment]
Thank you for your contribution but we had ``/usr/bin/env python`` in the past and it was removed because of Fedora required to do that.

For more info please read [here](https://fedoraproject.org/wiki/Features/SystemPythonExecutablesUseSystemPython).

Closing this PR now.

**Comment by jkonecny12** [comment]
Re-opening this PR for the further discussion. This can't be merged in this shape but maybe there is another solution to solve this.

Can you please tell us what distributions are you talking about? Are they already using Anaconda or they want to do that?

**Comment by jkonecny12** [comment]
No problem at all :).

**Pull request closed without merging**
