### PR TITLE
Document known crashes under VirtualBox

### PR DESCRIPTION
**Pull request by VladimirSlavik**
SSIA.

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Thanks for creating a known issue for that.
Interesting, do we know why is that happening?

**Comment by VladimirSlavik** [comment]
Unfortunately, no.

I have seen people install on Virtualbox just fine, even make articles about that, so it's definitely not a given that Virtualbox won't work. But so far there just wasn't anyone who would know what to look for, much less have time to debug this. The apparent randomness makes it look like a task for kernel people. So we're left only with this bit of lore that weird system corruption on Virtualbox sometimes happens.

**Comment by poncovka** [comment]
Hi, I think I have figured it out! Please, see my [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1902464#c13). There several workarounds:

1. Increase the memory if possible.
2. Use `--pbkdf*` options in a kickstart file.
3. Change the LUKS version to `LUKS1`.
4. Disable encryption.

**Comment by VladimirSlavik** [comment]
I suppose another indication separate from this would be to look for these:
- earlyoom
- WARNING:blivet:Less than [0-9]+ MiB RAM is currently free, LUKS2 format may fail.
- Activating service name='org.fedoraproject.Anaconda.Modules.Storage' (present more than once)

**Comment by poncovka** [comment]
In this case, the main indication is the storage configuration warning that we show in the UI:
`The available memory is less than 128 MiB which can be too small for LUKS2 format. It may fail.`

I am not sure if there are other cases of this crash that are not related to LUKS2.

**Comment by VladimirSlavik** [comment]
Superseded by #3308.

**Pull request closed without merging**
