### PR TITLE
webui: introduce a button to launch blivet GUI

### PR DESCRIPTION
**Pull request by KKoukiou**
This is available only for live images.
modify-storage

### CODE REVIEW

**Comment by KKoukiou** [comment]
I am not able  to build the live ISO (too few resources) so I cant test this. 

@M4rtinK @jkonecny12 can one of you build this for me?

**Comment by jkonecny12** [comment]
Here is link to your ISO: https://drive.google.com/file/d/1QY_HIyQNDohPYpo7ZKJBB8mqnqk2yFIJ/view?usp=sharing

**Comment by M4rtinK** [comment]
Please add a screenshot of how it looks like. :)

**Comment by VladimirSlavik** [comment]
Why can't I see it when it is launched?

**Comment by KKoukiou** [comment]
> Why can't I see it when it is launched?

@VladimirSlavik can you check again please? I can see it.

**Comment by KKoukiou** [comment]
> > Why can't I see it when it is launched?
> 
> @VladimirSlavik can you check again please? I can see it.

Hmm i think it depends if the window is full screen. I see in the journal when it fails: meta_window_set_stack_position_no_sync assertion 'window- stack_position = 0' failed

**Comment by vojtechtrefny** [comment]
Interesting, blivet-gui correctly starts in the foreground when Anaconda was launched from the *Welcome to Fedora* window. If I launch Anaconda from the launcher blivet-gui always starts in the background, even if the Firefox window is not maximized.

Also noteworthy is that some applications start in the foreground and some not (when starting Anaconda from the launcher): blivet-gui and Eye of GNOME start in the background, Nautilus and GNOME Weather start in the foreground. I'll try to look into this some more, maybe there's something I can do on the blivet-gui side to make sure it is always started in the foreground.

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

The issue with blivet-gui starting in the background will be most likely fixed in GNOME or blivet-gui itself so I don't think it should block this PR.

**Pull request merged**
