### PR TITLE
Allow encryption of thin logical volumes

### PR DESCRIPTION
**Pull request by poncovka**
Encryption of thin logical volumes is supported now.

Related: rhbz#1877777

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by jkonecny12** [comment]
Shouldn't this have backport to rhel-8 flag?

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :-)

Also, nice bug number! ;-)

**Pull request merged**
