### PR TITLE
Master add iso builds to templates

### PR DESCRIPTION
**Pull request by jkonecny12**
Change the ISO build to take branched Fedora sources instead of Rawhide.

Backport of https://github.com/rhinstaller/anaconda/pull/5098

### CODE REVIEW

**Comment by jkonecny12** [comment]
@VladimirSlavik seems that the ShellCheck has issues with our templating solution. Should I somehow bypass the check there?

**Comment by jkonecny12** [comment]
Resolved the missing bot requirement: https://github.com/cockpit-project/bots/pull/5176

**Comment by VladimirSlavik** [comment]
I think we need something like this:

```diff
      - id: ShellCheck
        name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v4
        with:
          severity: warning
          token: ${{ secrets.GITHUB_TOKEN }}
+         exclude-path: '*.j2'
```

Maybe it would run on the PR if it is changed with it?

**Comment by jkonecny12** [comment]
**UPDATED**
* Add j2 exclude for ShellCheck
* Rebased on top of https://github.com/rhinstaller/anaconda/pull/5104 so the issue I was facing should be fixed now

**Comment by jkonecny12** [comment]
**UPDATED**
* Rebased on top of templating PRs with updated rendered scripts

**Review by VladimirSlavik — APPROVED** [review]

**Pull request merged**
