### PR TITLE
Don't use Cockpit style overrides

### PR DESCRIPTION
**Pull request by poncovka**
Cockpit modify the PatternFly style, so let's drop it.

### CODE REVIEW

**Comment by jkonecny12** [comment]
Looks good to me but you need to update pixel tests for this.

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

**Comment by VladimirSlavik** [comment]
Ask @M4rtinK about the pixel tests please

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Pull request merged**
