### PR TITLE
Improve build of the ISO creating containers

### PR DESCRIPTION
**Pull request by jkonecny12**
### Change the ownership of the artifacts build from the ISO builds
The ISO builds are required to be done under root. That means that the resulting artifacts are also root owned. That makes troubles with `git clean` or similar calls. To solve that copy the `owner` and `group` from the input Anaconda RPMs to output artifacts. That should be correct most of the time.

### Also remove requirements to run make commands as root
The `sudo make ...` is just wrong and should not be used anymore. Instead `sudo` calls are abstracted in the `Makefile`.

### Improve usage of the container build cache
~Cache could save a lot of time during development but could cause outdated images because container don't know if the DNF call is outdated. To resolve this with a compromise let's set the cache live to ~24~ 6 hours. When cache is older than ~24~ 6 hours it will be ignored otherwise it's used.
This is significant improvement to container development!~
Moved to https://github.com/rhinstaller/anaconda/pull/5073

### Reduce size of the images
~For all the DNF calls disable weak dependencies.
This is harder to test but should be easily to fix potential issues.
However, the saving should be nice. In my simple testing:~

~anaconda-ci on master branch:
original size: 2.68 GiB
new size: 2.22 GiB~
Moved to https://github.com/rhinstaller/anaconda/pull/5072

### Improve the documentation of the ISO builds
Reflect new changes.
Improve the state based on the feedback I've got.

### CODE REVIEW

**Review by VladimirSlavik — COMMENTED** [review]
Thank you, this looks great!

Do you want to change also the workflows together with this, or leave it for later?

I wonder about the first commit. What are the risks of that change?

**Comment by VladimirSlavik** [comment]
Please split the PR according to what you are fixing or changing. Owner after image build = one thing. Caching = second thing. Dependencies = third thing.

**Comment by jkonecny12** [comment]
Moved the parts of the PR to separate PRs:
https://github.com/rhinstaller/anaconda/pull/5072
https://github.com/rhinstaller/anaconda/pull/5073

**Comment by VladimirSlavik** [comment]
Should be good to merge, I'll change the build action in #5071 as needed.

**Pull request merged**
