### PR TITLE
webui: parameterize ports for ssh, cockpit connection and http server

### PR DESCRIPTION
**Pull request by KKoukiou**
Previously no parallel test runs were possible, since there was port collision on the host.
This commit makes it possible for local test runs or CI to run in
paralle.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
LGTM, thank you.

I wonder about the hardcoded "35", but that's probably more complicated.

**Comment by KKoukiou** [comment]
> LGTM, thank you.
> 
> I wonder about the hardcoded "35", but that's probably more complicated.

When we start testing something else than rawhide we need to parametrize this as well.

**Comment by KKoukiou** [comment]
Hmm this seems to get stuck in the CI. Locally it finishes needs debugging

**Review by jkonecny12 — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
