### PR TITLE
Fix python3 requires in spec file

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Cherry-pick of 56541263bf3cc24365abb097f2a05e8102442ada 

----

Resolves: rhbz#1619153

Updating downstream patch which didn't work for osci gating tests.
Patch proposed by torsava@redhat.com

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
The following line is now missing, I assume it's intentional...
`Group: System Environment/Libraries`

**Comment by rvykydal** [comment]
Sorry, I rebased and force pushed the branch for the iso build so you'd need to rebase your PR on its new content.
But I thought we could do it now like Martin in inital setup:
https://github.com/rhinstaller/initial-setup/pull/95,
I opened:
https://github.com/rhinstaller/anaconda/pull/2569
(so we don't have to rebase this one)

**Comment by rvykydal** [comment]
And yes, Group has been removed intentionally.

**Comment by VladimirSlavik** [comment]
Ah, ok, closing then!

**Pull request closed without merging**
