### PR TITLE
Move the code for adding repositories to the DNF base

### PR DESCRIPTION
**Pull request by poncovka**
Call the `convert_ks_repo_to_repo_data` and `convert_repo_data_to_ks_repo` functions
to convert a kickstart repo object into its DBus representation and back.

Call the `add_repository` method of the DNF manager to add a repository to DNF.

### CODE REVIEW

**Review by jkonecny12 — COMMENTED** [review]
In general looks good to me. However, I would rather see the first commit in the Clean architecture design.

Basically, have object which has the data in a unified format (just blackbox) and have `read_ks_data`, `write_ks_data` and similar function as interface for these data.

However, I understand if you don't want to complicate things with that, it would just be "nicer".

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by poncovka** [comment]
> In general looks good to me. However, I would rather see the first commit in the Clean architecture design.
> 
> Basically, have object which has the data in a unified format (just blackbox) and have `read_ks_data`, `write_ks_data` and similar function as interface for these data.
> 
> However, I understand if you don't want to complicate things with that, it would just be "nicer".

This is a temporary solution. The kickstart repo data will be eventually processed by the DNF payload module and we will keep only the repo data objects. However, there is too much code that would have to be changed at once, so I am doing it this way to make the changes smaller.

**Comment by poncovka** [comment]
Rebased and tested.

**Pull request merged**
