### PR TITLE
Add none user interface.

### PR DESCRIPTION
**Pull request by poncovka**
None user interface (nui) should work the same way as the noninteractive tui, but with limited output. It is a substep to the further modularization. It starts with `inst.noui` option.

### CODE REVIEW

**Comment by poncovka** [comment]
In case of failure:
nui_fail

In case of success:

The messages between the dots are not supposed to be there, it is a reported bug in `rpm`.

nui_success

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by cgwalters** [comment]
That's a scary amount of new code for this.  Can't this be a flag in the tui code or something?

**Comment by jkonecny12** [comment]
Almost all the code here is appending and it will be executed only in a special mod. So or so it's now in discussion if this patch will be merged as it is now or it will be reworked.

**Pull request closed without merging**
