### PR TITLE
Add configuration files for Read the Docs

### PR DESCRIPTION
**Pull request by poncovka**
Provide new configuration files for Read the Docs and its requirements.

Related: https://github.com/readthedocs/readthedocs.org/issues/8616

### CODE REVIEW

**Comment by poncovka** [comment]
Can keep the `docs/readthedocs.org:anaconda-installer` check enabled?

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

I think this is #infra too, but feel free to ignore that.

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well - thanks a lot! :) A very nice improvement & one more thing that makes Anaconda more robust. :)

**Pull request merged**
