### PR TITLE
Add support for iso creator container

### PR DESCRIPTION
**Pull request by jkonecny12**
This can be easily adjusted for the current branch so we could simplify GitHub workflows and avoid code duplication this way.

(cherry picked from commit 64344ce5b5b7c93207ee855b0b4f97de75ae7447)

### CODE REVIEW

**Comment by jkonecny12** [comment]
Tested locally.

**Comment by VladimirSlavik** [comment]
I think the repo file is missing.

**Comment by jkonecny12** [comment]
Ha you are correct! Thanks a lot for spotting that!

**UPDATED:**
* Add missing rhel-8 repository file.

**Comment by jkonecny12** [comment]
@jstodola another request for merging this infra work. It would be great to have KS support for RHEL-8 ASAP.

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you!

**Comment by jkonecny12** [comment]
**UPDATED:**
* Backported quay.io prefix for our containers so it is consistent on all branches.

**Comment by jkonecny12** [comment]
Tested locally and from the workflows it should be good enough.

**Review by VladimirSlavik — APPROVED** [review]

**Review by poncovka — APPROVED** [review]
Thanks!

**Review by jstodola — APPROVED** [review]

**Comment by jkonecny12** [comment]
Add missing `#infra` to the commit message.

**Pull request merged**
