### PR TITLE
network: Overwrite resolv.conf generated by systemd

### PR DESCRIPTION
**Pull request by cgwalters**
[Note: against F22-branch, but installing rawhide content, that's how I hit the bug]

systemd changed to generate a symlink resolv.conf ->
/run/networkd/resolv.conf which doesn't exist at installation time.

(What we should do at some point is tell NetworkManager to
 serialize its state into the installation root and get out
 of the business of writing these files directly)

https://bugzilla.redhat.com/show_bug.cgi?id=1116651

### CODE REVIEW

**Comment by cgwalters** [comment]
Doing a quick self-review, I started wondering why the "only write `/etc/resolv.conf` if it didn't exist, or livecd" logic existed.  (Which I'm changing to "overwrite always").  This goes way way back to  https://github.com/rhinstaller/anaconda/commit/633fb6244a6dbbf07cbb0e8547bd9282be073d7c

Possibly, we could enhance the logic here to say "only overwrite if not owned by an RPM"?   Or we just say that people should do network configuration in `%post` (which would overwrite whatever Anaconda did).

**Comment by bcl** [comment]
We should say that systemd should not be creating a broken symlink and leave the livecd logic alone. I do like the bit where overwrite really means replace it. As that old commit explains, some people drop in these files themselves and expect it to be left alone.

**Comment by cgwalters** [comment]
Ok, how about "overwrite if it's a broken symlink"?

**Comment by bcl** [comment]
That just seems like a hack to me. What if another package wants to create a broken symlink on purpose?
systemd is what is broken here, it is what should be fixed. It assumes that no other package in the install package set might create /etc/resolv.conf, something that it has no way of knowing at install time. If it really wants this symlink it should be checking it at runtime.

**Comment by cgwalters** [comment]
The complexity here is systemd *is* creating it at "runtime", but allow `%post` to work we're running systemd-tmpfiles at install time.

The way `systemd-tmpfiles` works, it won't overwrite anything that already exists at that time.  So this is really an install time only bug.

As far as "What if another package wants to create a broken symlink on purpose?"  - That doesn't seem like a realistic scenario to me.

**Comment by cgwalters** [comment]
I just force-pushed a new commit which only unlinks if it's a broken symlink.  Haven't tested yet.

**Comment by clumens** [comment]
Can one of the admins verify this patch?

**Comment by dashea** [comment]
Closing since this is an issue between systemd and NetworkManager, and we are not going to fix their problems in anaconda. For what it's worth, we worked around, in lorax, the issue of systemd-tmpfiles creating a bad resolv.conf at the time boot.iso is booted by not allowing systemd to create anything in /etc since none of what it tries to create does any good for systems with a stateful /etc.

**Pull request closed without merging**
