### PR TITLE
Add support for anaconda-rpm containers to refresh workflow

### PR DESCRIPTION
**Pull request by jkonecny12**
We will use power of combinations of matrix. That will create all the combinations between container-tag and container-type variables for us and we don't have to define new job for this.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by jkonecny12** [comment]
It's failing, looking for solution right now.

**Comment by jkonecny12** [comment]
**UPDATED:**
* Fixed issues found from the first version.

**Comment by jkonecny12** [comment]
Here is the test run:
https://github.com/Test-anaconda-org/anaconda/runs/1927872126?check_suite_focus=true

Everything failed but that is because of missing secrets and missing blivet on ELN.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
