### PR TITLE
Use the DBus module for the image and tar payloads

### PR DESCRIPTION
**Pull request by poncovka**
* Create the tarball source module.
* Create complete installation tasks for image and tar payload installations.
* Use the DBus module for the image and tar payloads.

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by jkonecny12 — COMMENTED** [review]
Looks good to me so far.

**Comment by poncovka** [comment]
Updated and tested.

**Review by jkonecny12 — APPROVED** [review]
Still looks good to me.

**Pull request merged**
