### PR TITLE
Rename installclass_atomic to Fedora Atomic Host

### PR DESCRIPTION
**Pull request by jkonecny12**
It sounds better and also there will be Fedora Atomic Workstation soon.

*Suggested-by: Dusty Mabe*

### CODE REVIEW

**Comment by dustymabe** [comment]
LGTM. I think we can go ahead and merge this but I will mention @cgwalters here so he can comment on it when he gets back from AFK time. If he tells us next week this was a bad change then we can just revert it. 

👍

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by cgwalters** [comment]
LGTM

**Pull request merged**
