### PR TITLE
Master restorecon changes

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Port #2636 and #2659.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Changing to draft as the "parent" rhel PR is still too much WIP.

**Comment by VladimirSlavik** [comment]
I think the tests actually pass, as far as this is concerned...

**Comment by VladimirSlavik** [comment]
Now 100% true to the originals. (And ready to merge.)

**Comment by jkonecny12** [comment]
jenkins, test this please

**Pull request merged**
