### PR TITLE
network: do not crash on destroyed device object in GUI

### PR DESCRIPTION
**Pull request by rvykydal**
Port of https://github.com/rhinstaller/anaconda/pull/5482

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by rvykydal** [comment]
/kickstart-test --testtype network --skip-testtypes=gh576,gh595,rhbz1960279,gh641,gh774,gh790,gh970

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Pull request merged**
