### PR TITLE
webui: Avoid crash on non-translated languages

### PR DESCRIPTION
**Pull request by adamkankovsky**
This PR solves crash avoidance when selecting a language for which there is no translation in anaconda. The crash avoidance is created by displaying UTF language shortcuts for these languages in the Review page instead of the unknown name.

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
Can you please write a test for this? 
Utilize the backend dbus call from the test ot set a language like macedonian, which used to create the crash and make sure to the that:
1. there is not crash
2. the language info are presented correctly

**Review by VladimirSlavik — COMMENTED** [review]
Clever idea! Yes, tests please.

**Review by VladimirSlavik — APPROVED** [review]
Thanks!

**Review by KKoukiou — APPROVED** [review]
Very clean. Thanks for the test.

please next time add the tests in the same commit as the feature.

**Pull request merged**
