### PR TITLE
Add a kickstart specification for the main process

### PR DESCRIPTION
**Pull request by poncovka**
Use a kickstart specification to define command and data overrides
for the kickstart handler used by the main process. It means that
we can define commands that will be used instead of commands that
should be ignored.

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

We should celebrate the victory of Useless Commands. Somehow.

**Comment by poncovka** [comment]
Tested locally.

**Pull request merged**
