### PR TITLE
Behave better in the abscence of locales

### PR DESCRIPTION
**Pull request by dashea**
Concede that everything is an absolute disaster and try to muddle through

### CODE REVIEW

**Comment by dashea** [comment]
Added a commit so that the GUI is not translated into an unsupported locale.

**Comment by jkonecny12** [comment]
In the first commit the last word in the last sentence. Maybe it's my bad English but I think it shouldn't be there or you want there ``anywhere`` instead.
Otherwise looks good to me.

**Comment by vpodzime** [comment]
> In the first commit the last word in the last sentence. Maybe it's my bad English but I think it shouldn't be there or you want there anywhere instead.

I think ``anymore`` makes sense there too.

**Comment by dashea** [comment]
Pushed to master and f24.

**Pull request closed without merging**
