### PR TITLE
Allow to disable the Security module

### PR DESCRIPTION
**Pull request by poncovka**
Check whether the Security DBus module is enabled before it is used.
It might be disabled in the Anaconda configuration file.

(cherry-picked from a commit f19f39d)

Related: rhbz#1834535

### CODE REVIEW

**Review by VladimirSlavik — COMMENTED** [review]
Looks good to me. Thank you!

**Review by VladimirSlavik — APPROVED** [review]

**Comment by poncovka** [comment]
Updated.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well.

**Pull request merged**
