### PR TITLE
webui: pin down tag for fetching cockpit's test library

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me & thanks for the fix! :)

BTW, how do you handle these pins in the cockpit project ? I guess if forgotten over time, it could perhaps break something instead due to the library being outdated. Just wait for CI to catch it or possibly some pro-active regular bumps ?

**Comment by KKoukiou** [comment]
> Looks good to me & thanks for the fix! :)
> 
> BTW, how do you handle these pins in the cockpit project ? I guess if forgotten over time, it could perhaps break something instead due to the library being outdated. Just wait for CI to catch it or possibly some pro-active regular bumps ?

The latter. You need to manually now and then bump these cockpit tags.

**Review by poncovka — APPROVED** [review]

**Comment by jkonecny12** [comment]
Looks great to me. @M4rtinK could you please add this bumping to a on-duty tutorial we have.

**Pull request merged**
