### PR TITLE
Move some validation code into proxy object from gui

### PR DESCRIPTION
**Pull request by jcpunk**
Does it make sense to move some of the proxy validation code into the proxy string object?

This is an initial stab.

### CODE REVIEW

**Comment by M4rtinK** [comment]
Is there some kinda of a backstory for this change (eq. do you need it for an addon you are developing or do you see this just a general code quality improvement) ? That could help us with maintaining the code after we merge it.

**Comment by jcpunk** [comment]
I'm looking into the installation_source.py spoke.  There are a few comments scattered about that suggest the code could be better optimized[1].

I'm mostly looking at this as a general code improvement.  I'm hopeful to begin leveraging this to start the suggested cleanup.

[1] https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/ui/gui/spokes/installation_source.py#L416

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by jkonecny12** [comment]
That failed test is not related to this PR.

**Comment by M4rtinK** [comment]
PR CI should be fixed now - rerunning the tests.

**Comment by M4rtinK** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jcpunk** [comment]
I'm going to close this out for now and revisit following the UI changes

**Pull request closed without merging**
