### PR TITLE
webui: Let error reporting dialog test area auto resize

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by rvykydal** [comment]
I seem to be getting this using `test/webui_testvm.py`
Screenshot from 2023-08-24 14-08-43

**Comment by KKoukiou** [comment]
@rvykydal you 're right - sorry - tested in a screen size that worked  and though it was ok. re-checking.

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.
Looking at it the helper texts actually belongs logically to the button so it seems to be at the right place now.

**Pull request merged**
