### PR TITLE
webui: users: do not try to use the proxy before it's ready

### PR DESCRIPTION
**Pull request by KKoukiou**
This fixes the flaky test which is always failing on first try as seen
here.

https://grafana-frontdoor.apps.ocp.ci.centos.org/d/ci/cockpit-ci?orgId=1&var-cockpit_project=rhinstaller%2Fanaconda

### CODE REVIEW

**Comment by KKoukiou** [comment]
Nope did not work, moving to draft.

**Comment by KKoukiou** [comment]
Tests are passing now without retry.

**Review by M4rtinK — APPROVED** [review]
Looks good as far as I can tell. :)

**Pull request merged**
