### PR TITLE
Port DNS kickstart options to f38

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Port of #4519. Originally, we targeted f38 with this.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Tests won't work until pykickstart goes in: https://bodhi.fedoraproject.org/updates/FEDORA-2023-6312edccf2

**Review by poncovka — APPROVED** [review]
Thanks!

**Comment by VladimirSlavik** [comment]
Manual testing ok, will try unit tests.

**Comment by VladimirSlavik** [comment]
Unit tests and rpm tests passed locally after adding new kickstart to the container.

**Comment by VladimirSlavik** [comment]
The pykickstart update is now frozen.

**Comment by VladimirSlavik** [comment]
Given how much bugfixing this needed in rawhide, this doesn't feel ready for f38.

@bcl will cancel the kickstart side by bumping the version in kickstart to 39: https://github.com/pykickstart/pykickstart/pull/448

**Pull request closed without merging**
