### PR TITLE
Ostreecontainer rhel 9

### PR DESCRIPTION
**Pull request by rvykydal**
This is a take on port of https://github.com/rhinstaller/anaconda/pull/4561 to rhel-9 branch.

It could replace the https://github.com/rhinstaller/anaconda/pull/5277 which is incorporating also some parts of https://github.com/rhinstaller/anaconda/pull/3234 (updating rpm payload module including the installation method but not actually migrating to it completely).

I am trying to do just a port of the master PR so we can eventually port the https://github.com/rhinstaller/anaconda/pull/3234 on top of it.

TODO:
- [x] port the tests
- [x] test with kickstart tests

### CODE REVIEW

**Comment by rvykydal** [comment]
The tests are passing for me locally when updating the pykickstart in the CI container to the required version.

**Comment by rvykydal** [comment]
The PR is passing on ported upstream kickstart test: https://github.com/rhinstaller/kickstart-tests/pull/1041
The ported test has bootloader disabled - it should be handled by followup bootupd work (porting https://github.com/rhinstaller/anaconda/pull/5342 and related to rhel-9) I believe.

**Comment by rvykydal** [comment]
@jkonecny12 we might want to consider [Do not crash on default None values of ostreecontainer command](https://github.com/rhinstaller/anaconda/pull/5399/commits/d20aa8f3fde9c410017baf0592f2e8bf6b07c4d5) also for master to be safer (not crashing on default / missing values in kickstart).

**Review by jkonecny12 — APPROVED** [review]
Looks great to me. Thanks!

We should backport the last commit to master :)

**Comment by cgwalters** [comment]
Hm so this didn't roll in https://github.com/rhinstaller/anaconda/pull/5342 and https://github.com/rhinstaller/anaconda/pull/5363 though?  I think we need those

**Pull request merged**
