### PR TITLE
Prevent issues with encrypted LVs on renamed VGs (#1224045)

### PR DESCRIPTION
**Pull request by vpodzime**
If a VG (or a container generally) is renamed, we need to take into account the
fact that its child device (can) get renamed too and update our list of
already-used names accordingly.

### CODE REVIEW

**Comment by vpodzime** [comment]
Pushed a rebased version of the patch.

**Comment by jkonecny12** [comment]
Seems good to me

**Comment by jkonecny12** [comment]
If this is pushed to master already please close it :)

**Comment by bcl** [comment]
Looks good to me.

**Comment by vpodzime** [comment]
Pushed.

**Comment by vpodzime** [comment]
Pushing to the f23-branch too as it fixes an F22 bug.

**Pull request closed without merging**
