### PR TITLE
Always quote values in ifcfg- files (#1279131)

### PR DESCRIPTION
**Pull request by bcl**
parse-kickstart doesn't use SimpleConfig and wasn't quoting everything.
These files are shell executables so everything needs to be quoted to
prevent accidentally trying to run unexpected binaries.

Resolves: rhbz#1279131

### CODE REVIEW

**Comment by jkonecny12** [comment]
Looks good to me.

**Comment by vpodzime** [comment]
One would expect the ``shlex`` module to have a function for this, but there seems to be none. Looks good to me too.

**Comment by bcl** [comment]
> One would expect the shlex module to have a function for this, but there seems to be none. Looks good to me too.

In pyanaconda we use SimpleConfig, but to get that into dracut we'd have to pull everything into the initrd :)

**Comment by bcl** [comment]
pushed to master.

**Comment by bcl** [comment]
Pushed.

**Pull request closed without merging**
