### PR TITLE
Fix time setting for daylight savings, let Python do the work

### PR DESCRIPTION
**Pull request by AdamWill**
Since the port from pytz to zoneinfo in #3167, anaconda has set
the system clock one hour too fast when installing for a timezone
that does daylight savings time, during daylight savings time.

There turns out to be a lot of history behind this calculation,
see https://bugzilla.redhat.com/show_bug.cgi?id=1965718#c4 for
details.

It turns out that since Python 3.3, datetime objects have the
`timestamp()` method, which does exactly what we want here. In
my tests it gives the correct answer in every problematic case,
including the one I found was broken in current code, and the
Kolkata and Aden timezones mentioned in
https://bugzilla.redhat.com/show_bug.cgi?id=1293314 . So I think
we should just use that.

Resolves: rhbz#1965718

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
I'd take testing of this, but I have a lot of stuff already. Feel free to assign this to me, but only if this can wait.

**Comment by AdamWill** [comment]
It is breaking two openQA tests; I could set those specific tests to use an updates.img but it's a bit awkward. If we don't fix them, we won't notice when anything *else* breaks in the things those tests test.

**Comment by AdamWill** [comment]
OK, so I changed this to be even simpler: there is actually a `timestamp()` method for datetime objects since Python 3.3 that does precisely what we want, and seems to give the correct result in every case. I don't think we need to be compatible with Python < 3.3 any more, so let's just use that.

I also added tests, since we didn't have any. I have checked that these tests pass with both my original fix and this newer simpler fix, and the EST-during-DST tests fail as expected with the current code. So I think the test suite behaves correctly and proves that this code should be good.

**Comment by poncovka** [comment]
> I'd take testing of this, but I have a lot of stuff already. Feel free to assign this to me, but only if this can wait.

I will take it, but it will have to wait till Monday. Sorry about that.

**Comment by VladimirSlavik** [comment]
Actually, ditto re Monday. Let's try again then.

**Comment by AdamWill** [comment]
it has unit tests now!

**Review by poncovka — APPROVED** [review]
Looks good to me. Thank you for fixing it!

**Pull request merged**
