### PR TITLE
webui: Update request IDs when removing mount point row

### PR DESCRIPTION
**Pull request by vojtechtrefny**
When removing a mount point row, we need to decrease IDs for the requests with higher IDs to avoid having duplicate ID when adding a new row.

Resolves: rhbz#2232398

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
I am not sure if this is the best way to fix this issue, but it seems to be working fine. The problem is that after removing a row which is not last we end up with a "gap" in the IDs and next row/mount point added now has the same ID as the previous one, because new IDs are allocated simply as *number of requests + 1*. I was thinking about changing this to *last request + 1* but that also might be problematic because we also use the request ID as the row ID. Feel free to suggest a better approach.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me AFAICT :)

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
