### PR TITLE
network: do not crash on infiniband devices activated in initramfs

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1883173

### CODE REVIEW

**Comment by rvykydal** [comment]
We need to apply this patch as downstream patch or in a new rhel-8.3.0 branch.

**Comment by rvykydal** [comment]
It is already present upstream as https://github.com/rhinstaller/anaconda/commit/a3e46c49216f76f73097587b15ded52b253ce3d2

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by jkonecny12** [comment]
This PR is not tested here. It's testing 3a9ffa8e71a516c9d177f77243010f3e5331d337 instead.

The PR https://github.com/rhinstaller/anaconda/pull/2942 have to be merged first and then rebase this on top of that.

**Comment by rvykydal** [comment]
> This PR is not tested here. It's testing [3a9ffa8](https://github.com/rhinstaller/anaconda/commit/3a9ffa8e71a516c9d177f77243010f3e5331d337) instead.
> 
> The PR #2942 have to be merged first and then rebase this on top of that.

Done, passed

**Comment by rvykydal** [comment]
Updated rhbz reference

**Pull request merged**
