### PR TITLE
Remove hub and spoke user account for Fedora Design Suite

### PR DESCRIPTION
**Pull request by luyatshimbalanga**
This commit removes hub and spoke user account to follow Workstation approach.

**Thank you** for your contribution!

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
This will need extending tests. See eg. https://github.com/rhinstaller/anaconda/pull/3680/files for where to look. The tests might be slightly different these days, but once you know where to look, it's just copypasta and changing the strings to match your new config.

**Comment by VladimirSlavik** [comment]
What the bleep happened here?

**Comment by poncovka** [comment]
So, this is my theory. I think that the fork uses [the pull app](https://github.com/apps/pull) to "keep the fork up-to-date". Then 8 hours ago, our workflow automatically created and pushed a release commit to our `master` branch. That triggered the pull app and caused a forced rebase of the `master` branch on the fork. Now the fun part. This pull request is not opened for a dedicated feature branch created on the fork, it is opened for the `master` branch on the fork. So after the actions of the pull app, this is basically our `master` branch. Therefore, "poncovka deployed to releases" and "InStallker merged commit" are statuses of our `master` branch. And since I was the last person who touched the implementation of the deployment workflow, GitHub uses my name in that status.

What does it mean? The changes in this pull request were dropped by the pull app, so they were not merged to our repository. You can see that this pull request has 0 commits now. @luyatshimbalanga, could you open a new pull request and use a dedicated feature branch or disable the pull app, please?

**Comment by VladimirSlavik** [comment]
Thanks for the writeup - I agree that is the most probable explanation.

**Comment by luyatshimbalanga** [comment]
I created another pull request with disabled pull app. See https://github.com/rhinstaller/anaconda/pull/4554

**Pull request merged**
