### PR TITLE
infra: Name built images sensibly

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Instead of boot.iso, name the images according to what they are built from:
- `pr<#>-<hash>-boot.iso`
- `master-<hash>-boot.iso`

A similar scheme is used for the artifact zip names.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Yes, this works. Successful runs:
- Manually started https://github.com/VladimirSlavik/anaconda/actions/runs/5715981087
- On comment https://github.com/VladimirSlavik/anaconda/actions/runs/5716167703

**Comment by VladimirSlavik** [comment]
Now with 100% more eyes on comment...

**Comment by VladimirSlavik** [comment]
So, the end result is pretty nice, I think.
- If you comment, this is how it looks like: https://github.com/VladimirSlavik/anaconda/pull/112#issuecomment-1658767738 -> run https://github.com/VladimirSlavik/anaconda/actions/runs/5717422179/job/15491137457
- If you start it from the actions tab manually, it works too: https://github.com/VladimirSlavik/anaconda/actions/runs/5717830623

**Comment by VladimirSlavik** [comment]
Next step after merging this would be integration of the live builds.

**Comment by VladimirSlavik** [comment]
Blocked because we need github cli (gh) on our runners.

**Review by jkonecny12 — COMMENTED** [review]
Great improvement. Thanks!

**Pull request merged**
