### PR TITLE
Fix shell quotes in dracut

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Shellcheck is more happy now: No SC2068 "Double quote to prevent globbing and word splitting."

This should not change anything, but we will see. Kickstart tests to run:
- [x] smoke
- [x] coverage
- [x] network (rvykydal says: maybe random choice, include bootopts, exclude bindtomac)
- [x] driverdisk-related ones

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
/kickstart-test --testtype coverage --skip-testtypes knownfailure

**Comment by VladimirSlavik** [comment]
/kickstart-test --testtype network --skip-testtypes knownfailure

**Comment by VladimirSlavik** [comment]
At the volume of tests used here, flakes are to be expected, I think. The results will need more interpretation.

**Review by jkonecny12 — COMMENTED** [review]
Looks good to me so far.

**Comment by VladimirSlavik** [comment]
/kickstart-test driverdisk-disk ntp-pools lvm-1 reqpart default-desktop network-prefixdevname bond2-pre --skip-testtypes knownfailure

**Comment by VladimirSlavik** [comment]
So: `driverdisk-disk` is still broken, so that had to fail, and `network-prefixdevname` which timed out, is to be skipped on fedora. In other words, all kickstart tests eventually succeeded.

I think that means we can't make it better, and can speculatively merge and let the other testing layers verify that this works.

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Review by rvykydal — APPROVED** [review]
Although I wonder why some vars are not required to be quoted - if the update makes the spellcheck happy, I am happy too.
LGTM

**Comment by jkonecny12** [comment]
> Although I wonder why some vars are not required to be quoted - if the update makes the spellcheck happy, I am happy too. LGTM

I guess it has logic that quoting never hurts and could avoid issues in future modification of the code.

**Review by jkonecny12 — APPROVED** [review]

**Pull request merged**
