### PR TITLE
Skip payload-related spokes in the initial setup (#1915541)

### PR DESCRIPTION
**Pull request by poncovka**
The initial setup doesn't install payload. It was broken by the commit ef0b5e9.

Resolves: rhbz#1915541

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
LGTM! Even thought I think we should always run `should_run` of `NormalSpoke`.

**Comment by AdamWill** [comment]
Is there any way we can add initial-setup tests to the CI for anaconda? It seems like we hit this pattern "change in anaconda passes anaconda tests, but breaks initial-setup" relatively often, it'd be nice to catch it before it goes out to Rawhide...

**Comment by poncovka** [comment]
> Is there any way we can add initial-setup tests to the CI for anaconda? It seems like we hit this pattern "change in anaconda passes anaconda tests, but breaks initial-setup" relatively often, it'd be nice to catch it before it goes out to Rawhide...

I am really sorry about that. It is definitely on our list, but it a completely different set up, so we might need to write something new. I am very unhappy about the current situation as well.

**Comment by M4rtinK** [comment]
I can report that with this PR applied to Anaconda I can get to the TUI to start, but the GUI still crashes:

```
Jan 15 14:42:56 localhost.localdomain initial-setup[682]: Initial Setup crashed due to unhandled exception:
                                                          Traceback (most recent call last):
                                                            File "/usr/lib64/python3.9/site-packages/pyanaconda/ui/gui/__init__.py", line 729, in>
                                                              self._currentAction.refresh()
                                                            File "/usr/lib64/python3.9/site-packages/pyanaconda/ui/gui/hubs/__init__.py", line 36>
                                                              self._createBox()
                                                            File "/usr/lib/python3.9/site-packages/initial_setup/gui/hubs/initial_setup_hub.py", >
                                                              Hub._createBox(self)
                                                            File "/usr/lib64/python3.9/site-packages/pyanaconda/ui/gui/hubs/__init__.py", line 12>
                                                              cats_and_spokes = self._collectCategoriesAndSpokes()
                                                            File "/usr/lib/python3.9/site-packages/initial_setup/gui/hubs/initial_setup_hub.py", >
                                                              return common.collectCategoriesAndSpokes(self, GUI_spoke_class)
                                                            File "/usr/lib/python3.9/site-packages/initial_setup/common.py", line 63, in collectC>
                                                              candidate_spokes = collect_spokes(hub_instance.paths["spokes"], spoke_parent_class)
                                                            File "/usr/lib/python3.9/site-packages/initial_setup/common.py", line 40, in collect_>
                                                              spokes.extend(collect(mask, path,
                                                            File "/usr/lib64/python3.9/site-packages/pyanaconda/core/util.py", line 1307, in coll>
                                                              members = [(name, getattr(module, name))
                                                            File "/usr/lib64/python3.9/site-packages/pyanaconda/core/util.py", line 1309, in <lis>
                                                              if p(getattr(module, name))]
                                                            File "/usr/lib64/python3.9/site-packages/pyanaconda/core/util.py", line 1301, in <lam>
                                                              p = lambda obj: inspect.isclass(obj) and pred(obj)
                                                            File "/usr/lib/python3.9/site-packages/initial_setup/common.py", line 41, in <lambda>
                                                              lambda obj: issubclass(obj, spoke_parent_class) and obj.should_run("firstboot", Non>
                                                            File "/usr/lib64/python3.9/site-packages/pyanaconda/ui/gui/spokes/language_support.py>
                                                              return context.payload.type not in PAYLOAD_LIVE_TYPES
                                                            File "/usr/lib64/python3.9/site-packages/pyanaconda/ui/context.py", line 51, in paylo>
                                                              return self._anaconda.payload
                                                            File "/usr/lib64/python3.9/site-packages/pyanaconda/anaconda.py", line 92, in payload
                                                              elif self.opts.liveinst:
                                                          AttributeError: 'NoneType' object has no attribute 'liveinst'
                                                          
                                                          During handling of the above exception, another exception occurred:
                                                          
                                                          Traceback (most recent call last):
                                                            File "/usr/libexec/initial-setup/initial-setup-graphical", line 10, in <module>
                                                              is_instance.run()
                                                            File "/usr/lib/python3.9/site-packages/initial_setup/__init__.py", line 419, in run
                                                              ret = ui.run()
                                                            File "/usr/lib64/python3.9/site-packages/pyanaconda/ui/gui/__init__.py", line 782, in>
                                                              self._gui_lock.release()
                                                          AttributeError: 'NoneType' object has no attribute 'release'
```

**Comment by poncovka** [comment]
All `context.payload` calls should be handled now.

**Comment by M4rtinK** [comment]
@poncovka Thanks, seems to work fine now as far as I can tell. :)

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks a lot! :)

**Pull request merged**
