### PR TITLE
Ignore %anaconda section in parse-kickstart

### PR DESCRIPTION
**Pull request by bcl**

### CODE REVIEW

**Comment by dashea** [comment]
The same thing will need to happen in handle-sshpw (which also needs to ignore %addon)

**Comment by clumens** [comment]
We had talked about this in IRC yesterday, and my take on it was that the appropriate fix was making pykickstart not error out on unknown sections, given that there's an infinite number of user-definable sections now.  Of course this would fix it on anaconda's end, but doing something in pykickstart would fix it for everyone.

**Comment by bcl** [comment]
I'm in favor of doing both -- explicitly ignore them, and make pykickstart not fail.

**Comment by clumens** [comment]
Ah, the ol' suspenders and belt approach.  Yeah that works.

**Comment by bcl** [comment]
pushed to master and f22-branch

**Pull request closed without merging**
