### PR TITLE
Adapt makebumpver to rhel-devel -> rhel-8 branch renaming.

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1666319

### CODE REVIEW

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
PR with port to Fedora: https://github.com/rhinstaller/anaconda/pull/2397

**Comment by rvykydal** [comment]
Ported to master with https://github.com/rhinstaller/anaconda/pull/2397

**Pull request merged**
