### PR TITLE
rpmostreepayload: Substitute ${basearch} in ostreesetup ref

### PR DESCRIPTION
**Pull request by cgwalters**
See: https://pagure.io/atomic-wg/issue/299

Basically for multi-arch systems like Fedora it's convenient
to be able to reuse the same kickstart across multiple architectures.

This requires a new rpmostree API: https://github.com/projectatomic/rpm-ostree/pull/877
(So be careful about backporting this; if we do that I may try
 to have it check for the API availability)

### CODE REVIEW

**Comment by cgwalters** [comment]
Tested locally against https://kojipkgs.fedoraproject.org/compose/branched/Fedora-27-20170912.n.0 /compose/Atomic/x86_64/iso/Fedora-Atomic-ostree-x86_64-27-20170912.n.0.iso using an `updates.img` from the f27-devel branch.

**Comment by cgwalters** [comment]
And I changed my local kickstart test to do:

`ostreesetup --nogpg --osname=fedora-atomic --remote=fedora-atomic --url=http://192.168.122.1:8000/repomirror/repo --ref=fedora/26/${basearch}/atomic-host`

**Comment by dustymabe** [comment]
LGTM

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by cgwalters** [comment]
http://jenkins.install.bos.redhat.com/job/anaconda-f27-mock-PR/179/ ➡️ http://jenkins.install.bos.redhat.com/job/anaconda-f27-mock-PR/179/artifact/result/tests/nosetests.log ➡️ 

> AssertionError: <pyanaconda.kickstart.RepoData object at 0x7fe29d565e80> is not an instance of <class 'pykickstart.commands.repo.F27_RepoData'>

which looks unrelated to this?

**Comment by rvykydal** [comment]
Yes it is unrelated, it is pykickstart and anaconda builds not being in sync.

**Comment by dustymabe** [comment]
> Yes it is unrelated, it is pykickstart and anaconda builds not being in sync.

so can we merge? or do we need to wait for that to be fixed?

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
@dustymabe 
Can this go to F27 (is rpm-ostree related change there)? Or was it intended just for master.

**Comment by dustymabe** [comment]
> Can this go to F27 (is rpm-ostree related change there)? Or was it intended just for master.

Definitely would like to see this in F27 as well.

**Pull request merged**
