### PR TITLE
Master kexec reboot

### PR DESCRIPTION
**Pull request by bcl**
This implements rebooting into the new system using kexec to speed things up.
Also depends on new pykickstart with reboot --kexec

### CODE REVIEW

**Comment by cgwalters** [comment]
I don't think this is a good idea.  kexec is OK for kdump where the goal is just to get data off the machine, but this will be introducing a scenario where only the initial install -> first boot is via kexec, but since it's not the default otherwise, it will be very rarely tested.

If you search the intertubes there are various references to kexec-induced issues (e.g. https://bugs.launchpad.net/diskimage-builder/+bug/1240933 )

**Comment by bcl** [comment]
That's why it is optional. FYI this is related to rhbz#1207747

**Comment by vpodzime** [comment]
Other than the minor comments above this looks good to me.

**Comment by bcl** [comment]
Pushed. This will be in Fedora23

**Pull request closed without merging**
