### PR TITLE
network: guard team devices configuration in kickstart by capabilities

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Comment by rvykydal** [comment]
/kickstart-test --testtype network --skip-testtypes gh576,gh595,gh640,gh641,gh680,gh740,gh769,gh774,gh777,gh910,gh890,gh871,rhbz1853668,gh975,gh1023,gh1060

**Comment by rvykydal** [comment]
/kickstart-test --testtype network --skip-testtypes gh576,gh595,gh640,gh641,gh680,gh740,gh769,gh774,gh777,gh910,gh890,gh871,rhbz1853668,gh975,gh1023,gh1060

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Pull request merged**
