### PR TITLE
Bump codecov/codecov-action from 1 to 2 (#infra)

### PR DESCRIPTION
**Pull request by poncovka**
Bumps the version of `codecov/codecov-action` to the latest one.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well.

**Review by jkonecny12 — APPROVED** [review]
Looks great to me. Just wonder if we want to support also RHEL branches here?

**Comment by poncovka** [comment]
The tests have failed (https://github.com/poncovka/anaconda/pull/2/checks?check_run_id=3171966197). Blocked for now.

**Comment by poncovka** [comment]
It seems to work now: https://github.com/poncovka/anaconda/runs/3350881138?check_suite_focus=true

**Review by VladimirSlavik — APPROVED** [review]
Still LGTM!

**Pull request merged**
