### PR TITLE
Move post installation scripts to the end of queue

### PR DESCRIPTION
**Pull request by poncovka**
(cherry-picked from a commit 20001b6)

Resolves: rhbz#1983922

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by jkonecny12** [comment]
Probably should be asked on the original PR, but shouldn't we have tests for this code?

**Comment by poncovka** [comment]
> Probably should be asked on the original PR, but shouldn't we have tests for this code?

I don't think it is worth it at this point. These tasks should be scheduled dynamically in the future, so this implementation will disappear.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by jstodola** [comment]
> > Probably should be asked on the original PR, but shouldn't we have tests for this code?
> 
> I don't think it is worth it at this point. These tasks should be scheduled dynamically in the future, so this implementation will disappear.

The last sentence actually sounds like 2 reasons for having this covered by a test. Even if this implementation will disappear, the functionality should be the same from the customer point of view. "Scheduled dynamically" sounds like a source of unpredictable problems for a QE person...

**Comment by VladimirSlavik** [comment]
+1 on tests not worth it. What is there to test? Order of tasks in the queue? Their existence in it?

**Comment by jstodola** [comment]
Based on bug 1983922, a kickstart-tests test could test that /root/anaconda-ks.cfg exists when kickstart %post scripts are executed and the file is not empty.

**Comment by jkonecny12** [comment]
In that case maybe we want to cover this by KS tests not by unit tests. Unit tests are more focused on implementation.

**Comment by VladimirSlavik** [comment]
Unit tests could test check the task is in the queue. Kickstart tests could check that `anaconda-ks.cfg` exists, true, but it's such a generic thing that maybe all of them should. Or there could be some special test to check the common things, or perhaps the coverage ones...

**Pull request merged**
