### PR TITLE
Add the generate_driver_disk_repositories function

### PR DESCRIPTION
**Pull request by poncovka**
Move the code for generating driver disk repositories to a separate function.

**Based on:** https://github.com/rhinstaller/anaconda/pull/3837

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks great to me. Thanks!

**Comment by jkonecny12** [comment]
There are some pylint errors which needs to be resolved first.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Pull request merged**
