### PR TITLE
tests: ruff: enforce UP032 (f-string) rule

### PR DESCRIPTION
**Pull request by KKoukiou**
TODO: 
* [X] Either fix https://github.com/rhinstaller/pocketlint/issues/51
* [x] DONE: Or revert the f-string changes on the set_markup
* [X] Or disable pylint markup checks on the affected lines
* [ ] Check if this somehow affecting the translations (I am not able to test that, the generated boot.iso does not have po files inside I think)

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
@vojtechtrefny do you know if there is any reason to not do this?

**Comment by jkonecny12** [comment]
This change is against Code conventions set by the team: https://anaconda-installer.readthedocs.io/en/latest/contributing.html#code-conventions

```
Format strings with [.format()](https://docs.python.org/3/library/stdtypes.html#str.format) instead of % (https://pyformat.info/)
Exception: Use % formatting in logging functions and pass the % as arguments. See [logging format interpolation](https://stackoverflow.com/questions/34619790/pylint-message-logging-format-interpolation) for the reasons.
```

Reason we went with this was that we did not wanted to mixup f-strings with format and format is not able to cover all the cases. We can definitely reconsider this solution again but I'm marking this as blocked as it's against the current code conventions we have set.

**Comment by KKoukiou** [comment]
> This change is against Code conventions set by the team: https://anaconda-installer.readthedocs.io/en/latest/contributing.html#code-conventions
> 
> ```
> Format strings with [.format()](https://docs.python.org/3/library/stdtypes.html#str.format) instead of % (https://pyformat.info/)
> Exception: Use % formatting in logging functions and pass the % as arguments. See [logging format interpolation](https://stackoverflow.com/questions/34619790/pylint-message-logging-format-interpolation) for the reasons.
> ```
> 
> Reason we went with this was that we did not wanted to mixup f-strings with format and format is not able to cover all the cases. We can definitely reconsider this solution again but I'm marking this as blocked as it's against the current code conventions we have set.

As I mentioned in the past as well, this file is read by noone, it's not enforced actively and only the ultra old team members might be able to refer to it like you did now.
The way to go forward it to enfore rules through linters (pylint, ruff etc) and keep the configuration files for these as the single source of truth. 

So, on the decision for fstrings - I actually think it's the way to go, the only place it does not apply is the pango templates, because of the custom pocketlint checks, which are not covering fstrings (see commit message)

Otherwise, we should really be able to delete the conventions file.

**Comment by KKoukiou** [comment]
@jkonecny12 which cases does fstrings does not cover?

**Comment by jkonecny12** [comment]
Ahh, my memory is failing here. IIRC f-strings can't be modified before you will mark them as `f` which is causing troubles for example with localization strings.

**Comment by KKoukiou** [comment]
> Ahh, my memory is failing here. IIRC f-strings can't be modified before you will mark them as `f` which is causing troubles for example with localization strings.

Can you elaborate here a bit more?

**Comment by KKoukiou** [comment]
https://issues.redhat.com/browse/INSTALLER-3989

**Pull request closed without merging**
