### PR TITLE
Disable ELN containers (#infra)

### PR DESCRIPTION
**Pull request by VladimirSlavik**
~~ELN is too disorderly at the moment.~~

This does not prevent building the containers locally, just turns off building them daily and failing.every.single.time.

### CODE REVIEW

**Review by poncovka — APPROVED** [review]

**Comment by sgallagher** [comment]
FWIW, the container builds were fixed yesterday.

**Comment by VladimirSlavik** [comment]
So, after #4196 was merged, ELN containers build, but they don't pass the subsequent tests, because:
- Unit tests run also `pylint` which is broken due to `dill` not working on Python 3.11. These are patched in Rawhide, but don't appear in ELN.
- RPM tests blindly install `anaconda*`, which includes `anaconda-live`, which is not considered in ELN content resolver inputs. It's an open question if it should be included too or not. What that means is that `xisxwayland` is not pulled into ELN, but we don't special-case the tests for that, only the container.

If we don't want to merge this, we need to come up with some resolution to the issues above.

I considered separating the container builds into a reusable workflow and running one job with a matrix for Fedora and another for ELN, but GH actions still does not support calling reusable workflows within a matrix/strategy.

**Comment by VladimirSlavik** [comment]
With #4248, we will be able to split off ELN builds to a separate workflow and have a separate status for that. That would make this change unnecessary.

**Comment by VladimirSlavik** [comment]
With #4254, we will also be able to reduce the friction surface for RHEL and ELN.

I think this is no longer needed.

**Pull request closed without merging**
