### PR TITLE
Update versions of the kickstart commands

### PR DESCRIPTION
**Pull request by poncovka**
Some of the commands or their options were removed or deprecated.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Thanks! Builds aren't up yet, though :(

**Comment by poncovka** [comment]
> Thanks! Builds aren't up yet, though :(

Rawhide is not, but ELN unit tests started to fail on other pull requests.

**Comment by poncovka** [comment]
The tests pass locally.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by jkonecny12** [comment]
The `master` test won't work here because it's running in the old container with the old pykickstart. However, the new container is not build because it has broken test (fixed by this PR). So let's merge this and build new container to solve the issue.
Tested locally on newly build container works correctly.

**Pull request merged**
