### PR TITLE
TEST: Try to capture internal runner

### PR DESCRIPTION
**Pull request by martinpitt**
Don't land this! :-) We want to see what happens, in the context of PR #2933.

### CODE REVIEW

**Comment by martinpitt** [comment]
So this *did* run on the internal runner, which is not that nice. It's heavily guarded, but not quite what we expected. Let's get in #2932 and try this again.

**Comment by jkonecny12** [comment]
Heh, interesting what could be done by an easy PR.

**Comment by martinpitt** [comment]
#2933 landed, re-running.

**Comment by martinpitt** [comment]
@jkonecny12 : That now went as intended, it runs the workflow from master.  *phew*

**Pull request closed without merging**
