### PR TITLE
Cherry-pick PR 5297 content from Fedora-39 branch

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
This needs to be tested with the Web UI

**Comment by VladimirSlavik** [comment]
What's the testing that it needs? Is it something that's now available?

**Comment by KKoukiou** [comment]
> What's the testing that it needs? Is it something that's now available?

we dont have automation for live images, so that needs to  be tested manually.

**Comment by VladimirSlavik** [comment]
Oh :(

**Comment by KKoukiou** [comment]
Something wrong with RPM builds here. Closing and reopening for COPR from packit to be recreated.

**Pull request closed without merging**
