### PR TITLE
Add basic support for LVM cache creation in kickstart

### PR DESCRIPTION
**Pull request by vpodzime**
If user specifies we should create an LV as a cached LV, we need to transform
the parameters in to a CacheRequest instance and pass it to blivet to create a
new LV as cached.

This PR requires the [blivet's PR #190] (https://github.com/rhinstaller/blivet/pull/190) to be merged first and the appropriate bump of the required version of blivet will be done before this gets pushed.

### CODE REVIEW

**Comment by jkonecny12** [comment]
Looks good to me

**Comment by vpodzime** [comment]
A slightly modified version that passes devices (PVs) instead of just their names to blivet.

**Comment by bcl** [comment]
Looks good.

**Comment by vpodzime** [comment]
Pushed.

**Pull request closed without merging**
