### PR TITLE
Bond no default wired connection r9

### PR DESCRIPTION
**Pull request by rvykydal**
Upstream PR: https://github.com/rhinstaller/anaconda/pull/5703. This PR differs only in terminology (slaves/ports)

### CODE REVIEW

**Comment by rvykydal** [comment]
Waiting for planning into RHEL 9 release.

**Comment by rvykydal** [comment]
> Waiting for planning into RHEL 9 release.

Planned for rhel 9.6

**Comment by rvykydal** [comment]
> > Waiting for planning into RHEL 9 release.
> 
> Planned for rhel 9.6

So 9.5.

**Review by M4rtinK — APPROVED** [review]
Looking good. :)

**Review by jkonecny12 — APPROVED** [review]

**Pull request merged**
