### PR TITLE
infra: packit: get version from specfile

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

**Comment by jkonecny12** [comment]
Looks great to me. Thanks for the improvement.

**Review by jkonecny12 — APPROVED** [review]

**Review by vojtechtrefny — APPROVED** [review]

**Review by KKoukiou — COMMENTED** [review]
This  won't work as the anaconda.spec is generated on build time.

**Review by KKoukiou — COMMENTED** [review]
This was meant to be a workaround for https://github.com/packit/packit/issues/2184 but it's not possible as the anaconda.spec is generated at build time from the template file.

**Pull request closed without merging**
