### PR TITLE
Only use <> for markup (#1317297)

### PR DESCRIPTION
**Pull request by bcl**
Zanata error checking gets confused when a string looks like markup but
isn't. So convert <Enter> to [Enter] and change several other uses to
UPPER CASE.

### CODE REVIEW

**Comment by jkonecny12** [comment]
Looks good to me.

**Comment by bcl** [comment]
This now passes the tests.

**Comment by jkonecny12** [comment]
Looks good to me again :) .

**Comment by bcl** [comment]
Pushed.

**Pull request closed without merging**
