### PR TITLE
webui: port review screen confirmation from checkbox to modal dialog

### PR DESCRIPTION
**Pull request by KKoukiou**
Screen Shot 2022-04-04 at 10 41 34

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Review by VladimirSlavik — COMMENTED** [review]
Do I understand correctly that...

If the current screen is `review-configuration`, there is no going forward on button press, instead `NextWaitConfirmation` is changed to `True`, and the state change triggers a re-build (?) of the whole page, this time resolving the part `nextWaitsConfirmation && <ReviewConfigurationConfirmModal` to the modal, so it shows over the review, and then the callback from that moves the wizard forward a page?

(The part where things are triggered "passively" / "remotely" by state changes is still pretty alien to me.)

**Comment by KKoukiou** [comment]
> Do I understand correctly that...
> 
> If the current screen is `review-configuration`, there is no going forward on button press, instead `NextWaitConfirmation` is changed to `True`, and the state change triggers a re-build (?) of the whole page, this time resolving the part `nextWaitsConfirmation && <ReviewConfigurationConfirmModal` to the modal, so it shows over the review, and then the callback from that moves the wizard forward a page?
> 
> (The part where things are triggered "passively" / "remotely" by state changes is still pretty alien to me.)

Everything what you describe here is exactly what happens, just one small inaccuracy.
When the state variable gets updated (nextWaitsConfirmation), just the part of the page that's rendered from that component , in this case Footer component, and its chldren get's refreshed.  *not* the whole page.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
