### PR TITLE
Port NVMe over fabrics GUI to Fedora

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This ports #4423 to Fedora. See pictures there.

TODOs:
- [x] readiness lower on the stack - blivet etc.
- [ ] manual testing
- [x] release notes

Most of the work by @poncovka. Looks like cherry-picking amended commits hides the other author :(

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
> @vojtechtrefny do you have any idea about when the nvme fabrics code in blivet wold be upstream too?

We plan to release new version of blivet in Fedora 38 -- blivet 3.7.0 and it will contain all the nvme changes that are available in RHEL, but we don't plan to release the libblockdev NVMe plugin until Fedora 39 (or possibly 40). The blivet code will work, but the additional information about the NVMe drives supplied by libblockdev won't.

**Comment by VladimirSlavik** [comment]
In other words, this will have to wait, correct?

**Comment by vojtechtrefny** [comment]
> In other words, this will have to wait, correct?

Yes and no. Without the libblockdev plugin Blivet will report NVMe oF devices as "normal" NVMe devices. So the Anaconda support for NVMe oF won't work, but it also won't crash (if the blivet part is written correctly :-)). But it definitely has to wait for Blivet 3.7.0 release where the `NVMeFabricsNamespaceDevice` and other classes will be available.

**Comment by VladimirSlavik** [comment]
Looks like blivet is in place now. Rebased.

**Review by poncovka — APPROVED** [review]
Thank you!

**Comment by VladimirSlavik** [comment]
Blocked by the manual testing requirement.

**Comment by VladimirSlavik** [comment]
Rebased.

**Comment by VladimirSlavik** [comment]
Updates image: [master_updates.img.gz](https://github.com/rhinstaller/anaconda/files/11325287/master_updates.img.gz)

**Comment by AdamWill** [comment]
https://fedorapeople.org/groups/qa/anaconda-nvme-fabric-01.iso is an ISO with the PR included, for testing.

**Comment by skycastlelily** [comment]
Hi Vladimir,
I tested with the latest updates image:https://github.com/rhinstaller/anaconda/files/11325287/master_updates.img.gz,
the installation halted at "[  OK  ] Finished dracut-pre-pivot.…dracut pre-pivot and cleanup hook."( I added loglevel=7,but failed to get more information)
Actually the installation halts there even without that updates image added.
On non-nvme-of servers ,with that updates , you will see nvme fabric devices choose is added.
I didn't get  time to test this pr before your last rebase,but the above symptoms sound just like you described in the email before the last pr.
I checked the updates image,it dose contain the latest files.
So,you sure the latest pr works?Or,did  I miss anything here?
I'm gonna to email you the following beaker jobs to see if you could find some might useful information.
1.successful fedora installation on non-nvme-of servers with the updates added
2.failed fedora installation on nvme-of server with the updates added
3.successful rhel installation on that nvme-of server

**Comment by AdamWill** [comment]
@skycastlelily can you test with my ISO instead? it's possible the changes here are the kind that can't really be tested with an updates image (this does happen sometimes; usually if the change needs to happen *before* the update overlay process kicks in).

**Comment by skycastlelily** [comment]
> can you test with my ISO instead?
I'm afraid I'm not able to use  that iso on beaker servers.

@VladimirSlavik  Did you use Adam's iso to perform the test?If so,would you please tell me how ?Thanks.

**Comment by VladimirSlavik** [comment]
No, I used update images.

**Comment by skycastlelily** [comment]
> No, I used update images.

Then,would you please points out the different place of my job  from yours or would you please tell me how you perform the test?Thanks

**Comment by VladimirSlavik** [comment]
Ah, sorry, there is a misunderstanding. Your description of the failure sounds the same as what happened when I tried this: The machine simply failed to boot.

I did not look at the beaker jobs in email, yet.

I will check also which machine you got loaned - if it is the same as I had, then it might be worth checking if there's a different machine to use.

**Comment by skycastlelily** [comment]
Er,my apologize,it feels like that this pr is going to be merged in any minute when I opened this page today,
and that's the reason why I comment here: to highlight that this pr is not ready to be merged.
I don't think it's the nvme-of server's  problem,as rhel installation works fine,I think you may need to modify more code.
But just in case,the nvme-of server I loaded is st14, please feel free to load another one if you used the same or tell me if you want me to check.

**Comment by VladimirSlavik** [comment]
@vojtechtrefny I suppose this is still stuck?

**Comment by vojtechtrefny** [comment]
> @vojtechtrefny I suppose this is still stuck?

Yes. I mean it can be merged, just not tested. We plan to build the new version of libblockdev for Fedora next week.

**Comment by VladimirSlavik** [comment]
I guess it's fine to wait just a bit more :-)

**Comment by VladimirSlavik** [comment]
- We're in rawhide one fedora later and all the parts should be in place.
- Waiting for storage to help testing.
- Will rebase.

**Comment by AdamWill** [comment]
So, do you want @skycastlelily to try this again with an updates image?

**Comment by VladimirSlavik** [comment]
I'm told @tbzatek will manage that, somehow.

**Comment by tbzatek** [comment]
> I'm told @tbzatek will manage that, somehow.

Right,  I'm going to test this but first we have a couple of dracut changes to get in.

**Comment by tbzatek** [comment]
Needs #5328

**Comment by vojtechtrefny** [comment]
I've rebased this to the latest master and did some manual testing with @tbzatek so I think this is ready to be merged now.

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Comment by VladimirSlavik** [comment]
Thank you for testing and finishing this!

**Pull request merged**
