### PR TITLE
Allow arch filtering for comps

### PR DESCRIPTION
**Pull request by j-mracek**

### CODE REVIEW

**Comment by jkonecny12** [comment]
This is related to [bug 1555134](https://bugzilla.redhat.com/show_bug.cgi?id=1555134).

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
Hello @j-mracek we finally (thanks to @poncovka) are getting to your lost PR. Could you please rebase it on top and solve the conflict. I'll do sanity checking then.

Thanks a lot and sorry for so long delay.

**Comment by j-mracek** [comment]
@jkonecny12 Rebased

**Pull request merged**
