### PR TITLE
Disable NM autoconnections in Anaconda

### PR DESCRIPTION
**Pull request by rvykydal**
The NM autoconnections (automatic network connection via dhcp) used to
be disabled via lorax. Let's move it into anaconda so we have
better control over it depending on the use case, eg by adding:

ConditionKernelCommandLine=|ip
ConditionKernelCommandLine=|inst.ks

Resolves: rhbz#TODO

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]
Looks great to me!

**Comment by rvykydal** [comment]
PR with port to Fedora: https://github.com/rhinstaller/anaconda/pull/3950

**Pull request merged**
