### PR TITLE
Set hostname also from ip= static configuration without device (#1988…

### PR DESCRIPTION
**Pull request by rvykydal**
…521)

See the comment in added test case for details

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Comment by rvykydal** [comment]
@jstodola - do you think the idea is ok?

**Review by jstodola — APPROVED** [review]
It makes sense to support this in anaconda. `nm-initrd-generator` is also able to parse the hostname from such an argument:
```
[jstodola@localhost ~]$ /usr/libexec/nm-initrd-generator -s ip=10.34.102.244::10.34.102.54:255.255.255.0:myhostname:

*** Hostname 'myhostname' ***

*** Connection 'default_connection' ***

[connection]
id=Wired Connection
uuid=a7dfe6dc-6a3f-481a-adea-d7c35989e975
type=ethernet
autoconnect-retries=1
multi-connect=1
permissions=

[ethernet]
mac-address-blacklist=

[ipv4]
address1=10.34.102.244/24,10.34.102.54
dhcp-hostname=myhostname
dhcp-timeout=90
dns-search=
may-fail=false
method=manual

[ipv6]
addr-gen-mode=eui64
dhcp-hostname=myhostname
dhcp-timeout=90
dns-search=
method=auto

[proxy]
[jstodola@localhost ~]$
```

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Pull request merged**
