### PR TITLE
Add support for chrony pool directive

### PR DESCRIPTION
**Pull request by mlichvar**
With chrony-2.0 it is possible to specify a pool of NTP servers instead
of individual servers. It selects four servers from the addresses that
the pool name is resolved to and replaces them automatically when they
are unreachable or falsetickers. This is now used in the default Fedora
chrony configuration.

To avoid extending the ntp API and the date time spoke, pools are simply
presented as four separate servers with the same name.

Resolves: rhbz#1193389

### CODE REVIEW

**Comment by vpodzime** [comment]
This looks good to me, although I think it needs some additional work from the UX perspective as if I understand it correctly now the NTP servers configuration dialog will now show the same item 4 times without any clear explanation why. I think we need to change the look of the dialog to distinguish servers from pools and do the same elsewhere. But as I said, this is definitely a good starting point. Thanks for the patch!

**Comment by bcl** [comment]
I don't think I understand how this is supposed to work. It reads servers from the config and multiplies pool entries by 4. And then when rewriting the config it multiplies each server, whether or not it is a pool server, by 4? Maybe some examples of what the config should look like in the case of pool vs. individual vs. mixed pool+individual servers.

**Comment by vpodzime** [comment]
> I don't think I understand how this is supposed to work. It reads servers from the config and multiplies pool entries by 4. And then when rewriting the config it multiplies each server, whether or not it is a pool server, by 4? Maybe some examples of what the config should look like in the case of pool vs. individual vs. mixed pool+individual servers.

If I understand the code changes correctly, this implements the support for chrony's NTP pools by interpreting pools as quadruples of servers. So instead of ``[0-4].pool.ntp.org`` anaconda would show the ``pool.ntp.org`` URL four times in the UI and write it as ``pool pool.ntp.org`` to the config. IOW, every pool instance from the config is replaced by four servers with the same URL on reading the config and vice versa when writing it out.

**Comment by mlichvar** [comment]
> I don't think I understand how this is supposed to work. It reads servers from the config and multiplies pool entries by 4. And then when rewriting the config it multiplies each server, whether or not it is a pool server, by 4? Maybe some examples of what the config should look like in the case of pool vs. individual vs. mixed pool+individual servers.

The default chrony config used to have:

server 0.fedora.pool.ntp.org iburst
server 1.fedora.pool.ntp.org iburst
server 2.fedora.pool.ntp.org iburst
server 3.fedora.pool.ntp.org iburst

Now it's just:
pool 2.fedora.pool.ntp.org iburst

The "2." name is used because it's currently the only one providing
IPv6 addreses. That will likely change in the future.

With the patch the user will see there are still four servers used
for synchronization and will hopefully not be tempted to add more.

**Comment by bcl** [comment]
Ah, ok, thanks for the explanation. How about when someone uses their own ntp infrastructure? Is 4 a standard grouping for pool?

**Comment by mlichvar** [comment]
On Mon, Apr 20, 2015 at 10:17:35AM -0700, Brian C. Lane wrote:
> Ah, ok, thanks for the explanation. How about when someone uses their own ntp infrastructure? Is 4 a standard grouping for pool? 

Four is the maximum number of servers chronyd will use from one pool by
default. If the name resolves to fewer addreses than four, it will use
only that many.

The patch was meant as something quick and simple before F22 is
released. Ideally, the pool/server selection would use a checkbox in
the server list dialog.

**Comment by clumens** [comment]
I'd really like to see finished UI before merging this in, because what's going to happen is very shortly after merging this in its current state we are going to get bug reports about how we are duplicating server names.

**Comment by vpodzime** [comment]
I think I can do the UI part today or tomorrow (hopefully I still remember how the NTP server UI works). My only concern is kickstart, where ``--ntpservers`` is unfortunately an option of the ``timezone`` command and can hardly be extended to support pools somehow -- ideas are more than welcome!

**Comment by mlichvar** [comment]
> I'd really like to see finished UI before merging this in, because what's going to happen is very shortly after merging this in its current state we are going to get bug reports about how we are duplicating server names.

FWIW, duplicated server lines is a valid configuration. For example

server 2.fedora.pool.ntp.org iburst
server 2.fedora.pool.ntp.org iburst
server 2.fedora.pool.ntp.org iburst
server 2.fedora.pool.ntp.org iburst

is functionally quite close to

pool 2.fedora.pool.ntp.org iburst

The only difference is that with the former the servers will not be
replaced automatically when unreachable/falseticker.

**Comment by vpodzime** [comment]
Are you guys okay with something like this?

NTP serves/pools configuration

**Comment by bcl** [comment]
How do you remove one?

**Comment by vpodzime** [comment]
> How do you remove one?

Same as before -- uncheck the "Use" checkbox.

**Comment by clumens** [comment]
(1) Is it expected that the user will want to toggle the pool setting after adding a new server, or on one that anaconda adds automatically?

(2) This is just a general comment on the entire dialog, not just what you've added here.  Does the word "pool" in this context mean anything to the user?  We don't really explain it anywhere, except perhaps maybe in the help which you cannot reach from this dialog.

**Comment by vpodzime** [comment]
> (1) Is it expected that the user will want to toggle the pool setting after adding a new server, or on one that anaconda adds automatically?

Likely for a manually added servers/pools, unlikely for automatically added ones.

> (2) This is just a general comment on the entire dialog, not just what you've added here. Does the word "pool" in this context mean anything to the user? We don't really explain it anywhere, except perhaps maybe in the help which you cannot reach from this dialog.

I think it should be clear to people who enter the dialog and want to do any changes there. No stats, of course, but I think, hardly ever anybody changes the NTP server configuration maybe except for people who know they are in a network blocking some servers and providing others. But even that is usually resolved by DHCP. Having said that, I'm not entirely against completely removing the dialog, but that could lead us to troubles with NTP turned ON  but not syncing and no indication of what's going wrong and no way how to fix it.

**Comment by clumens** [comment]
Oh I wasn't suggesting we just get rid of the dialog.  I had just noticed a couple potential UI problems and wanted to make sure we had a discussion about them, and perhaps came up with some fixes if they were in fact problems.  But it sounds like things are okay.

**Comment by vpodzime** [comment]
Added the commit that adds the GUI changes as shown by [the preview above] (https://github.com/rhinstaller/anaconda/pull/75#issuecomment-94861529)

**Comment by vpodzime** [comment]
Pushed to master. Waiting for [rhbz#1193389] (https://bugzilla.redhat.com/show_bug.cgi?id=1193389) to be accepted as F22 blocker so that I can cherry-pick the changes also to the f22-branch.

**Pull request closed without merging**
