### PR TITLE
Map Anaconda exceptions to org.fedoraproject.Anaconda.Error 

### PR DESCRIPTION
**Pull request by poncovka**
Add a rule that will map unknown exceptions raised in Anaconda modules
to the `org.fedoraproject.Anaconda.Error` DBus error name.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by poncovka** [comment]
The pixel tests are fixed.

**Pull request merged**
