### PR TITLE
Make it possible to run ./anaconda from git

### PR DESCRIPTION
**Pull request by atodorov**
Several minor fixes which make it possible to execute ./anaconda from the git checkout without having anaconda RPMs installed on the system. This is strictly for testing purposes. I intend to refactor the Dogtail tests to use `anaconda --image` instead of a VM. 

If you want to play with it you have to add something like this in Makefile.am:

```
runanaconda:
       ANACONDA_DATA=$(abs_srcdir)/data \
       ANACONDA_WIDGETS_OVERRIDES=$(abs_srcdir)/widgets/python \
       ANACONDA_WIDGETS_DATA=$(abs_srcdir)/widgets/data \
       ANACONDA_INSTALL_CLASSES=$(abs_srcdir)/pyanaconda/installclasses \
       PYTHONPATH=$(abs_srcdir):$(abs_builddir)/pyanaconda/isys/.libs:$(abs_srcdir)/widgets/python/:$(abs_builddir)/widgets/src/.libs/ \
       LD_LIBRARY_PATH=$(abs_builddir)/widgets/src/.libs \
       UIPATH=$(abs_srcdir)/pyanaconda/ui/gui/ \
       GI_TYPELIB_PATH=$(abs_builddir)/widgets/src/ \
       GLADE_CATALOG_SEARCH_PATH=$(abs_srcdir)/widgets/glade \
       GLADE_MODULE_SEARCH_PATH=$(abs_builddir)/widgets/src/.libs \
       $(abs_srcdir)/anaconda -G --dirinstall /var/tmp/anaconda-install/
```

### CODE REVIEW

**Comment by clumens** [comment]
Have you tested running anaconda normally, with these patches in an updates image, to verify that still works?

**Comment by vpodzime** [comment]
Otherwise this looks good to me as long as it doesn't break anaconda run in the usual way.

**Comment by atodorov** [comment]
> Have you tested running anaconda normally, with these patches in an updates image, to verify that still works?

Not yet. I will try to test it tomorrow.

**Comment by atodorov** [comment]
@clumens - I've tested an updates.img with these commits against anaconda-24.5-1. I didn't see any issues with the regular installation. IMO this is safe to merge.

**Comment by clumens** [comment]
Merged, thanks.

**Pull request closed without merging**
