### PR TITLE
The RPM tooling generates the compiled python so having automake do it is redundant

### PR DESCRIPTION
**Pull request by KKoukiou**
Resolves: rhbz#2275279

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me - thanks for looking into this! :)

**Comment by allisonkarlitskaya** [comment]
try:

```make
dist_xxx_DATA = $(wildcard $(srcdir)/*.py)
```

...and probably update the spec to exclude the `__pycache__` dirs, since they're not created anymore (ie: exactly the point of this PR).

**Comment by jkonecny12** [comment]
The issue is that COPR doesn't support RHEL and we are building RHEL-10 ISOs here -- so again we are messing together CentOS Stream and RHEL packages.

Also this whole build is done in the CentOS Stream container which is not correct.

**Comment by hroncok** [comment]
```
$ rpm -qlp anaconda-core-41.10-1.20240417102806998567.pr5574.2.g95917b4095.fc41.x86_64.rpm | grep 'pyc$' | sort | wc -l
942

$ diff -u <(repoquery -q --repo=rawhide -l anaconda-core | grep 'pyc$' | sort) <(rpm -qlp anaconda-core-41.10-1.20240417102806998567.pr5574.2.g95917b4095.fc41.x86_64.rpm | grep 'pyc$' | sort)
```

:tada:

**Pull request merged**
