### PR TITLE
RHEL-9: sync files

### PR DESCRIPTION
**Pull request by jkonecny12**
Sync files from `master`.

- Makefile.am and related
- ISO management scripts
- CONTRIBUTION guide
- Jinja templated files

### CODE REVIEW

**Review by KKoukiou — APPROVED** [review]

**Review by KKoukiou — COMMENTED** [review]
this commit will break the release, as it does not have RHEL ticket and it's not infra.

**Comment by jkonecny12** [comment]
Updated the commit message to add `infra:`.

**Comment by jkonecny12** [comment]
Hi @jstodola I'm requesting your review because of infra check. It failed on:
```
.branch-variables.yml is not part of the infrastructure
CONTRIBUTING.rst is not part of the infrastructure
Makefile.am is not part of the infrastructure
```
which is expected.

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Review by jstodola — APPROVED** [review]

**Pull request merged**
