### PR TITLE
Fix line spacing

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This fixes [hopefully most of] line spacing according to the style naggers, outside modules directory.

(Modules available too, waiting on #2284)

Clarification: The blank lines checking is provided by pycodestyle (pep8), not pylint. The messages fixed are of the C3** "blank line" class (type?).

### CODE REVIEW

**Comment by poncovka** [comment]
@jkonecny12, it looks like me might be able to enable checks for the line spacing in the pylint configuration file after we merge this PR.

**Comment by VladimirSlavik** [comment]
Clarification: The blank lines checking is provided by `pycodestyle` (`pep8`), not `pylint`. The messages fixed are of the `C3**` "blank line" class (type?).

**Comment by jkonecny12** [comment]
I think it's this one:
```
:trailing-newlines (C0305): *Trailing newlines*
  Used when there are trailing blank lines in a file.
```

It has already a task for the disable C messages.

**Comment by VladimirSlavik** [comment]
Oops. I closed the old branches and these that didn't fit the "fix_*" naming scheme. Turns out the PR was based on the wrong branch.

**Comment by VladimirSlavik** [comment]
Sorry, deleted the wrong branch apparently :(

**Comment by VladimirSlavik** [comment]
Jenkins, please test this.

**Pull request merged**
