### PR TITLE
infra: Run unit and rpm tests daily/nightly

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This should help as an additional data source to diagnose issues when things "randomly fail everywhere". Tests running here are not affected by any changes. See comments for more details.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Successful run: https://github.com/VladimirSlavik/anaconda/actions/runs/4993975869

**Review by M4rtinK — APPROVED** [review]
Looks good to me & should be really helpful longer term. :)

**Review by rvykydal — APPROVED** [review]
Thank you.

**Pull request merged**
