### PR TITLE
Use new tags for skipping tests on specific products (#infra)

### PR DESCRIPTION
**Pull request by poncovka**
Use `skip-on-fedora`, `skip-on-rhel`, `skip-on-rhel-8` and `skip-on-rhel-9`.

**Depends on:** https://github.com/rhinstaller/kickstart-tests/pull/547

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by jkonecny12 — APPROVED** [review]
Looks great to me. Thanks!

**Pull request merged**
