### PR TITLE
Use dictionaries is thread-safe manner.

### PR DESCRIPTION
**Pull request by dashea**
This language sucks.

### CODE REVIEW

**Comment by AdamWill** [comment]
At least it ain't perl.

I hit this too and filed a bug: https://bugzilla.redhat.com/show_bug.cgi?id=1245779

**Comment by clumens** [comment]
I hit this quite a lot in kickstart_tests.  Glad to see it go.

**Comment by vpodzime** [comment]
This is so stupid that at the first glance I started thinking about our own ``SafeDict`` class providing some sane behaviour for iteration. Fortunately it's not that many places as I was afraid it would be and we can keep this in mind when doing review of future changes. So ACK from me too.

**Comment by dashea** [comment]
Pushed.

**Pull request closed without merging**
