### PR TITLE
Backport known external repos

### PR DESCRIPTION
**Pull request by jcpunk**
This PR backports the newly added known-external-repos code to the RHEL8 anaconda.

### CODE REVIEW

**Comment by jcpunk** [comment]
Any chance to label this for rhel-devel?

**Comment by jkonecny12** [comment]
Please rebase this on `rhel-devel` branch?

**Comment by jkonecny12** [comment]
And I have a feeling that this functionality is already there.

**Comment by jcpunk** [comment]
It does appear to be in there now.  No need for this PR

**Pull request closed without merging**
