### PR TITLE
F38 enable ostree containers

### PR DESCRIPTION
**Pull request by jkonecny12**
Backport of https://github.com/rhinstaller/anaconda/pull/4561

### CODE REVIEW

**Comment by jkonecny12** [comment]
Fixed typo in release notes and remove unused method.

**Comment by jkonecny12** [comment]
The unit test issue is not related to this PR:

```
where False = isinstance(<parse_kickstart_for_dracut_test.DracutNetwork object at 0x7fcfd9c3cc50>, <class 'pykickstart.commands.network.F38_Network'>)
```

Solved by https://github.com/pykickstart/pykickstart/pull/448

**Comment by jkonecny12** [comment]
Cockpit tests needs a new image with newer pykickstart 3.46. Similar to https://github.com/rhinstaller/anaconda/pull/4561#issuecomment-1474201777

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
