### PR TITLE
Update pixel tests broken from localization

### PR DESCRIPTION
**Pull request by jkonecny12**
The back button is now localized so we need to update the tests.

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
I am ok with the change but the commit message is wrong. It's the opposite happening. The back button used to be localized and now it's not.

**Review by KKoukiou — APPROVED** [review]

**Review by KKoukiou — COMMENTED** [review]
Actually pls fix the commit message - it's confusing.

**Review by KKoukiou — APPROVED** [review]

**Comment by jkonecny12** [comment]
Ahh, ok. Still getting used to the pixel tests, I understood it incorrectly.

**Pull request merged**
