### PR TITLE
Webui autopart wizard substeps

### PR DESCRIPTION
**Pull request by rvykydal**
In Anaconda Wizard I am trying to split installation-destination step into sub-steps but I am failing with "Uncaught TypeError: activeStep is undefined".

It occurs when going to the expandable step (installation-destination / "Installation destination") as >= second step, for example from the first screen (installation-language / "Welcome"): [Next] [Back] [Next] or [Next] [Next] [Back] (as the first step, ie [Next] from the welcome screen the problem does not occur).

```
Uncaught TypeError: activeStep is undefined
    WizardToggle WizardToggle.js:12
    React 16
        renderWithHooks
        updateFunctionComponent
        beginWork
        callCallback
        invokeGuardedCallbackDev
        invokeGuardedCallback
        beginWork$1
        performUnitOfWork
        workLoopSync
        renderRootSync
        performSyncWorkOnRoot
        flushSyncCallbacks
        ensureRootIsScheduled
        ensureRootIsScheduled
        scheduleUpdateOnFiber
        dispatchSetState
    update hooks.js:67
    c cockpit.js:1
    value cockpit.js:1
    <anonymous> cockpit.js:1
    cockpit cockpit.js:1
    <anonymous> cockpit.js:1
    <anonymous> cockpit.js:1
```
Seems to be failing here in the WizardToggle:
https://github.com/patternfly/patternfly-react/blob/1fc22acee0db6b2da1efc42f7a4caccaa7dfeb40/packages/react-core/src/components/Wizard/WizardToggle.tsx#L60

I also tried to add some other substeps for debugging in (https://github.com/rvykydal/anaconda/tree/webui-autopart-wizard-substeps-try-other-steps) and the same issue appears (after [Next], [Next]).

So this is a draft calling (as a JS / React / PF newbie) for help.

### CODE REVIEW

**Comment by rvykydal** [comment]
@KKoukiou Hey Katerina, do you have any hint? I must be missing something but I am not able to find out what.

**Review by KKoukiou — COMMENTED** [review]
The problem is the startAtStep property that you pass to the Wizard component. This does not count with the nested steps, and some indexing then goes wrong.

Either make the 'startAtStep' take in account the nested steps, or completely remove it, as this is not a valid user scenario to be able to start from the step other than the first.

**Comment by rvykydal** [comment]
Removing works for me, thank you!

**Comment by rvykydal** [comment]
Obsoleted by https://github.com/rhinstaller/anaconda/pull/4599

**Pull request closed without merging**
