### PR TITLE
Update translation canary to latest upstream version

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Includes all changes from translation-canary upstream as of https://github.com/rhinstaller/translation-canary/pull/5 or 4d4e65b89e140a20a6666cd5295dea2022a2bfa5 .

~~Differences in license text due to different breaking width are ignored.~~

Thanks @vojtechtrefny for bringing the changes all back together.

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks! :)

**Review by jkonecny12 — APPROVED** [review]
Thanks a lot for doing this! I wanted to do that :)

**Comment by vojtechtrefny** [comment]
I also did the update for blivet: https://github.com/storaged-project/blivet/pull/924 and I have a little more changes, I think the biggest difference is the license change from GPL to LGPL which I don't see here. I didn't do the "merge" manually but used git subtree:

```
git subtree pull --prefix translation-canary https://github.com/rhinstaller/translation-canary.git master --squash
```

**Comment by VladimirSlavik** [comment]
Thanks @vojtechtrefny, I did not realize the license change was also not synced yet. Instead of blind copy-paste, I cherry-picked the commits from upstream - just these that did not happen here already.

**Pull request merged**
