### PR TITLE
Support bond device activated in initramfs from kickstart

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1940919

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Thanks!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by VladimirSlavik** [comment]
This does not need porting?

**Comment by rvykydal** [comment]
> This does not need porting?

I should have mentioned it, it is port from Fedora

**Pull request merged**
