### PR TITLE
The underline character should not be displayed

### PR DESCRIPTION
**Pull request by jstodola**
Fix anaconda showing "1 _storage device selected" on the advanced storage spoke.

The call was accidentally? removed in 7b7616f546

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Thank you, looks good to me. However, it would be better to rebase this on f33-devel.

**Comment by jstodola** [comment]
uhh, that's wrong... will try next time

**Comment by VladimirSlavik** [comment]
No that is perfectly ok, as long as you change also the target  branch up there under the name...

**Comment by jstodola** [comment]
https://github.com/rhinstaller/anaconda/pull/2817 created instead.

**Pull request closed without merging**
