### PR TITLE
Only use the instclass environment if it actually exists.

### PR DESCRIPTION
**Pull request by dashea**
For master + f22

### CODE REVIEW

**Comment by dashea** [comment]
gonna nack this myself, ran into some group selection weirdness that I want to sort out

**Comment by dashea** [comment]
Figured out the group selection problem (it missed and tried to select a separator that wasn't there) and added a bonus dnfpayload fix.

**Comment by bcl** [comment]
Looks good.

**Comment by dashea** [comment]
Pushed these three, I'll do the new payload methods as a separate pull request.

**Pull request closed without merging**
