### PR TITLE
Show DNF exception instead of silent exit

### PR DESCRIPTION
**Pull request by jkonecny12**

### CODE REVIEW

**Comment by jkonecny12** [comment]
@dashea good point but sad is I already tried it. The problem is you lose context when the exception exits the exception handler. Also you can't save stacktrace to queue I tried that too.
This was only working solution I have found.

It would be nice if someone found clearer solution.

**Comment by vpodzime** [comment]
Looks good to me. This is definitely and improvement. If we found some way to get the exception to "the other side" in the future, we can always change it.

**Comment by jkonecny12** [comment]
I added code to improve bug reporting to Bugzilla. Now the DNF exception will be in name of the bug.

Removing ACK -- complete change of code base.

**Comment by jkonecny12** [comment]
Updated PR.
Implemented @vpodzime idea https://github.com/jkonecny12/anaconda/commit/f151da5fadc43fc0921fa6f7b8215635b9dfbaad#commitcomment-13809371 thank you.

**Comment by vpodzime** [comment]
Looks even better to me now. Thanks!

**Comment by jkonecny12** [comment]
Hmm looks like I broke something. With this patch I can't report bug raised by USR1 signal.

I will look on that in more detail why this happening. I will change status of this somehow when I found cause.

**Comment by jkonecny12** [comment]
I did slight changes and now it should work properly as expected. 
Sad thing is that the DNF error is printed twice. First traceback is where we raised the exception and second is traceback of DNF error. I'm going to file a bug on DNF to make the exception shorter [this](https://bugzilla.redhat.com/show_bug.cgi?id=1277485) the packages there are exception description.

Another problem is that this exception has more than one line so we need to take only first line of the exception description. This was filed as bug on libreport because I think they should do this automatically.

**Comment by jkonecny12** [comment]
Please another review of this PR. Thank you

**Comment by vpodzime** [comment]
Looks good to me too.

**Comment by jkonecny12** [comment]
Pushed. Thank you

**Pull request closed without merging**
