### PR TITLE
Rhel 10 cleanup xorg and vnc leftovers

### PR DESCRIPTION
**Pull request by M4rtinK**
Xorg and VNC related cleanups.

### CODE REVIEW

**Comment by jstodola** [comment]
While testing more use cases on s390x I noticed there are a few additional instances of "x11" in the code that should be updated. In my case `gnome-kiosk` failed to start because of it. The following change fix that for me:
```
diff --git a/data/systemd/anaconda-direct.service b/data/systemd/anaconda-direct.service
index 2f09e05975..e05c4408c4 100644
--- a/data/systemd/anaconda-direct.service
+++ b/data/systemd/anaconda-direct.service
@@ -7,7 +7,7 @@ ConditionPathIsDirectory=|/sys/hypervisor/s390
 ConditionKernelCommandLine=|inst.notmux
 
 [Service]
-Environment=HOME=/root MALLOC_CHECK_=2 MALLOC_PERTURB_=204 PATH=/usr/bin:/bin:/sbin:/usr GDK_BACKEND=x11 XDG_RUNTIME_DIR=/tmp LANG=en_US.UTF-8
+Environment=HOME=/root MALLOC_CHECK_=2 MALLOC_PERTURB_=204 PATH=/usr/bin:/bin:/sbin:/usr GDK_BACKEND=wayland XDG_RUNTIME_DIR=/run/user/0 GIO_USE_VFS=local LANG=en_US.UTF-8
 Type=oneshot
 WorkingDirectory=/root
 ExecStart=/usr/sbin/anaconda
```
Please, have a look also at other "x11" strings in the code.

**Comment by M4rtinK** [comment]
> Please, have a look also at other "x11" strings in the code.

Good catch, will do that! :) I have been mostly looking for "xorg, "x org", etc. X11 is a good candidate as well. :)

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Comment by jkonecny12** [comment]
Please fix the tests.

**Comment by M4rtinK** [comment]
Added two separate PRs that mark the kickstart `vnc` command as deprecated, that can be handled separately from this PR as not to block it. :)

https://github.com/pykickstart/pykickstart/pull/497
https://github.com/rhinstaller/anaconda/pull/5785

**Comment by M4rtinK** [comment]
/kickstart-test --skip-testtypes knownfailure,manual,skip-on-rhel,skip-on-rhel-10,gh576,gh640,gh804,gh1090,gh1104,gh1106,gh1105,gh1108,gh1109,gh1107,gh1110

**Comment by M4rtinK** [comment]
Checked the results of the full RHEL 10 kstest run:

- the keyboard switching flake
- a few known storage related flakes
- an issue with a soon to be removed dracut test using `vnc` boot option for testing

So all in all, nothing relevant as far as I can tell & the PR should be finally good to go. :)

**Pull request merged**
