### PR TITLE
Port DNS kickstart options to RHEL 9

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Port of #4519.

Needs coordination with pykickstart https://github.com/pykickstart/pykickstart/pull/440 tracked in https://bugzilla.redhat.com/show_bug.cgi?id=2172531

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Manual testing ok.

**Comment by VladimirSlavik** [comment]
Blocked by status of the bug.

**Comment by VladimirSlavik** [comment]
This needs all of the fixes in the other upstream PRs.

**Comment by VladimirSlavik** [comment]
Rebased just to keep up with the branch. Pykickstart PR merged, both bugs acked, retesting manually still worked...

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Comment by jkonecny12** [comment]
After https://github.com/rhinstaller/anaconda/pull/4755 is merged please add revert commit here to enable network kickstart command testing.

**Review by rvykydal — APPROVED** [review]

**Pull request merged**
