### PR TITLE
Backport fedora-welcome changes to F38

### PR DESCRIPTION
**Pull request by fmuellner**
Same as #4610, but cherry-pick to the fedora-38 branch.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
I have no idea what's up with tests, there should be a button to run them, but it is nowhere to be found.

**Comment by VladimirSlavik** [comment]
With the latest changes, unit tests passed locally, too.

**Comment by AdamWill** [comment]
This is not safe until livesys-scripts is fixed. https://pagure.io/livesys-scripts/pull-request/12

**Comment by VladimirSlavik** [comment]
Thanks!

**Pull request merged**
