### PR TITLE
Fix makebumpver wrong jira lang

### PR DESCRIPTION
**Pull request by jkonecny12**
JIRA account is the one what define responses locale. Unfortunately this can't be changed from REST API. At the end it means that we need to use ID of the statuses instead of their name.

Side changes:
- improve detection of RHEL in makebumpver script
- add makebumpver and related scripts as infrastructure files

Backport of https://github.com/rhinstaller/anaconda/pull/5432 with a small change of blank lines in rhel_version script.

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
I am not getting why we want to maintain a two different versions of the script. I would keep it conditional and working across all repos the same, so that we dont need to bother with non-trivial backports etc.

IOW, I would not do the `if rhel_version` -> no code thingy.

**Comment by jkonecny12** [comment]
Sounds reasonable but I don't think we want have now resources for such a overhaul.

The same idea works for makeupdates which should be also separated.

**Comment by jkonecny12** [comment]
Inline the almost empty `_is_RHEL` method.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
