### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by copperii**
remove extra at (erase at at...)

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thanks!

**Comment by M4rtinK** [comment]
> @M4rtinK I guess we need to update pixel tests for this. I would suggest to update this PR directly by you, what do you think?
Agreed, I'll handle it that way. :)

**Comment by M4rtinK** [comment]
I've rebased the branch and updated the pixel test reference.

**Pull request merged**
