### PR TITLE
rpmostree uefi fixes

### PR DESCRIPTION
**Pull request by cgwalters**
This is intending to address https://github.com/rhinstaller/anaconda/issues/1188

Still a WIP - I want to do more testing.

The first patch though I think is an obvious cleanup win, if you want me to make that a separate PR I can.

### CODE REVIEW

**Comment by jkonecny12** [comment]
OK, when it won't be in WIP, please write here a comment to notify us ;).
Thanks

**Comment by cgwalters** [comment]
Lifting WIP, these patches work fine for me.  The bug I was seeing was https://bugzilla.redhat.com/show_bug.cgi?id=1492145 which was unrelated.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Pull request merged**
