### PR TITLE
maint: anaconda.spec.in: drop unused usermode (consolehelper)

### PR DESCRIPTION
**Pull request by KKoukiou**
Resolves: rhbz#2268137

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good to me but please add SHA of the commit removing this dependency to the commit message:
https://github.com/rhinstaller/anaconda/commit/919be1d50949d6a18e25a5a2c7df965c23ea1c33

**Comment by KKoukiou** [comment]
> Looks good to me but please add SHA of the commit removing this dependency to the commit message: [919be1d](https://github.com/rhinstaller/anaconda/commit/919be1d50949d6a18e25a5a2c7df965c23ea1c33)

Is this some convention? I did not find something in `docs/commit-log.rst`, and also not checking previous commits touching anaconda.spec.in

**Comment by jkonecny12** [comment]
It is not requirement nor convention but it makes code archeology easier task.

**Comment by KKoukiou** [comment]
> It is not requirement nor convention but it makes code archeology easier task.

But how does putting the commit SHA in the commit message helps? I have nothing against that, just trying to understand the reason.

**Comment by jkonecny12** [comment]
You may find yourself in situation when someone will ask us to add related package or this package back. Then you need you find reason why we removed it on a first place to know if it is reasonable. If you don't have the SHA in the commit message you will find this commit but it will be harder for you to go even deeper to history because tool which is part of the package doesn't need to be named the same as package.

This helped me in the past a few times. It saves time during the code archeology. And also I don't see a reason why not to do this 😃

**Comment by KKoukiou** [comment]
@jkonecny12 I still don't get how this is anyhow helpful, your example did not clarify this for me. 
Anyhow - i dont mind adding it - i just wished to understand the purpose.

**Comment by KKoukiou** [comment]
OK @jkonecny12 I see our misunderstanding. I thought you were asking me to add the current PRs commit ID to the commit message :P I now understand that you want the commit ids of the ancestor relevant commit, that removed the dependencies.

**Pull request merged**
