### PR TITLE
make anaconda working back again with tmux2.4

### PR DESCRIPTION
**Pull request by jkonecny12**
Rebase PR https://github.com/rhinstaller/anaconda/pull/1040 on `f26-devel` branch.

### CODE REVIEW

**Comment by jkonecny12** [comment]
Merged and it is also in master now.

**Comment by AdamWill** [comment]
So this doesn't work properly, for two reasons.

One, bc isn't in the installer environment.

Two, it's not *right*. bc does a floating point number comparison, not a version comparison (given the conventions of how software is normally versioned). For instance, that means it thinks 1.9 > 1.10 (because as a number, it *is*).

This:

https://stackoverflow.com/questions/4023830/how-compare-two-strings-in-dot-separated-version-format-in-bash

suggests using sort -V to do a version sort, which seems like a reasonable solution.

I'll send a modified PR and test it.

**Comment by AdamWill** [comment]
https://github.com/rhinstaller/anaconda/pull/1048 should fix this properly, I believe.

**Comment by pallotron** [comment]
thanks for fixing. :)

**Pull request merged**
