### PR TITLE
Migrate vnc tui spokes to runtime DBUS

### PR DESCRIPTION
**Pull request by adamkankovsky**

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
I am far from being expert in the backend but this looks a bit as an unwanted workaround.

The tui / gui places trying to access the vnc variable, should read it from the proxy runtime .

**Review by KKoukiou — COMMENTED** [review]
Please refer to the bug in the commit message:
https://bugzilla.redhat.com/show_bug.cgi?id=2292556

**Comment by KKoukiou** [comment]
@adamkankovsky this still crashes.
Screen Shot 2024-06-19 at 10 00 18

**Comment by adamkankovsky** [comment]
> @adamkankovsky this still crashes. Screen Shot 2024-06-19 at 10 00 18

I already found it. When otps is used, the value is in a string otherwise it is secret data. I've already edited it. I apologize for the mistake. I tested it using kickstrat and this error could not be here.

**Review by M4rtinK — APPROVED** [review]
Looks good to me, code wise. :)

**Review by KKoukiou — APPROVED** [review]
Tested also the ISO - works correctly with inst.tui inst.vnc inst.vncpassword

**Pull request merged**
