### PR TITLE
network: apply kickstart network --nodefroute also from stage2

### PR DESCRIPTION
**Pull request by rvykydal**
Apply the option also when kikcstart is applied in stage2, for example when
defining commands via %pre section.

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

Just a nitpick. You have typo in the commit message: ``kikcstart``.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by rvykydal** [comment]
jenkins, test this please

**Review by jkonecny12 — APPROVED** [review]
Looks even better now.

**Review by poncovka — APPROVED** [review]

**Pull request merged**
