### PR TITLE
gui: fix summary hub layout for Japanese translations

### PR DESCRIPTION
**Pull request by rvykydal**
The patch makes the spoke buttons more compact vertically (same as with
other languages), making User spoke accessible without scrolling.

Resolves: rhbz#2120293

### CODE REVIEW

**Comment by rvykydal** [comment]
Original:
japanese_original

Patched:
japanese_patched

I've checked that for German, Hebrew, Finnish, Chinese, Korean, English the patch makes no difference in the layout.

**Review by poncovka — APPROVED** [review]
Looks good to me. Thank you for figuring this out!

**Review by VladimirSlavik — APPROVED** [review]
Thank you! I'd say looks good to me, but there isn't much to see :-D

**Review by M4rtinK — APPROVED** [review]
Nice and simple, thanks a lot! :)

**Comment by rvykydal** [comment]
PR with port to Fedora: https://github.com/rhinstaller/anaconda/pull/4325

**Pull request merged**
