### PR TITLE
Use a disk label to find the filesystem for escrow results

### PR DESCRIPTION
**Pull request by dashea**
The escrow test does not use autopart, so the root filesystem does not
end up on /dev/mapper/fedora-root like most other tests. Use a label so
we don't have to depend on the partition order.

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me. A clever change.

**Comment by clumens** [comment]
If you get bored, there are several other tests that could use this same trick.

**Comment by dashea** [comment]
Added label usage to btrfs-1 and 2 and raid-1

**Comment by dashea** [comment]
Dang it, missed tmpfs. I'll push an update with that in a sec

**Comment by clumens** [comment]
Yep, looks good to me too.

**Comment by dashea** [comment]
Pushed.

**Pull request closed without merging**
