### PR TITLE
Add automatic update of the npm packages.json (#infra)

### PR DESCRIPTION
**Pull request by jkonecny12**
Use existing dependabot configuration for that.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

**Review by KKoukiou — COMMENTED** [review]
Seems this could be problematic.
https://github.com/cockpit-project/starter-kit/pull/527

**Comment by KKoukiou** [comment]
So this is very likely not going to work (as is), see https://github.com/cockpit-project/starter-kit/pull/527

However I am willing to give it a try. I will send a PR to patternfly/react-core to define the react-styles as peer dependency, in order that the dependabot can group these packages together. https://github.com/dependabot/dependabot-core/issues/1296#issuecomment-1035995416

**Comment by KKoukiou** [comment]
So proposed this to `patternfly` upstream https://github.com/patternfly/patternfly-react/pull/6930 

Would be worth that you take a look as well.

**Pull request merged**
