### PR TITLE
Stop ignoring "Run" in pylint

### PR DESCRIPTION
**Pull request by VladimirSlavik**
These days we have nothing with such a name.

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Looks good to me. However, I am not sure whether we run the check that uses this option.

**Comment by martinpitt** [comment]
@poncovka : I would assume here? https://github.com/rhinstaller/anaconda/tree/master/tests/pylint

**Comment by poncovka** [comment]
> @poncovka : I would assume here? https://github.com/rhinstaller/anaconda/tree/master/tests/pylint

Yes, but we have a lot of disabled pylint checks. See: https://github.com/rhinstaller/anaconda/blob/master/tests/pylint/pylintrc#L69

**Comment by VladimirSlavik** [comment]
After digging a bit more, this is a default value. Let's ignore this instead.

**Pull request closed without merging**
