### PR TITLE
Use sysconfig in dracut directly, not via distutils

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Removes last usage of distutils in dracut code.

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks!

**Review by poncovka — COMMENTED** [review]
Looks good to me.

**Review by jkonecny12 — COMMENTED** [review]
Looks good to me too.

**Comment by VladimirSlavik** [comment]
This is a potentially compose-breaking change, and not required immediately. I suggest waiting on the Copy logs task breakages to stabilize, then merge this. In reality that translates to next week, probably?

**Review by jkonecny12 — APPROVED** [review]
As I already said, looks good to me. Thanks!

**Pull request merged**
