### PR TITLE
Give users a chance to fix unusable initial storage layouts

### PR DESCRIPTION
**Pull request by dwlehman**
If there is an issue with the initial storage configuration that must be resolved before installation can continue, give the user an opportunity to resolve it. If they do, they can retry the storage scan and proceed with the installation. If not, they have to exit the installer. Limits on input quality are not unreasonable.

This relies on rhinstaller/blivet#76

### CODE REVIEW

**Comment by vpodzime** [comment]
If I understand it correctly, the patches should be reorganized as the first one requires the latter ones, doesn't it? If yes, please make it the last patch.

Otherwise this looks good to me.

**Comment by vpodzime** [comment]
Because of the changes containing the Python 3's module name ``queue`` we need to check this works/is adapted on the Python 3 devel branch.

**Comment by dwlehman** [comment]
They're in the correct order on the branch, but github seems to be using the timestamps instead. See here:

https://github.com/dwlehman/anaconda/commits/unusable-storage-branch

**Comment by vpodzime** [comment]
Oh, that happened to me too some time ago. Thanks for making it clear for me.

**Comment by dwlehman** [comment]
Cherry-picked and pushed.

* 8b27185 - Add handling for unusable storage configurations.
* 9e70bbf - Allow markup in the label/message of DetailedErrorDialog.
* 9f6e212 - Allow passing an optional button list to showDetailedError.
* 41e0040 - Allow kwargs with gtk_action_wait, gtk_action_nowait decorators.

**Pull request closed without merging**
