### PR TITLE
Remove deviceprobe and install commands

### PR DESCRIPTION
**Pull request by VladimirSlavik**
They have been deprecated a long time ago.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
See also https://github.com/pykickstart/pykickstart/pull/347

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Comment by jstodola** [comment]
Can you please wait a bit before merging this PR? Although the install command has been deprecated for a while, this change would cause problems for installations via Beaker (https://beaker-project.org/), where the install command is still provided in the kickstart file even for rawhide.
Bug against Beaker: https://bugzilla.redhat.com/show_bug.cgi?id=1896479

**Comment by VladimirSlavik** [comment]
Sure, let's do that.

However, specifically this change does not matter. It's only two lines because even before, the commands did not do anything. It's the pykickstart change that actually changes outward behavior - that makes these commands not parse.

**Comment by poncovka** [comment]
This PR is safe to merge, because it only removes some unused imports. I don't think it's a notable change.

**Comment by jstodola** [comment]
OK, feel free to merge this change, I will follow the pykickstart PR to avoid unpleasant surprises before the Beaker bug is resolved.
Sorry for the noise :-)

**Pull request merged**
