### PR TITLE
webui: enable linter for webui CI runs

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by jstodola** [comment]
Shouldn't be `ui/webui/src/index.js` changes in a separate commit?

**Comment by jstodola** [comment]
I should have provided a reasoning why I think that separate commits are better:
When linter for webui CI runs needs to be disabled for whatever reason in the future, it would not be possible to do it by reverting a single commit that enabled it without re-introducing the issues found in `ui/webui/src/index.js`.

**Comment by KKoukiou** [comment]
> I should have provided a reasoning why I think that separate commits are better: When linter for webui CI runs needs to be disabled for whatever reason in the future, it would not be possible to do it by reverting a single commit that enabled it without re-introducing the issues found in `ui/webui/src/index.js`.

But there is not  scenario where we would want to disable a linter in CI runs. linters are an extra tool to ensure code quality.

**Review by jkonecny12 — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
Looks good to me - but please split the fixups to a separate commit. Thanks! :)

**Pull request merged**
