### PR TITLE
Document how to start a self-hosted GitHub actions runner locally

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
This is mostly an excuse to test the deployment of our self-hosted github action runners :) However, it [looks wrong](https://github.com/martinpitt/anaconda/tree/doc-runner/tests#tests-in-ci) as I used Markdown syntax in our ReST file. So I force-pushed, and we can test what happens with multiple parallel runs as well.

**Comment by martinpitt** [comment]
Both the run for the [previous version](https://github.com/rhinstaller/anaconda/pull/2932/checks?check_run_id=1273967938) and the [current push](https://github.com/rhinstaller/anaconda/pull/2932/checks?check_run_id=1273999301) ran successfully.

@jkonecny12 : Time to disable the "Anaconda RHEL 8 tests" Jenkins job? Do you want to do the rpm files one yourself (I'm happy to help/guide of course), or want me to?

**Comment by martinpitt** [comment]
Fixing links harder, now it [looks good](https://github.com/martinpitt/anaconda/tree/doc-runner/tests#tests-in-ci).

**Comment by jkonecny12** [comment]
> Both the run for the [previous version](https://github.com/rhinstaller/anaconda/pull/2932/checks?check_run_id=1273967938) and the [current push](https://github.com/rhinstaller/anaconda/pull/2932/checks?check_run_id=1273999301) ran successfully.
> 
> @jkonecny12 : Time to disable the "Anaconda RHEL 8 tests" Jenkins job? Do you want to do the rpm files one yourself (I'm happy to help/guide of course), or want me to?

Nice job! Jenkins job is disabled!

I'll gladly handle the RPM tests myself to test the set-up!

**Review by jkonecny12 — APPROVED** [review]
LGTM ;)

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Pull request merged**
