### PR TITLE
Fix the progress bar steps

### PR DESCRIPTION
**Pull request by poncovka**
The progress bar steps are related to the total number of tasks. The
bar should do one step every time the installation task is completed.

### CODE REVIEW

**Comment by poncovka** [comment]
Jenkins, test this please

**Comment by poncovka** [comment]
Jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
Please link this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1480836) here.

**Comment by jkonecny12** [comment]
Great work. This fix finally landed! :+1:

**Pull request merged**
