### PR TITLE
Fix dependency on zram-generator in RHEL

### PR DESCRIPTION
**Pull request by sgallagher**
Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Thank you! Does this need porting somewhere too?

**Comment by sgallagher** [comment]
We will need a build with this change in Fedora and CentOS Stream 9 once https://kojihub.stream.rdu2.redhat.com/koji/buildinfo?buildID=10659 lands in the compose.

**Comment by jstodola** [comment]
@sgallagher thanks for this change. Can you also create a RHEL-9 bug against anaconda?

**Comment by msekletar** [comment]
I think you guys need to go ahead and build the Anaconda with this change. Otherwise we won't have any compose, as it will fail because Anaconda is still referencing the package by its old name.

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Comment by sgallagher** [comment]
I created https://bugzilla.redhat.com/show_bug.cgi?id=1991617 for RHEL 9

**Comment by jkonecny12** [comment]
Thanks a lot @sgallagher and @msekletar for solving this issue so fast!

**Pull request merged**
