### PR TITLE
Re enable permian for kstest on pr

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

The commit messages should include `#infra`, I think.

**Comment by VladimirSlavik** [comment]
Ah, the check wants it to be exactly `(#infra)<EOL>`, so it fails on the double quotes. I dropped the label again, looks like the check can be actually pretty useless :-/

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well & thanks for fixing the issue! :)

**Review by jkonecny12 — APPROVED** [review]
Thanks for solving this!

**Review by jkonecny12 — APPROVED** [review]

**Comment by rvykydal** [comment]
Depends on https://github.com/rhinstaller/permian/pull/36

**Pull request merged**
