### PR TITLE
Run bash instead of sh in rescue mode

### PR DESCRIPTION
**Pull request by VladimirSlavik**
What it says on the label.

Not sure yet what else it affects, testing still todo.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Is it the same? The prompt says "sh" which is why I noticed this at all...

**Comment by VladimirSlavik** [comment]
This needs both manual testing, and checking kickstart tests. Hence still a draft.

**Comment by VladimirSlavik** [comment]
Manual testing ok, onwards to kickstart tests...

**Comment by M4rtinK** [comment]
> Is it the same? The prompt says "sh" which is why I noticed this at all...

Looks like this can be used to check what is actually providing the shell running on a console:

`$SHELL --version`

**Comment by VladimirSlavik** [comment]
Coverage Kickstart tests passed, and there isn't anything that would seem related, so that's that - undrafting.

**Pull request merged**
