### PR TITLE
tests: Fix webui-tests workflow

### PR DESCRIPTION
**Pull request by velezd**
- Remove unused/duplicate WebUI e2e testplan
- Make the GitHub check result correspond with tests results
- Collect all the log files needed for easy debugging
- Fix waiving

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by KKoukiou — COMMENTED** [review]
@velezd the changes look good. How did you tests them? Do you have this workflow already setup on your fork? Can you pls link the workflow execution as verification that this works?

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Comment by VladimirSlavik** [comment]
This is made to run on a custom worker, so there's no good way to test it for someone who can't get the templates to spin up an instance.

Personally I'd say this is fine, as we'll need more work on the whole thing anyway...

**Comment by jkonecny12** [comment]
> This is made to run on a custom worker, so there's no good way to test it for someone who can't get the templates to spin up an instance.
> 
> Personally I'd say this is fine, as we'll need more work on the whole thing anyway...

Would it be so problematic to run it locally as https://github.com/rhinstaller/anaconda/tree/master/ui/webui/test#running-tests-in-a-toolbox ? If you want, I'll take a look how to abstract the thing?

**Comment by velezd** [comment]
Running the tests locally is not a problem, but running the GitHub workflow exactly as it is here is the hard part. However I did test some of the changes individually.

**Comment by KKoukiou** [comment]
@velezd @VladimirSlavik this is not the first neither the last time that we need to update github workflow files for the end to end tests. Such updates need to be tested on forks, set up so that they have permissions to use the workers needed. 

Merging untested changes should be really the last resort, and only happen when it's impossible to test the changes anyhow. 

If this PR falls in the last category of 'impossible to test in fork', please analyze little bit more the  comment from here https://github.com/rhinstaller/anaconda/pull/4806#issuecomment-1574037590

What permissions can't be adjusted to forks that they are having access to these workers?

**Review by KKoukiou — CHANGES_REQUESTED** [review]
@velezd @VladimirSlavik this is not the first neither the last time that we need to update github workflow files for the end to end tests. Such updates need to be tested on forks, set up so that they have permissions to use the workers needed.

Merging untested changes should be really the last resort, and only happen when it's impossible to test the changes anyhow.

If this PR falls in the last category of 'impossible to test in fork', please analyze little bit more the comment from here https://github.com/rhinstaller/anaconda/pull/4806#issuecomment-1574037590

What permissions can't be adjusted to forks that they are having access to these workers?

**Review by KKoukiou — APPROVED** [review]
After a discussion I revoke my rejection.

**Pull request merged**
