### PR TITLE
Fix the help button mnemonic display on spokes

### PR DESCRIPTION
**Pull request by dashea**
If you hold "Alt" on a hub or standalone spoke, the "Help!" label will change to "Help! (F1)". If you hold Alt on a normal spoke, this does not happen. This patch fixes that by moving the mnemonics listener into the method that changes the window that is visible in the stack.

### CODE REVIEW

**Comment by dashea** [comment]
Forgot to mention: this can, and probably should, be cherry-picked to f22-branch as well, though I have not yet created a bug for it.

**Comment by clumens** [comment]
Looks good to me.

**Comment by dashea** [comment]
Rebased and merged, but leaving the pull request open to remind to cherry-pick to f22

**Comment by dashea** [comment]
Cherry-picked to f22

**Pull request closed without merging**
