### PR TITLE
storage: Remove support for NVDIMM namespaces

### PR DESCRIPTION
**Pull request by poncovka**
All additional support for NVDIMM is being deprecated and removed, especially the support for the namespace reconfiguration. However, namespaces configured in the block/storage mode can be still used for installation.

The `nvdimm` kickstart command is deprecated and will be removed in future releases.

**Depends on:** https://github.com/pykickstart/pykickstart/pull/469
**Blocks:** https://github.com/storaged-project/blivet/pull/1172

Resolves: #INSTALLER-3766

### CODE REVIEW

**Comment by poncovka** [comment]
@vojtechtrefny I am able to select a NVDIMM device in the fsdax mode for the installation. It just won't boot. I guess that is the expected behaviour, right? I have used the Blivet changes as well for testing.

nvdimm_without_support

nvdimm_without_support_out

**Comment by vojtechtrefny** [comment]
> @vojtechtrefny I am able to select a NVDIMM device in the fsdax mode for the installation. It just won't boot. I guess that is the expected behaviour, right?

Yes, device mapper doesn't work with the fsdax mode (only with the sector mode). I'd say this is expected and we should just ignore it.

**Comment by vojtechtrefny** [comment]
> > @vojtechtrefny I am able to select a NVDIMM device in the fsdax mode for the installation. It just won't boot. I guess that is the expected behaviour, right?
> 
> Yes, device mapper doesn't work with the fsdax mode (only with the sector mode). I'd say this is expected and we should just ignore it.

We could add `pmemN` devices (but not `pmemNs` devices (sector mode namespaces)) to the ignored list to avoid this.

**Review by VladimirSlavik — COMMENTED** [review]
Changes LGTM, but I didn't stop to think what might be missing...

**Comment by poncovka** [comment]
> We could add `pmemN` devices (but not `pmemNs` devices (sector mode namespaces)) to the ignored list to avoid this.

Done.

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Review by VladimirSlavik — APPROVED** [review]

**Pull request merged**
