### PR TITLE
Make the scale visible by default (#1943370)

### PR DESCRIPTION
**Pull request by poncovka**
GLib crashes with a segmentation fault if the accessibility
is enabled and a GtkScale widget is not visible by default.
We will hide the widget later if required.

Turn off wrapping of the scale values. There is not enough
space for more than one line above the scale.

Resolves: rhbz#1943370

### CODE REVIEW

**Comment by poncovka** [comment]
Before:
scale_01

After:
scale_02

**Comment by jstodola** [comment]
Tested on RHEL using [anabot](https://pagure.io/anabot) and [minimal.xml](https://pagure.io/anabot/blob/main/f/examples/minimal.xml) recipe, which was previously failing due to anaconda crash.
It's now possible to go through the installation and reclaim disk space.
Thanks!

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you!

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by VladimirSlavik — APPROVED** [review]
Thank you! Looks good to me.

Does this work well also when the scale is at its end?

**Comment by poncovka** [comment]
> Does this work well also when the scale is at its end?

It does. It looks the same as the mark below.

**Pull request merged**
