### PR TITLE
Reload NTP server list in dialog on every run

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Fixes weird behavior of removals and changes. Basically the dialog was reloaded only on cancel, but needs it on every show.
    
See also: rhbz#1823129

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Thank you, fixed the commit message, will merge once tests pass.

**Comment by VladimirSlavik** [comment]
Pylint is broken and can't run now. + Previous version was ok. = Merging

**Comment by VladimirSlavik** [comment]
Given the bug was later split, the commit should have read "Resolves" instead of "Related".

**Comment by poncovka** [comment]
> Given the bug was later split, the commit should have read "Resolves" instead of "Related".

@VladimirSlavik, never mind. Just update the bug in bugzilla :-)

**Pull request merged**
