### PR TITLE
Improvements for running at low resolutions

### PR DESCRIPTION
**Pull request by dashea**

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by jkonecny12** [comment]
In the first commit comment: " *Also also* the disk label column to be shrunk in case the user doesn't care about all of that."

I think there is miss-type and should be only one *also*.

**Comment by jkonecny12** [comment]
Other than that seems good to me.

**Comment by dashea** [comment]
Pushed.

**Pull request closed without merging**
