### PR TITLE
Fix parsing of hostname from cmdline for ipv6.

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1554271

### CODE REVIEW

**Comment by rvykydal** [comment]
This is backport from rhel7-branch

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
@jkonecny12 What do you mean by 'IP validation'? The regex is just removing substrings in square brackets (which are IPv6 addresses) from ip= dracut option.

**Comment by jkonecny12** [comment]
Ahh true, I've miss-read that. In that case it should be fine (or I hope it will be) :D.

**Comment by rvykydal** [comment]
jenkins, test this please

**Pull request merged**
