### PR TITLE
Remove deprecated support for add-ons

### PR DESCRIPTION
**Pull request by poncovka**
Use the support for Anaconda DBus add-ons instead.

### CODE REVIEW

**Review by VladimirSlavik — COMMENTED** [review]
Looks good to me, but I don't think I know enough to meaningfully ACK this.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by poncovka** [comment]
Rebased.

**Review by M4rtinK — APPROVED** [review]
Looks good to me, nice cleanup! :)

**Pull request merged**
