### PR TITLE
Change the example bug related to unlocked LUKS devices

### PR DESCRIPTION
**Pull request by poncovka**
* Update the common issue about unlocked LUKS devices.
* Use the latest Read the Docs theme to fix the field lists.

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by poncovka** [comment]
The current look of the field lists:
Screenshot from 2022-03-07 13-56-19

The fixed look of the field lists:

Screenshot from 2022-03-07 13-56-25

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Pull request merged**
