### PR TITLE
infra: Do not use rhel repos in centos container

### PR DESCRIPTION
**Pull request by jkonecny12**
I didn't realized that we are using CentOS Stream container now so I automatically added RHEL repositories. That is wrong and I'm messing up packages between CentOS and RHEL.

Let's use only CentOS Stream packages right now and enable CRB repository in those.

Also add our temporary workaround repository to iso-creator container.

### CODE REVIEW

**Comment by M4rtinK** [comment]
I've tried to add this to [my Wayland + GRD/RDP branch](https://github.com/rhinstaller/anaconda/pull/5498) but it does not help - still the same error with missing python3-pam package. :P

**Comment by jkonecny12** [comment]
I see the issue. Give me a sec.

**Comment by jkonecny12** [comment]
My bad, we don't need `python-pam` package in the container but for the build. Remove the repository from the container (plus CRB which is also not required) and add the new repository to the lorax call.

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Pull request merged**
