### PR TITLE
Remove Jenkins from makebumpver

### PR DESCRIPTION
**Pull request by VladimirSlavik**
SSIA.

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
The code is from 2015 and I think this is not used a long time already (even before Jenkins was decommissioned). Lets remove it.
Thanks!

**Comment by VladimirSlavik** [comment]
I just realized the function was not even called anywhere :D

**Review by M4rtinK — APPROVED** [review]
LOL, I still remember passing the --skip-jenkins option for literately years give how stable our Jenkins instance used to be.
 Looks good to me, thanks a lot! :)

**Review by poncovka — APPROVED** [review]
Thank you!

**Review by rvykydal — APPROVED** [review]
Thank you

**Pull request merged**
