### PR TITLE
Enable upload of our CentOS Stream containers (rhel-9 and rhel-10 branches) 

### PR DESCRIPTION
**Pull request by jkonecny12**
Add rhel-9 and rhel-10 containers to the container images we are uploading on quay.io so these container images could be gated.

This is now possible because we migrated from RHEL containers to CentOS Stream containers, so we can gate containers for rhel branches and simplify our workflows.

This is first step to fix issues with pot files update for rhel-9 and rhel-10 which needs their own containers.

Unfortunately, rhel-10 will not work until fix https://github.com/rhinstaller/anaconda/pull/5619/commits/497922aefbecf0e17332a92a0aaa59402ad05caf from https://github.com/rhinstaller/anaconda/pull/5619 is merged but it's not blocking merge of this - just failure is expected.

Tested here: https://github.com/jkonecny12/anaconda/actions/runs/8893376749

### CODE REVIEW

**Comment by jkonecny12** [comment]
My experience is that if we don't follow latest or we don't have automation for that we will end up on using outdated things. In general no-one will notice we should update these.

However, maybe a good point could be that the host won't exists if it won't be supported. So from this PoV maybe we don't need to care about what ubuntu we are using until it starts failing because the host was removed.

What would you prefer. And I really don't think keep workflows up to date is the correct answer here.

**Comment by KKoukiou** [comment]
> My experience is that if we don't follow latest or we don't have automation for that we will end up on using outdated things. In general no-one will notice we should update these.
> 
> However, maybe a good point could be that the host won't exists if it won't be supported. So from this PoV maybe we don't need to care about what ubuntu we are using until it starts failing because the host was removed.
> 
> What would you prefer. And I really don't think keep workflows up to date is the correct answer here.

Not strong opinion here, but please dont squeeze such unrelated changes in commits that dont needs them.
Feel free to merge.

**Comment by jkonecny12** [comment]
Good point.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
