### PR TITLE
network: do not use dialog for just single wireless connection to con…

### PR DESCRIPTION
**Pull request by rvykydal**
…figure

Follow up to https://github.com/rhinstaller/anaconda/pull/2977

### CODE REVIEW

**Comment by rvykydal** [comment]
Show dialog for network selection only if we have multiple profiles:
https://rvykydal.fedorapeople.org/new_ui_configure_more_cons_available.webm

If there is only single connection, edit it right away:
https://rvykydal.fedorapeople.org/new_ui_configure_single_con.webm
... The connection is created when selecting the network and in this case entering wrong password. Typical use case is WPA Enterprise where we don't ask for credentials in secret agent dialog when selecting the network (too complex), but we just create the connection and let the user enter credentials via configuration using nm-c-e.

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by jstodola** [comment]
I'm a bit late, but I found it confusing to allow to click the "Configure..." button if there is nothing to be configured. (https://rvykydal.fedorapeople.org/new_ui_configure_single_con.webm). Shouldn't the button be disabled if the list of networks to configure is empty?

**Comment by rvykydal** [comment]
> I'm a bit late, but I found it confusing to allow to click the "Configure..." button if there is nothing to be configured. (https://rvykydal.fedorapeople.org/new_ui_configure_single_con.webm). Shouldn't the button be disabled if the list of networks to configure is empty?

I will add this in another PR when NM crashes which would make the configuration with this addition even more fragile are fixed (https://bugzilla.redhat.com/show_bug.cgi?id=1873561)

**Comment by rvykydal** [comment]
> > I'm a bit late, but I found it confusing to allow to click the "Configure..." button if there is nothing to be configured. (https://rvykydal.fedorapeople.org/new_ui_configure_single_con.webm). Shouldn't the button be disabled if the list of networks to configure is empty?
> 
> I will add this in another PR when NM crashes which would make the configuration with this addition even more fragile are fixed (https://bugzilla.redhat.com/show_bug.cgi?id=1873561)

https://github.com/rhinstaller/anaconda/pull/3098

**Pull request merged**
