### PR TITLE
Allow to run kickstart tests on a PR with a specific test PR

### PR DESCRIPTION
**Pull request by rvykydal**
Tested on local fork: https://github.com/rvykydal/anaconda/pull/191
Depends on https://github.com/rhinstaller/kickstart-tests/pull/1231

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
Please adjust the template file and run make `reload infra`

**Review by jkonecny12 — COMMENTED** [review]
I think this can be simplified.

If you checkout master branch and then add step with `gh pr checkout` you shouldn't need those api information.

https://cli.github.com/manual/gh_pr_checkout

**Comment by rvykydal** [comment]
> I think this can be simplified.
> 
> If you checkout master branch and then add step with `gh pr checkout` you shouldn't need those api information.
> 
> https://cli.github.com/manual/gh_pr_checkout

Should I rebase to the latest target branch after the checkout (I think so) ? If so, how do I learn what is the target (BASE_REF) ?

**Comment by jkonecny12** [comment]
> > I think this can be simplified.
> > If you checkout master branch and then add step with `gh pr checkout` you shouldn't need those api information.
> > https://cli.github.com/manual/gh_pr_checkout
> 
> @jkonecny12 Should I rebase to the latest target branch after the checkout (I think so) ? If so, how do I learn what is the target (BASE_REF) ? Or can we safely assume master?

This should return you the target branch.
```shell
# do the checkout by standard action

# step to rebase
gh pr checkout <number>
BASE_REF=$(gh pr view --json baseRefName --template '{{.baseRefName}}' 5722)
git rebase $BASE_REF
```

**Comment by rvykydal** [comment]
Updated with @jkonecny12's suggestions

**Review by jkonecny12 — APPROVED** [review]
Looks great. I'm glad my suggestion was helpful ;)

**Pull request merged**
