### PR TITLE
network: adapt to ibft plugin being enabled by default in NM (#1371188)

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1371188

Port from rhel7-branch

### CODE REVIEW

**Comment by jkonecny12** [comment]
Could you please write commit message explaining how this works.
Otherwise looks good to me.

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
> Could you please write commit message explaining how this works.

PR updated.

**Pull request merged**
