### PR TITLE
Fix bad IP checker in text installation

### PR DESCRIPTION
**Pull request by jkonecny12**
Fix for crash in text anaconda when user set illegal IP address.
Fix bad warning message when illegal IP is set.

*Resolves bug (#1217393)*

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by kellinm** [comment]
The class name *Fake_RE_Nameservers* doesn't really describe what's happening.  It looks like it's a boolean method that checks the IP address and returns whether or not is is valid.  Is_Valid_IP_By_Regex would be easier to parse for future maintainers.

There is also similar ticket out there for nameservers entry failing when the entry is "X.X.X.X, Y.Y.Y.Y" due to the extra space as an invalid character. I was looking to actually use the validated IP to check and catch exceptions and return those to the logs and remove the entry from the list to prevent crashes.  The failed entries would also show up on the screen with an abbreviated message to the user.

I like your concept of the wrapper class - what if we combined both solutions and had that code inside your wrapper using both the regular expression as well as an actual network validation that returns BOOLEAN, ErrorMessage and we can display the errors in the text client?

**Comment by jkonecny12** [comment]
> The class name Fake_RE_Nameservers doesn't really describe what's happening. It looks like it's a boolean method that checks the IP address and returns whether or not is is valid. Is_Valid_IP_By_Regex would be easier to parse for future maintainers.
 
When you look on the source file you see that similar class is already present ``Fake_RE_IPV6`` I only used the same naming convention which was already there for some time. I think it's exactly how it's named fake regular expression class for nameservers.

> There is also similar ticket out there for nameservers entry failing when the entry is "X.X.X.X, Y.Y.Y.Y" due to the extra space as an invalid character. I was looking to actually use the validated IP to check and catch exceptions and return those to the logs and remove the entry from the list to prevent crashes. The failed entries would also show up on the screen with an abbreviated message to the user.

Could you please write here number of this bug?
 
> I like your concept of the wrapper class - what if we combined both solutions and had that code inside your wrapper using both the regular expression as well as an actual network validation that returns BOOLEAN, ErrorMessage and we can display the errors in the text client?

I don't agree with this idea. Fake regex class is purely for getting right input from user by providing fake regex class. I don't think this is the right place to test if the given IP is valid in the network. 
If we really need to test network validation it will be better place after input validation in my opinion.

**Comment by vpodzime** [comment]
Still think this change is OK.

**Comment by kellinm** [comment]
The alternate ticket is BZ 1174451.

I think I worded my intentions wrong - I do not think it's worthwhile to validate whether an address exists on a network as that introduces too much uncertainty and timeout issues.

I meant capturing the conversion-to-address errors.

EG: Try to make it throw a similar error to this which is simply the inability to convert it to an IP and catch it.

File "/usr/lib64/python2.7/site-packages/pyanaconda/nm.py", line 870, in nm_ipv4_to_dbus_int
    return struct.unpack("=L", socket.inet_aton(address))[0]

This means that - even *if* the regular expression fails to catch the problem - we will have caught the error and put a reasonable error message into the logs.

**Comment by vpodzime** [comment]
Adding the check using the conversion makes sense to me. Thanks for the clarification, @kellinm

**Comment by jkonecny12** [comment]
There is something like this, but without the exception catching. Now there is a  ``network.check_ip_address(ip, version=6):`` which using ``IPy.parseAddress(address)`` method for IPv6. I can change this to test IPv4 too if you want.

Is this feasible solution for you @kellinm ?

**Comment by kellinm** [comment]
Yes this is feasible for me - will your regex strip whitespace? If so - I will drop my separate patch and we can tie our tickets together.

**Comment by jkonecny12** [comment]
Yeah it wouldn't be problem I think. I can change it to ",\w*" or how exactly it is here :) .
I'll create new pull request for this.

**Pull request closed without merging**
