### PR TITLE
rhv: Adding rhv for installclasses

### PR DESCRIPTION
**Pull request by dougsland**
This patch creates installclass for rhv.

### CODE REVIEW

**Comment by dougsland** [comment]
Tested against oVirt Node Next and RHV 4.0 + anaconda-21.48.22.87-1 everything worked nicely.

**Comment by dougsland** [comment]
Anaconda logs from RHV4 test installation: http://people.redhat.com/dlandgra/anaconda/

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by snbueno** [comment]
Looks good to me as well.

**Comment by fabiand** [comment]
:+1: from my side as well.

**Pull request merged**
