### PR TITLE
network: enable NM autoconnections only if inst.ks and ip= is not used

### PR DESCRIPTION
**Pull request by rvykydal**
Applies rhel-specific patch https://github.com/rhinstaller/anaconda/commit/49d345bdb2aa311e22d70e2b9f636a37e07f79ae to rhel-10

TODO:
- [x] Add a test (kickstart test?)
- [x] Try to figure out generic upstream solution / patch - would require detection of rhel (on systemd units level)

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :) For the detection, I guess os-release parsing could work, but wonder if it would be robust enough. :)

**Comment by rvykydal** [comment]
The kickstart test already exists.
A generic upstream solution: https://github.com/rhinstaller/anaconda/pull/5957

**Comment by rvykydal** [comment]
Obsoleted by https://github.com/rhinstaller/anaconda/pull/5957

**Pull request closed without merging**
