### PR TITLE
RHEL-10: Fix user systemd error printed to console and other minor RDP fixes

### PR DESCRIPTION
**Pull request by jkonecny12**
Anaconda is starting systemd --user for RDP session. This unfortunately, will result in message:

```
Failed to adjust memory pressure threshold, ignoring: Device or resource
busy
```

This message is printed directly to terminal and bypassing stdout or stderr.

Force this message to be logged to the journal instead of terminal.

Resolves: [RHEL-67911](https://issues.redhat.com/browse/RHEL-67911)

Backport of 
- https://github.com/rhinstaller/anaconda/pull/5979
- https://github.com/rhinstaller/anaconda/pull/5994
- part of https://github.com/rhinstaller/anaconda/pull/5829

### CODE REVIEW

**Comment by jkonecny12** [comment]
Local testing done and works.

**Review by M4rtinK — APPROVED** [review]
Looking good! :)

**Comment by jkonecny12** [comment]
Please ignore the failed test. I made a typo in the test name so the result is not valid :(

**Pull request merged**
