### PR TITLE
Permit blacklisting modules from inherited parent product

### PR DESCRIPTION
**Pull request by jcpunk**
This patch will make it easy for CentOS and SL to inherit RHEL, but not subscription-manager.

### CODE REVIEW

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
So we discussed this in the team and we have decided that we would like to avoid having exclude lists. Mainly because we have plenty of options which could be excluded so it could grow our configuration file a lot.

Please change this PR to just copy the list and remove one item from the CentOS and SL. You can leave the test you have to avoid problems in the future.

**Comment by jcpunk** [comment]
That is a bit sad, though I do understand the reasoning.

I'll close this PR out and build a new one with the alternate workflow.

**Pull request closed without merging**
