### PR TITLE
Fix I/O issues when anaconda is started without a locale.

### PR DESCRIPTION
**Pull request by dashea**
Fun fact: python 3 lets input() crash with UnicodeDecodeError.

### CODE REVIEW

**Comment by vpodzime** [comment]
WTH, python 3?! I'm starting to think that python people should really get a huge badge for an incredible achievement -- doing unicode support in a bad way; twice!

**Comment by vpodzime** [comment]
The change looks good to me.

**Comment by jkonecny12** [comment]
Looks good to me too.
I think this should go to F23 branch too so I'm adding labels.

**Comment by dashea** [comment]
Pushed to master and f23

**Pull request closed without merging**
