### PR TITLE
Enable ruff pylint checks

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This enables lots of checks for ruff, hopefully bringing it closer to what we have with pylint.

See also https://beta.ruff.rs/docs/rules/

The list of ignored checks is partially a masked TODO - there are some valid detections with these. However, fixing such detections is either a too wide change, or would modify behaviour enough to warrant retesting the application.

### CODE REVIEW

**Review by vojtechtrefny — APPROVED** [review]
LGTM

**Comment by VladimirSlavik** [comment]
rebased again...

**Pull request merged**
