### PR TITLE
Apply --noverifyssl option for liveimg kickstart command

### PR DESCRIPTION
**Pull request by jstodola**
Related: rhbz#1886985

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Review by VladimirSlavik — APPROVED** [review]
Thank you, looks good to me.

(I checked the actual download / source use, and this should be the whole fix.)

**Review by poncovka — APPROVED** [review]
Thanks!

**Comment by jkonecny12** [comment]
We are going to backport this to RHEL. So I think we should have here also the unit tests? WDYT @poncovka ?

**Comment by poncovka** [comment]
> We are going to backport this to RHEL. So I think we should have here also the unit tests? WDYT @poncovka ?

Sure. Why not.

**Comment by VladimirSlavik** [comment]
Normally I'd just merge this, but I can't exactly assign myself since I'm away, and it's acked but we want tests. No idea what to do here.

**Comment by jkonecny12** [comment]
@jstodola are you fine with creating also a unit tests or should we handle that for you?

**Comment by jstodola** [comment]
I will give it a try and ask for help if I fail.

**Comment by jstodola** [comment]
A unit test added.

**Pull request merged**
