### PR TITLE
network: wrap IP addresses showed in GUI for wireless devices (#1925781)

### PR DESCRIPTION
**Pull request by rvykydal**
Follow-up of commit fccd58ce29e69b7ed7572d8760c07f62356cbcdb

### CODE REVIEW

**Review by VladimirSlavik — COMMENTED** [review]
Just two characters? I am not sure how that looks...

**Comment by rvykydal** [comment]
> Just two characters? I am not sure how that looks...

IIRC in this context, which is IP addresses as strings (words) separated by a space it says: one IP address (word) per line.

**Comment by VladimirSlavik** [comment]
No? The [official docs](https://developer.gnome.org/gtk3/stable/GtkLabel.html#GtkLabel--max-width-chars) say that this is indeed in characters, just as the raw glade XML says. But there's a [lengthy SO answer](https://stackoverflow.com/questions/27462926/how-to-set-max-width-of-gtklabel-properly#34472033) which suggests this actually works differently.

**Review by VladimirSlavik — APPROVED** [review]

**Pull request merged**
