### PR TITLE
webui: When re-scanning don't reset disk selection

### PR DESCRIPTION
**Pull request by KKoukiou**
Instead keep selected disks if they are still usable.

Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=2231357#c3

### CODE REVIEW

**Comment by KKoukiou** [comment]
This needs some tests adjustments. Feel free to take over it if it needs to be in within the next 2 weeks that I am on PTO.

**Comment by rvykydal** [comment]
> This needs some tests adjustments. Feel free to take over it if it needs to be in within the next 2 weeks that I am on PTO.

I am making some of the test updates in https://github.com/rhinstaller/anaconda/pull/5116 but it is still WIP.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Pull request merged**
