### PR TITLE
Create downstream release changelog from GitHub releases (#infra)

### PR DESCRIPTION
**Pull request by jkonecny12**
Right now automated releases are created from a commits between the last release and the new one. That works good but if we want to play with formatting and removing something it's better to use GitHub releases than the commits.

### CODE REVIEW

**Comment by jkonecny12** [comment]
This PR is prepared to be merged later. Right now it's blocked because we still don't have nice GitHub releases which we would like to show in the changelog.

**Review by M4rtinK — APPROVED** [review]
Looks good to me as far as I can tell. :)

**Review by VladimirSlavik — APPROVED** [review]
Thanks!

The last automated release exploded, so we'd probably want to wait at least one sucecssful release to see if it works...

**Comment by jkonecny12** [comment]
Unblocked, last release looks great!

**Pull request merged**
