### PR TITLE
Remove screenshot support

### PR DESCRIPTION
**Pull request by M4rtinK**
Drop screenshot support in the GTK UI - it is not very useful (users need to many copy out resulting files) and this likely not often used. Also with many installations now running in VMs, it is usually easier to take a screenshot using the VM software screenshot function.

By dropping this functionality, we can remove the keybinder dependency as well as cleanup the code a bit.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thanks!

**Review by jkonecny12 — APPROVED** [review]

**Review by KKoukiou — APPROVED** [review]

**Comment by VladimirSlavik** [comment]
Looks like some import of SCREENSHOTS_DIRECTORY was left and now breaks...

**Pull request merged**
