### PR TITLE
Let DNF do its own substitutions

### LINKED ISSUE #493: Should DNF payload use it's substitutions?
https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/packaging/dnfpayload.py#L237 is a "_replace_vars" function.

DNF provides dnf.conf.substitutions which will pull in any DNF supported vars automatically.

This would allow for substitutions other than $basearch and $releasever while also moving the maintenance of expected vars out of anaconda.

### PR DESCRIPTION
**Pull request by jcpunk**
Resolves #493

### CODE REVIEW

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by jkonecny12** [comment]
Hello @jcpunk please fix this error:
```
************* Module ../pyanaconda/packaging/dnfpayload.py
W0611(unused-import): 23,0: : Unused import blivet.arch
```

**Comment by jcpunk** [comment]
Should be fixed up now.

**Comment by jcpunk** [comment]
hmmm, this has been stuck in pending check for a bit.....

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
It looked good before, there were errors but those errors where because of some other bugs which are resolved already.

If the check is stuck for some time you can try rebase. Sorry, it is not public, I hope it will be but we don't have enough time now to work on it.

**Comment by poncovka** [comment]
Hi, could you use `self._base.conf.substitutions` instead of `self._dnf_substitutions`? I don't think it is necessary to create a new instance of `dnf.conf.substitutions.Substitutions`. Also the substitution of `$releasever` does not work now, but the use of `conf` substitutions should fix that.

**Comment by jcpunk** [comment]
I've taken a quick stab at it.

**Comment by poncovka** [comment]
Looks good to me. Substitution works fine now. Thanks!

**Pull request merged**
