### PR TITLE
webui: custom mountpoint mapper refactor

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me as far as I can tell. :)

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

(Just one design note: maybe I'd make the rows separation more prominent (like thicker horizontal separation lines), the table looks quite column-y to me)

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Pull request merged**
