### PR TITLE
Remove instperf

### PR DESCRIPTION
**Pull request by M4rtinK**
This was added ~12 years ago in 4e5940ffc640f10d6901f6582db50899d58bc6c2 as an attempt to record memory usage & identify cause of OOM situations.

Unfortunately it is not documented anywhere and as far as I can tell (asking others in the team + Fedora QA/RTT) not used in at least a couple years.

So lets drop this & cleanup the source tree and our systemd targets and makefiles a bit.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by KKoukiou — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by AdamWill** [comment]
Um! We *do* use this. We have a [test in openQA](https://openqa.fedoraproject.org/tests/2272340) - the `memory_check` test - which boots with `debug` and uploads `memory.dat`, and the `check-compose` tool which generates the compose check reports parses that data and flags if memory use increases.

We have also used this in the past just manually to try and debug excessive memory usage by the installer.

**Comment by M4rtinK** [comment]
> Um! We _do_ use this. We have a [test in openQA](https://openqa.fedoraproject.org/tests/2272340) - the `memory_check` test - which boots with `debug` and uploads `memory.dat`, and the `check-compose` tool which generates the compose check reports parses that data and flags if memory use increases.
> 
> We have also used this in the past just manually to try and debug excessive memory usage by the installer.

I think I asked @kparal or someone else from the Brno section of Fedora QA about `instperf` & it looked like its not being used. Maybe I should have better worded it - something like memory usage profiling rather than the obscure name. Oops! :P

So I guess we should put it back, right ? :)

**Comment by AdamWill** [comment]
ideally yeah, if it's not *too* much of a maintenance burden. It's not critical, or anything, but it *has* been useful on occasion.

**Comment by AdamWill** [comment]
As expected, this has [broken the openQA test](https://openqa.fedoraproject.org/tests/2287595#step/_memcheck/5).

**Pull request merged**
