### PR TITLE
Allow reformatting of 'plain' btrfs volumes

### PR DESCRIPTION
**Pull request by vojtechtrefny**
Similar to previous support for btrfs subvolumes, this allows reusing the btrfs volume directly. Only btrfs volumes without subvolumes can be reused which allows using btrfs as a 'normal' single device filesystem instead of using subvolumes only.

---

This is one of the use cases that is not well supported in blivet -- from our point of view, btrfs is only "volume manager" so it's not very easy to use it just as a plain filesystem on top of a partition. This change allows "reformatting" the btrfs volume, which really means removing the volume and reformatting the parent devices.

Related: #4964

### CODE REVIEW

**Review by KKoukiou — APPROVED** [review]

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by KKoukiou** [comment]
I think the kickstart test failure is unrelated- I think you should re-try.

**Pull request merged**
