### PR TITLE
Container args cleanup

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This should unblock the container push error from today.

And hopefully make the whole works easier to read and maintain?

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Local testing seemed ok. Covered areas:
- unit tests - container build + run + push (should be the same for rpm tests)
- container scratch rpm build + live builder container build + live build (should be similar for boot.iso)
- release container build + release build

**Review by jkonecny12 — APPROVED** [review]
Thanks for fixing this issue and improving the code!

**Comment by VladimirSlavik** [comment]
Let's see what this breaks instead, I'd say...

**Pull request merged**
