### PR TITLE
webui: tests: port helpers to busctl and unselect all disks on teardown

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
I consider we should create some abstraction layer over dbus calls from python test code in the future as it seems these are very useful.

**Review by VladimirSlavik — APPROVED** [review]
Thank you, looks good to me.

I am starting to have second thoughts about manipulating the backend so freely, but that's not the change here, so never mind.

**Review by rvykydal — APPROVED** [review]
Thank you

**Pull request merged**
