### PR TITLE
Enable Fedora 36 tests on devel and release branches (#infra)

### PR DESCRIPTION
**Pull request by jkonecny12**

### CODE REVIEW

**Comment by jkonecny12** [comment]
Blocked by https://github.com/rhinstaller/anaconda/pull/3849 .

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]
Thank you!

**Comment by jkonecny12** [comment]
The `f36-release` branch error is expected because we don't have `f36-release` ci container. Reason for that is that pykickstart does not have support for F36 yet. Already filed an issue for that https://github.com/pykickstart/pykickstart/issues/396.

**Pull request merged**
