### PR TITLE
network: fix kickstart network --dhcpclass option

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1869224

### CODE REVIEW

**Comment by rvykydal** [comment]
Relies on NM support for the option.

**Review by jkonecny12 — APPROVED** [review]
LGTM. I really like to see cleanup fixes!

**Review by VladimirSlavik — APPROVED** [review]
+1

**Review by poncovka — APPROVED** [review]

**Comment by rvykydal** [comment]
PR with port to Fedora: https://github.com/rhinstaller/anaconda/pull/2832

**Pull request merged**
