### PR TITLE
rpmostreepayload: Reuse the local repo as a cache

### PR DESCRIPTION
**Pull request by cgwalters**
When doing kickstart installs (can happen for both bare metal PXE as well as
building cloud images), we currently end up redownloading all of the ostree
content, even though we have a version in the squashfs already.

However, the version we have may not be the version we want; the installer image
is typically built at a different/slower cycle from the ostree content.

But this is where a strength of libostree's content-addressed storage shines; we
can use the local repo as an object cache, and avoid fetching what we already
have.

This just enables the logic that lives in libostree.

Closes: https://github.com/rhinstaller/anaconda/issues/1117

### CODE REVIEW

**Comment by cgwalters** [comment]
This is a WIP since the API hasn't landed in libostree yet, but I tested this and it works nicely!

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by cgwalters** [comment]
The upstream PR was merged, removing WIP.  Note that I added a version check, so we'll work with both old and new versions.  Hence this should be safe to merge at any time.

libostree releases usually are on a 3-4 week cadence, so it'll be a week or two.

**Comment by cgwalters** [comment]
For reference the OSTree PR is: https://github.com/ostreedev/ostree/pull/982

**Pull request merged**
