### PR TITLE
Fix kickstart --dhcpclass option application

### PR DESCRIPTION
**Pull request by rvykydal**
Port of upstream fix https://github.com/rhinstaller/anaconda/pull/5563 which didn't make it into rhel10.

### CODE REVIEW

**Comment by rvykydal** [comment]
We need also to update related kickstart test in a way similar to https://github.com/rhinstaller/kickstart-tests/pull/1206

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Pull request merged**
