### PR TITLE
Allow to disable the Timezone module

### PR DESCRIPTION
**Pull request by poncovka**
Check whether the Timezone DBus module is enabled before it is used.
It might be disabled in the Anaconda configuration file.

(cherry-picked from a commit e579de3)

Related: rhbz#1834535

### CODE REVIEW

**Comment by poncovka** [comment]
kickstart --testtype smoke

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by poncovka** [comment]
kickstart --testtype smoke

**Comment by poncovka** [comment]
kickstart --testtype smoke

**Pull request merged**
