### PR TITLE
Prepare release notes for Fedora 35

### PR DESCRIPTION
**Pull request by poncovka**
Merge all release notes for F35 into one file.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. Thanks.

We should create some automatization for this. It should be trivial to do.

**Comment by poncovka** [comment]
> We should create some automatization for this. It should be trivial to do.

I think it will always need a human touch. I have changed the formatting and done some small edits in titles and paragraphs.

**Review by M4rtinK — APPROVED** [review]
Looks super nice, thanks a lot! :)

**Comment by jkonecny12** [comment]
> > We should create some automatization for this. It should be trivial to do.
> 
> I think it will always need a human touch. I have changed the formatting and done some small edits in titles and paragraphs.

That is a good point.

**Review by rvykydal — APPROVED** [review]
Thank you.

**Pull request merged**
