### PR TITLE
Drop old WiFi & geocoding based geolocation support

### PR DESCRIPTION
**Pull request by M4rtinK**
This code was developed in the initial stages of geolocation
support in Anaconda with the aim of providing an alternative
to purely IP based territory & timezone determination.

In was considered a prototype back then and was never documented as
something you can enable via the inst.geoloc boot option.

In the end we never did get to making the code production ready
while the IP based geolocation worked fine. Also all the WiFi
location and geocoding API URLs no longer work anyway.

So lets drop that old code & cleanup the docstrings a bit when we are at it.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Apart from the pylint complaints with unused imports, LGTM. Thank you!

```
W0611(unused-import):/tmp/anaconda/pyanaconda/geoloc.py:108,0: : Unused import dbus
W0611(unused-import):/tmp/anaconda/pyanaconda/geoloc.py:107,0: : Unused import urllib.parse
```

**Comment by M4rtinK** [comment]
@VladimirSlavik Pylint should be good to go.

**Review by jkonecny12 — APPROVED** [review]
Nice cleanup. Thanks!

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
