### PR TITLE
Enable bootloader hiding on RHEL

### PR DESCRIPTION
**Pull request by frozencemetery**
Signed-off-by: Robbie Harwood <rharwood@redhat.com>

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Hi Robbie, thank you! Can you please extend the commit message with a link to a bug so we can track the acks etc.? See: https://anaconda-installer.readthedocs.io/en/latest/contributing.html#commits-for-rhel-branches

**Comment by frozencemetery** [comment]
Updated.

**Review by VladimirSlavik — APPROVED** [review]
Code looks good to me, commit message now too. Thank you!

Acceptance is subject to ACKs on the bug of course...

**Comment by jkonecny12** [comment]
Tested on CentOS Stream and RHEL here https://github.com/rhinstaller/kickstart-tests/pull/722.

**Review by jkonecny12 — APPROVED** [review]
LGTM

**Pull request merged**
