### PR TITLE
Backport unit/rpm test fixes

### PR DESCRIPTION
**Pull request by martinpitt**
These are all cherry-picked from master. After that we will be able to run these tests in containers as well, and move them off Jenkins.

This is my first non-master PR, so please have an extra thorough look at the  branch target ("rhel-8" seems to be the active one, but there's also "rhel-8.0", "rhel8-alpha-branch", and "rhel8-branch"), and the labels.

### CODE REVIEW

**Comment by poncovka** [comment]
The branch is correct, but we will need an approved bug for these commits. @jkonecny12, could you take care of that, please?

**Comment by martinpitt** [comment]
@poncovka : OOI, why? Nothing here changes any runtime behaviour or the contents of the RPM.

**Comment by martinpitt** [comment]
I filed https://bugzilla.redhat.com/show_bug.cgi?id=1885635 and added a "Related:" tag to all commit messages. No code changes.

**Review by poncovka — APPROVED** [review]
Looks good to me.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
