### PR TITLE
Do not provide the anaconda-live subpackage on RHEL

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This should work, even if I have no idea what I'm doing...

Tested locally with rpm tests for both negated and non-negated condition.

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. I just wonder about the `live-env-deps` meta-package.

I guess we probably want to leave it here because of InitialSetup?

**Comment by VladimirSlavik** [comment]
Such a package does not exist. The deps metapackages we have are both used on boot.iso, so these remain.

**Comment by jkonecny12** [comment]
Oh my, I can't read today. My mistake.

**Pull request merged**
