### PR TITLE
Configure GRUB and zipl to use the "BootLoaderSpec" boot option configuration format

### PR DESCRIPTION
**Pull request by martinezjavier**
This PR is basically the same than PR #1545, that contains @vathpela patches to add BootLoaderSpec support to Anaconda.

The only differences are that it's based on top of the `rhel-devel` branch, and adds a `Resolves: rhbz#1615442` to the commit message as asked by @poncovka.

### CODE REVIEW

**Comment by poncovka** [comment]
Please also add `Related: rhbz#1615442` into messages of the other commits.

**Comment by martinezjavier** [comment]
@poncovka @jkonecny12 thanks for the review. Anything else missing for this PR to be merged?

**Comment by poncovka** [comment]
@martinezjavier, we are waiting for the compose to be ready.

**Comment by martinezjavier** [comment]
> @martinezjavier, we are waiting for the compose without grubby to be ready.

@poncovka we have moved `grubby` and `new-kernel-pkg` in RHEL to a `grubby-deprecated` package. And `grubby` is now a wrapper that modifies the BLS config files.

So I think we are all set for this change now.

**Pull request merged**
