### PR TITLE
Show all logs of failed unit tests (#infra)

### PR DESCRIPTION
**Pull request by poncovka**
Set the log level of unit tests to `UNSET` to get all messages.

(cherry-picked from a commit 541cb6e)

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]

**Comment by jkonecny12** [comment]
@jstodola could you please give us ACK here. To ignore missing bug?

**Review by jkonecny12 — APPROVED** [review]
Thanks for the backport.

**Review by jstodola — APPROVED** [review]
ACK.

**Pull request merged**
