### PR TITLE
Add AlmaLinux profile (master)

### PR DESCRIPTION
**Pull request by andrewlukoshko**

### CODE REVIEW

**Review by VladimirSlavik — COMMENTED** [review]
Thank you Andrew! Can you please drop the bug number? It's not relevant for upstream. Otherwise this one is good to go.

**Comment by andrewlukoshko** [comment]
@VladimirSlavik dropped

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

I won't merge immediately to give some time for others to comment.

**Pull request merged**
