### PR TITLE
infra: Use new github output syntax everywhere

### PR DESCRIPTION
**Pull request by VladimirSlavik**
SSIA...

Untested because of change volume.

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Thank you!

**Comment by M4rtinK** [comment]
Looking into the Cockpit CI failure. :)

**Comment by rvykydal** [comment]
Thank you, I've open PR to do the same in kickstar-tests repo: https://github.com/rhinstaller/kickstart-tests/pull/852

**Review by jkonecny12 — APPROVED** [review]

**Pull request merged**
