### PR TITLE
Translated strings

### PR DESCRIPTION
**Pull request by dashea**
The rhel7 bug still has some process to go through, but I'd like to go ahead and get this on f24 before string freeze.

### CODE REVIEW

**Comment by dashea** [comment]
Updated the help button commit to also translate the string used as the accessible name.

**Comment by M4rtinK** [comment]
Looks good to me & thanks for looking into that! :)

**Comment by Frodox** [comment]
+1 from bug reporter :)

**Comment by dashea** [comment]
Pushed to master, f24, and rhel7

**Pull request closed without merging**
