### PR TITLE
Rhel8 alpha branch remove btrfs support in kickstart

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Comment by rvykydal** [comment]
Removed unrelated stuff merged in the patch by accident.

**Comment by rvykydal** [comment]
The patch is related to pykickstart's https://github.com/rhinstaller/pykickstart/pull/206

**Comment by rvykydal** [comment]
Also added RHBZ tag

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by Conan-Kudo** [comment]
😭

**Comment by poncovka** [comment]
Jenkins, test this please.

**Comment by rvykydal** [comment]
Replaced by https://github.com/rhinstaller/anaconda/pull/1328

**Pull request closed without merging**
