### PR TITLE
Add Virtuozzo Linux profile to Anaconda

### PR DESCRIPTION
**Pull request by poncovka**
(cherry-picked from a commit 5c8d31a)

Resolves: rhbz#2067195

### CODE REVIEW

**Comment by poncovka** [comment]
Ported from https://github.com/rhinstaller/anaconda/pull/3975.

**Review by VladimirSlavik — APPROVED** [review]
Thanks!

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Pull request merged**
