### PR TITLE
Set up LD_PRELOAD for the Payloads module

### PR DESCRIPTION
**Pull request by poncovka**
The environment variable LD_PRELOAD needs to be set up during the start of
the Payloads module, but it needs to be dropped after that.

After the modularization, only the Payloads module should require LD_PRELOAD.

### CODE REVIEW

**Comment by sharkcz** [comment]
I did a quick test with Fedora-Rawhide-20200601.n.1 and an updates.img provided by @M4rtinK and GUI is up and working.

**Comment by poncovka** [comment]
Jenkins, test this please.

**Comment by sharkcz** [comment]
I think reference to https://bugzilla.redhat.com/show_bug.cgi?id=1722181 should be added.

**Comment by poncovka** [comment]
The commit messages are updated.

**Pull request merged**
