### PR TITLE
Don't use progressQ in the payload classes

### PR DESCRIPTION
**Pull request by poncovka**
Use the `_progress_cb` method instead.

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Review by VladimirSlavik — COMMENTED** [review]
I don't understand what this does without the other pieces. Or maybe I don't understand it at all...

**Comment by poncovka** [comment]
> I don't understand what this does without the other pieces. Or maybe I don't understand it at all...

I need to eventually replace `progress_message` with another callback that will be accessible only from the `pyanaconda.installation` module. This pull request makes sure, that the payload doesn't use `progress_message` directly, but it is actually `pyanaconda.installation` that sets this function as a callback.

**Comment by poncovka** [comment]
Rebased and tested.

**Pull request merged**
