### PR TITLE
webui: tests: multiple improvements: stop using ks file for spawning cockpit-ws

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
I like it. Thanks!

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

Just a small note about the commit messages. Header of the commit message should be less than 50 characters: https://git-scm.com/docs/git-commit#_discussion

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me, thank you!

**Comment by KKoukiou** [comment]
Rebased.

**Pull request merged**
