### PR TITLE
Add DNS search and ignore options from kickstart

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This is the anaconda part.

Blocked by waiting on https://github.com/pykickstart/pykickstart/pull/431, ~~which in turn is blocked by [rhbz#1656662](https://bugzilla.redhat.com/show_bug.cgi?id=1656662#c9)~~.

TODOs:
- [x] pykickstart PR opened: https://github.com/pykickstart/pykickstart/pull/431
- [x] pykickstart PR merged (tests will work)
- [x] pykickstart released (can merge)
- [x] release notes
- [x] testing
- [x] add tests

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Tested manually to work OK.

Blocked on pykickstart merge and release.

**Comment by VladimirSlavik** [comment]
> add tests

I don't think tests are actually needed. Pretty much none of the functions in the module have any :(

**Review by rvykydal — COMMENTED** [review]
I think we should also include the option in generated kickstart: https://github.com/rhinstaller/anaconda/blob/3b964f1b358ae76ebd52248aacdae87c1cf9cbac/pyanaconda/modules/network/nm_client.py#L1474.

**Comment by rvykydal** [comment]
> > add tests
> 
> I don't think tests are actually needed. Pretty much none of the functions in the module have any :(

I wouldn't insist on adding them in scope of this PR. We should add a new issue for adding unit tests for nm-client.py. Or maybe adding a test for `update_connection_ip_settings_from_ksdata` in scope of this BZ could be a nice start. 

Also we might want to add a kickstart test for the feature (or update an existing one but I didn't find any suitable in TESTTYPE="network" set). It would just do something like
```
check_device_config_value @KSTEST_NETDEV2@ DNS1 10.43.26.2 ipv4 dns "10.43.26.2;"
```
is done in https://github.com/rhinstaller/kickstart-tests/blob/eb975b25d14b75916bf2ea5d2c25af51080db305/network-autoconnections-httpks.ks.in#L100
The question is if we want a new test specific for this feature (having resources in mind), or if we use some existing, but a bit unrelated, one, like the `network-autoconnections-httpks`; or if we create some generic test for network options of similar nature. I'd maybe prefer the last option.

**Comment by VladimirSlavik** [comment]
Added the ks generation part, now (re-)testing manually

**Comment by VladimirSlavik** [comment]
Manual testing succeeded but needed rebasing ^

**Comment by VladimirSlavik** [comment]
> Or maybe adding a test for update_connection_ip_settings_from_ksdata in scope of this BZ could be a nice start.

Sounds good to me.

**Comment by rvykydal** [comment]
> > Or maybe adding a test for update_connection_ip_settings_from_ksdata in scope of this BZ could be a nice start.
> 
> Sounds good to me.

Thank you, looks good to me so far. I'll wait for the tests and finish the review.

**Comment by VladimirSlavik** [comment]
The tests won't run without pykickstart, so I'd perhaps get that merged?

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you!

**Comment by VladimirSlavik** [comment]
No longer blocked by pykickstart at all, except for propagation to mirrors.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Pull request merged**
