### PR TITLE
Fix stage2 as default sources

### PR DESCRIPTION
**Pull request by jkonecny12**
We should prioritize stage2 device as the default source. This is especially needed for DVD ISO because it is booting with inst.stage2 instead and we should use the DVD as the source for the default CDROM. The situation is even worse thanks to the fact that DVD ISOs are using inst.stage2=hd:...

Find stage2 device and test this device first during the auto-discover feature of CDRom source.

Backport of https://github.com/rhinstaller/anaconda/pull/2747.

### CODE REVIEW

**Comment by jkonecny12** [comment]
Unfortunately, this does not really work. I tested this on Fedora and the problem is that the pmem device is not mountable because it's already mounted. What is weird that the original mount is to /run/install/repo but as RO so it should not be the problem?

I have to dig deeper into this and why it's a problem on Fedora and not on RHEL...

**Comment by jkonecny12** [comment]
OK, might be problem of old blivet. When I downloaded new Fedora server DVD it seems to be working correctly.

Interesting thing is that blivet still returns bad device but this device has the correct data... 

```
Aug 20 17:16:07 fedora org.fedoraproject.Anaconda.Modules.Storage[1887]: DEBUG:blivet:resolved 'LABEL=Fedora-S-dvd-x86_64-33' to 'pmem0' (nvdimm)
```

```
[anaconda root@fedora ~]# ls -lh /dev/disk/by-label/Fedora-S-dvd-x86_64-33
lrwxrwxrwx. 1 root root 13 Aug 20 17:15 /dev/disk/by-label/Fedora-S-dvd-x86_64-33 -> ../../pmem0p1
```

```
Aug 20 17:16:07 fedora org.fedoraproject.Anaconda.Modules.Payloads[1888]: INFO:program:Running... mount -t iso9660 -o ro /dev/pmem0 /run/install/sources/mount-0000-cdrom
Aug 20 17:16:07 fedora org.fedoraproject.Anaconda.Modules.Payloads[1888]: DEBUG:program:Return code: 0
```

@vojtechtrefny is this correct behavior or it should not work like this?

**Comment by VladimirSlavik** [comment]
Can we reject the device on anaconda side when it has children, and search with that one excluded, or something similar?

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
I want to test this again soon because it seems that the problem was just with the old ISO.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
Working correctly on newer Server DVD.

**Pull request merged**
