### PR TITLE
Fix failing tests after nose dependency was removed from the spec

### PR DESCRIPTION
**Pull request by jkonecny12**
We removed this dependency from spec file in commit
2be2374

However, we missed that these dependencies are not yet installed by pip. Fix this issue now.

Also apply a small fix on the rpm tests execution which is required now.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thank you for fixing my breakage!

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
