### PR TITLE
Fix kickstart tests failure when loop device is not yet created

### PR DESCRIPTION
**Pull request by jkonecny12**
The loop device is not in the container automatically it has to be created first. Let's pre-create the loop 0 and 1 devices always before podman run.

Also add update of container images used by this workflow.

Tested [here](https://github.com/Test-anaconda-org/anaconda/runs/1663957864?check_suite_focus=true).

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks for the fix! :)

**Review by VladimirSlavik — COMMENTED** [review]
Changes look good to me, although I'm curious: Why is the linked test a keyboard one, if this affects network?

**Comment by jkonecny12** [comment]
> Changes look good to me, although I'm curious: Why is the linked test a keyboard one, if this affects network?

It's just one of the simplest :D.

**Review by VladimirSlavik — APPROVED** [review]
My bad, it's loop, not loopback :D

**Comment by jkonecny12** [comment]
Not your bad but my :D. I somehow mixed up those two.

**Comment by jkonecny12** [comment]
@poncovka  this should fix issue with running kickstart tests on Anaconda PR

**Pull request merged**
