### PR TITLE
Drop deprecated conf: kickstart_modules, addons_enabled

### PR DESCRIPTION
**Pull request by VladimirSlavik**
SSIA.

### CODE REVIEW

**Comment by jstodola** [comment]
This removal should be coordinated with the Image builder folks, since osbuild uses ` kickstart_module`:
https://github.com/osbuild/osbuild/blob/3343696a7b66316ca0ccfd936b12ca951d901eb7/stages/org.osbuild.anaconda#L37
See also https://bugzilla.redhat.com/show_bug.cgi?id=2023855#c5

**Comment by VladimirSlavik** [comment]
Thanks for linking that, I was wondering where to talk to them...

**Comment by VladimirSlavik** [comment]
Depends on https://github.com/osbuild/osbuild/pull/1320

**Pull request merged**
