### PR TITLE
Use the set up tasks in the image payload class

### PR DESCRIPTION
**Pull request by poncovka**
Run the `SetUpLocalImageSourceTask` and `SetUpRemoteImageSourceTask`
tasks to set up the source image for the installation.

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. Thanks!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Pull request merged**
