### PR TITLE
Add a PR template (#infra)

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Let's discuss.

See also:
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
I like that. Thank you!

**Comment by VladimirSlavik** [comment]
I looked at other projects and they usually also provide some template "fields" for the actual metadata, so that there aren't PRs with just the template as description. That's missing here, so I'll try to add that.

**Review by jkonecny12 — APPROVED** [review]
I really like this change. Thanks!

**Comment by VladimirSlavik** [comment]
Some inspiration: https://raw.githubusercontent.com/osbuild/osbuild-composer/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by VladimirSlavik** [comment]
This is how it looks now:

----

**Thank you** for your contribution!

Please check that your PR follows these rules:

* [ ] [**Code conventions**](https://anaconda-installer.readthedocs.io/en/latest/contributing.html#code-conventions). tl;dr: Follow PEP8, wrap at 100 chars, and provide docstrings.

* [ ] [**Commit message conventions**](https://anaconda-installer.readthedocs.io/en/latest/commit-log.html). tl;dr: Heading, empty line, longer explanations, all wrapped manually. If in doubt, write a longer commit message with more details.

* [ ] **Tests** pass and cover your changes. You can [run tests locally manually](https://anaconda-installer.readthedocs.io/en/latest/testing.html), or have them run as part of the PR. A team member will have to enable tests manually after inspecting the PR.
  *If you don't know how, ask us for help!*

* [ ] [**Release notes**](https://anaconda-installer.readthedocs.io/en/latest/contributing.html#release-notes) and **docs** if the PR adds something major or changes existing behavior.
  *If you don't know how, ask us for help!*

* [ ] **RHEL** rules: If your PR is for a `rhel-*` branch, pay special attention to commit messages. Make sure **all** commit messages include a line linking the commit to a bug, such as `Resolves: rhbz#123456`. For more information, see [the complete rules](https://anaconda-installer.readthedocs.io/en/latest/commit-log.html).
  *If you don't know how, ask us for help!*

Don't forget - *if you don't know how, ask us for help!*

And now that you read this all, you can delete it and type your own description of your changes :-)

**Comment by VladimirSlavik** [comment]
Oh yes, that would be sometimes useful too.

**Pull request merged**
