### PR TITLE
Raise KickstartValueError when encryption passphrase not specified

### PR DESCRIPTION
**Pull request by vojtechtrefny**
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1185466

### CODE REVIEW

**Comment by vpodzime** [comment]
I think these checks should go to pykickstart.

**Comment by linux-modder** [comment]
+1 for pykickstart

**Comment by mulkieran** [comment]
I am in favor of the pykickstart error-checking approach.

Unfortunately, it seems like the real bug is in the GUI, see: https://bugzilla.redhat.com/show_bug.cgi?id=1213096.

**Comment by dwlehman** [comment]
We used to prompt for missing passphrases using the anaconda UI. Is there some central switch in kickstart for whether to prompt or issue an error when such a piece of information is absent? There should be some consistency in this area.

**Comment by vojtechtrefny** [comment]
Some of the tests for this are in anaconda and some in pykickstarts. But I agree with Vratislav and others that we should test this in pykickstart.

**Comment by vojtechtrefny** [comment]
Opening this again. I think this actually should be in Anaconda, because using --encrypted without --passphrase is a valid kickstart input:

"If no passphrase is specified, the default system-wide one is used, or the installer will stop and prompt if there is no default."
https://github.com/vpodzime/pykickstart/blob/master-docs/docs/kickstart_docs.rst#part-or-partition

**Comment by vojtechtrefny** [comment]
Closed, new version: https://github.com/rhinstaller/anaconda/pull/174

**Pull request closed without merging**
