### PR TITLE
anaconda: add option to lock root account

### PR DESCRIPTION
**Pull request by fepitre**
Allow locking the root account in the password setting spoke.

### CODE REVIEW

**Comment by poncovka** [comment]
Jenkins, test this please.

**Comment by fepitre** [comment]
Jenkins seems happy. Is it normal that we cannot access to the build log? Above, in Show all checks, the links to Jenkins log are unavailable.

**Comment by jkonecny12** [comment]
Yes it is normal. Sorry about that, we are using inner infrastructure which is not public. We have a solution how to get logs outside, however, we don't have a time to implement that. :(

**Comment by M4rtinK** [comment]
I'll try to test this during this week.

**Comment by fepitre** [comment]
Thank you for your feedback. Indeed it looks like that currently and it would be better to put it under the confirm password field with some padding. I will do it soon.

**Comment by fepitre** [comment]
I edited the file under Glade. And put it below the confirmation box with an empty row. Is it enough?

**Pull request merged**
