### PR TITLE
Add class diagrams to hubs and spokes & fix some of a documentation compilation problems

### PR DESCRIPTION
**Pull request by jkonecny12**
Add class diagrams to existing hubs and spokes. I don't add these globally because they are waste of space in generated documentation if there are only few parents (also I didn't found where to setup that).

I lowered number of the documentation compilation errors and warnings.

Example:
class_diagram

### CODE REVIEW

**Comment by bcl** [comment]
This looks really nice! I like the idea of using targeted diagrams instead, usually they end up being too much of a mess to be useful.

**Comment by vpodzime** [comment]
Great! Big THANKS for this!

**Comment by bcl** [comment]
I forgot to ask, did you use ./scripts/make-sphinx-docs to test this? If there are more packages needed for the chroot, please add them there.

**Comment by jkonecny12** [comment]
I tested it with make html only, so I will look on it.
Thank you for the info.

**Comment by jkonecny12** [comment]
@bcl I found that the script needs graphviz package so I add it. Please look on it and give me ACK if it's ok.

I also found my error when one class have bad class for diagram. Fixed now.

**Comment by jkonecny12** [comment]
Pushed

**Pull request closed without merging**
