### PR TITLE
webui: reset storage backend before autopart test

### PR DESCRIPTION
**Pull request by rvykydal**
The test was failing during RETRY (caused by unrelated failure in the test) because of backend state initialization mode value changed by the previous try of the test.

### CODE REVIEW

**Comment by rvykydal** [comment]
> The tests used to pass for me locally, but that was before #4671. After the PR merge and reabase I was not able to run them locally, but I think they failed with another messages:
> 
> ```
> # ----------------------------------------------------------------------
> # testAutopartitioning (__main__.TestStorage)
> Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
> 127.0.0.1 - - [06/Apr/2023 12:01:01] "GET /updates.img HTTP/1.1" 200 -
> Failed to try-restart sssd.service: Unit sssd.service not found.
> [TEST STEP] open
> 
> DevTools listening on ws://127.0.0.1:10095/devtools/browser/4dc48892-8d5c-4245-9b9c-058c37605586
> ATTENTION: default value of option allow_rgb10_configs overridden by environment.
> [0406/120123.309416:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable. 
> [0406/120123.336322:WARNING:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
> (node:2373871) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.   
> (Use `node --trace-warnings ...` to show where the warning was created)
> /home/rvykydal/work/git/anaconda-webui.4/anaconda/ui/webui/test/common/chromium-cdp-driver.js:31
> import * as readline from 'node:readline/promises';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at Object.compileFunction (node:vm:360:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1084:15)
>     at Module._compile (node:internal/modules/cjs/loader:1119:27)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
>     at Module.load (node:internal/modules/cjs/loader:1033:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:22:47
> ```
> 
> Maybe I haven't re-synced all the stuff enough.

For the record, upgrade from F36 to F37 solved the issue for me.

**Review by VladimirSlavik — COMMENTED** [review]
I'm not sure if this is ready or not? The tests keep failing...

**Comment by rvykydal** [comment]
I'll rebase and re-run the tests, putting into Draft for now.

**Comment by rvykydal** [comment]
@VladimirSlavik the test have passed, ready for review

**Review by VladimirSlavik — APPROVED** [review]
Then of course LGTM, thanks!

**Pull request merged**
