### PR TITLE
webui: fix spacing of Storage Congfiguration options

### PR DESCRIPTION
**Pull request by rvykydal**
Addresses [INSTALLER-3450](https://issues.redhat.com/browse/INSTALLER-3450)

Screenshot from 2023-04-04 13-08-42

Screenshots: https://rvykydal.fedorapeople.org/webui/autopart_pr1/v1/screenshots/partitioning_spacing_update_v2/
Screencast: https://rvykydal.fedorapeople.org/webui/autopart_pr1/v1/screencasts/autopart_choices_alignment/Screencast%20from%2004-04-2023%2004:43:58%20PM.webm

Should improve this original state: https://rvykydal.fedorapeople.org/webui/autopart_pr1/v1/screenshots/Screenshot%20from%202023-03-08%2011-11-39.png

### CODE REVIEW

**Comment by lclay2** [comment]
I noticed the alignment issue, that @KKoukiou, mentioned as well. Is it possible to position the "Learn more" link in the same way that the kebab menu is on these examples?:
https://www.patternfly.org/v4/components/data-list/#width-modifiers

**Comment by rvykydal** [comment]
Yes, I noticed as well but thought it would be still good enough improvement for v1 update.
The alignment is better if I set the button as `isInline`:
Screenshot from 2023-04-05 10-18-41
compared to the current PR:
Screenshot from 2023-04-05 10-19-31
But for the `isInline` variant there is undesired line wrapping.
If only I knew how to make the button `isInline` non-wrapping :)

Definitely I'd like to fix the alignment but if it takes too much time I'd prefer this version (changing the layout of the alert to be below the option) before refining it. 

...

> Is it possible to position the "Learn more" link in the same way that the kebab menu is on these examples?:
https://www.patternfly.org/v4/components/data-list/#width-modifiers

The example is using `<Dropdown>` component with `<KebabToggle>` so I didn't find any hint how to align a button with "link" variant we are using.

**Comment by rvykydal** [comment]
Oh, there is maybe another approach, making the button DataListCell instead of DataListAction fixes the alignment, I just need to align the button to the right side:
Screenshot from 2023-04-05 10-52-16

**Comment by rvykydal** [comment]
> ... which is done by `isFilled={false}`, I'll update the PR

Done, the screenshots are in https://rvykydal.fedorapeople.org/webui/autopart_pr1/v1/screenshots/partitioning_spacing_update_v3/

Screenshot from 2023-04-05 11-16-41

**Comment by lclay2** [comment]
@rvykydal, I noticed an issue with the pointer focus position being off (~30 px?) throughout, I created a sub task for it.

**Review by VladimirSlavik — APPROVED** [review]
Code LGTM, thank you!

**Pull request merged**
