### PR TITLE
Add build of anaconda-iso-creator autobuild (#infra)

### PR DESCRIPTION
**Pull request by jkonecny12**
Autobuild container image for building of the ISO.

This is just a small draft quickly created to find out if we want to have such a thing.

Question to answer **are we fine to have this without tests?** The issue with running the build test is that you need to have KVM access which means not a GH runners.

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
There are no tests to run in the container, I think, so no problem not running them :)

However - why? The reason I ask is that the daily release rehearsals ("try release daily") build the container and actually use it, on all 3 main branches, so it's verified to be functional or raise an alarm.

If it's to maybe also push the container for master, that sounds like a good thing to try.

**Comment by jkonecny12** [comment]
That is great idea!

To answer the why question. Having this will simplify building of the images and make those more accessible. If you look on the discussion happening yesterday, people are confused that it's starting the download of the image and fail.

**Comment by M4rtinK** [comment]
> To answer the why question. Having this will simplify building of the images and make those more accessible. If you look on the discussion happening yesterday, people are confused that it's starting the download of the image and fail.

Yeah, that was super confusing - I was just following the docs & hit it right away. :P Nice to see this being addressed. :)

**Review by M4rtinK — APPROVED** [review]
LGTM. :)

**Comment by VladimirSlavik** [comment]
Maybe consider pushing the container after the release test instead?

**Pull request closed without merging**
