### PR TITLE
infra: Prepare templating to support RHEL-10

### PR DESCRIPTION
**Pull request by jkonecny12**
Current teplamting solution was to strict about having Rawhide, one Fedora and everything else was hardcoded. Intead of that let's change the logic to have a list of supported branches and this list will generate required tasks for each item on the list based on the data.

The main branch is not included because it helps us to recognize current branch.

**A few notable changes:**
* Solution for po update will now apply also for rhel-9 branch - this should be verified even thought it should work out of the box
* Dropping support from CI for rhel-8 which should be fine because rhel-8 won't get any new spins with the new installer
* Adding RHEL-10 branch support

**This have to be merged after RHEL-10 branch is created!**

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me as far as I can tell. :)

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
