### PR TITLE
Remove the timezone map from the Time & Date spoke

### PR DESCRIPTION
**Pull request by poncovka**
The timezone map was removed from the Time & Date spoke in the GKT-based user interface
and the spoke was redesigned to accommodate the changes. The installer no longer depends
on the the `libtimezonemap` package.

**TODO:**
- [x] Build and test a boot.iso.
- [x] Run kickstart tests for `time`.
- [x] Test the live media.

See: https://github.com/rhinstaller/anaconda/discussions/5355

### CODE REVIEW

**Comment by poncovka** [comment]
Redesign with NTP enabled:
timezone_redesign_ntp

Redesign with manual time enabled:
timezone_redesign_manual

**Comment by mairin** [comment]
> Redesign with NTP enabled: timezone_redesign_ntp
> 
> Redesign with manual time enabled: timezone_redesign_manual

This is looking great @poncovka !! The only thing I would suggest is maybe 3x the padding between the Time Zone region block and the Radio buttons, and between the radio buttons I'd probably do 2x the padding. I believe GTK padding according to the guidelines of this version of GTK was factors of 6. So maybe 18px padding between the two major blocks, and 12px padding between the radio button options.

**Comment by poncovka** [comment]
> So maybe 18px padding between the two major blocks, and 12px padding between the radio button options.

timezone_redesign_ntp_18_12

**Comment by mairin** [comment]
@poncovka The 2nd one with more padding - that's great!

**Comment by mairin** [comment]
Ah while we're here, sorry, one quick tweak if not a pain - a little more padding between the date dropdowns and the "/" characters inbetween the widgets... maybe just 6 px?

**Comment by poncovka** [comment]
> Ah while we're here, sorry, one quick tweak if not a pain - a little more padding between the date dropdowns and the "/" characters inbetween the widgets... maybe just 6 px?

Like this? I tried it with two different locales (`en_US` and `cs_CZ`):
timezone_us_time
timezone_cz_time

**Comment by mairin** [comment]
> > Ah while we're here, sorry, one quick tweak if not a pain - a little more padding between the date dropdowns and the "/" characters inbetween the widgets... maybe just 6 px?
> 
> Like this? I tried it with two different locales (`en_US` and `cs_CZ`): timezone_us_time timezone_cz_time

@poncovka this looks *fantastic* - how do you feel about it?

**Comment by poncovka** [comment]
> @poncovka this looks _fantastic_ - how do you feel about it?

I like is as well. Ok. Let's do that :-)

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by Conan-Kudo — APPROVED** [review]

**Comment by Conan-Kudo** [comment]
I mourn the loss in fanciness, but it looks good otherwise.

**Comment by ni-balexand** [comment]
> I mourn the loss in fanciness, but it looks good otherwise.

Indeed. I've enjoyed the ease-of-use behind just pointing and clicking. Scrolling through a long list of cities is annoying. The bigger problem I think, though, is that users who are not familiar with city-based time zones (i.e. don't know what city they should be associated with) might have a hard time finding the right one (e.g. a user in Austin needs to know to select Chicago).

This is not an improvement for the user, it's taking a step backwards. Why was this removed?

**Pull request merged**
