### PR TITLE
Don't install cppcheck on ELN (#infra)

### PR DESCRIPTION
**Pull request by VladimirSlavik**

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Needs testing.

**Review by poncovka — APPROVED** [review]
Thanks!

**Comment by VladimirSlavik** [comment]
The change is a success, but ELN container builds are broken anyway.

Compare logs for ELN CI container build:
- Dry run (plain master): https://github.com/vslavik-test-org/anaconda/actions/runs/1026160536
- This change: https://github.com/vslavik-test-org/anaconda/actions/runs/1026175636

Observe that:
- All of Fedora 34 fails (see #3484)
- ELN build of CI container stops at missing cppcheck, with the change at package conflict instead.
- Failure for other builds happens at login to registry, so these run correctly.

**Pull request merged**
