### PR TITLE
Use Firefox environment variables for styling

### PR DESCRIPTION
**Pull request by M4rtinK**
Use environment variables supported by Firefox to style how the Anaconda
Web UI Firefox window looks like.

Override the name in the header via the MOZ_APP_TITLE variable.
This is something that should ideally be translated in the future.

Also tune how the application is represented in the Gnome Shell overview mode,
by binding it to the data in the liveinst desktop file via the
MOZ_APP_REMOTINGNAME variable. Again, we will likely need to handle
translations of this in the future as well.

Resolves: rhbz#2230058
Resolves: rhbz#2235244
Related: rhbz#2231339

### CODE REVIEW

**Comment by M4rtinK** [comment]
So this is the how it looks like when the `MOZ_APP_TITLE` & `MOZ_APP_REMOTINGNAME` are used:
webui_custom_header_minimal
This is how it looks like in the "minimal" mode when Anaconda is launched directly from Gnome Initial Setup. I have not been able to enter the overview mode, so the only important thing here is the application window header, which apparently is being controlled by `MOZ_APP_TITLE`. Moving on to the regular Live session (accessible by the "Try" button in GIS).
webui_custom_header_try
The window looks the same when active - again custom app title set via  `MOZ_APP_TITLE`.
webui_custom_header_try_overview
When we switch to overview (by clicking on the activities button or pressing the windows key), we get this. Here we see `MOZ_APP_REMOTINGNAME` at work, pairing the app in overview to our `liveinst.desktop` file. As you can see, it shows two liveinst icons for some reason, instead of showing a white point under the icon to show there is a running instance. But I think that is a minor issue.
webui_custom_header_try_overview_highlight
When I highlight the app by placing a cursor on top of it, I get an app name - quite surprisingly we get the value from `MOZ_APP_TITLE` instead of something from the desktop file as I would expect. Still, I think this works for us.

**Comment by M4rtinK** [comment]
@garrett @halfline @jkonecny12 @allanday  So now that we can set the value in the header & focus text in overview, we need to decide what do we put there. :) Basically all the places where you see "ANYthing"  on the screenshots, we need to put something sensible.

BTW, what about translations ? Right now I would categorize this as not translatable, without considerable effort - this value is set in a bash script that we use to start Firefox and as far as I can tell, we just don't have support for integrating that with the translation machinery. It could likely by done, but I'm afraid it would not be trivial & is IMHO in the F40 territory.

**Comment by allanday** [comment]
> So now that we can set the value in the header & focus text in overview, we need to decide what do we put there.

The string I had in my mockups was "Fedora Installer". Or you could potentially have "Fedora Workstation 39 Installation" or similar.

I don't like the idea of having untranslated strings. At the same time, there needs to be a string there.

**Comment by jkonecny12** [comment]
Fedora installer seems good to me.

I wonder if we use the string from Anaconda then we can have it as translated string in Anaconda. However, that might change the approach of starting FF early... I will experiment a bit there.

**Comment by garrett** [comment]
I agree with @allanday — It should be a simple string with the OS followed by "Installer", and _ideally_ would be translated.

There are other options:
- It could be an empty string in the titlebar (but it'd need to have a title for the overview). It already has the "Fedora... Installer" title in the heading of the wizard.
- Alternatively, we probably could even drop the wizard heading and only rely on the titlebar for the name, but would have to find another place for the "..." menu. This is likely too big of a change for F39.

Both of these options are probably post-F39, if at all. The simplest solution for F39 is going with with Allan suggests.

**Comment by halfline** [comment]
> When we switch to overview (by clicking on the activities button or pressing the windows key), we get this. Here we see `MOZ_APP_REMOTINGNAME` at work, pairing the app in overview to our `liveinst.desktop` file. As you can see, it shows two liveinst icons for some reason, instead of showing a white point under the icon to show there is a running instance. But I think that is a minor issue.

Does putting StartupWMClass=liveinst in liveinst.desktop fix that?

**Comment by M4rtinK** [comment]
> Does putting StartupWMClass=liveinst in liveinst.desktop fix that?

I've added that, but it does not seem to have affect - there are still 2 icons when Anadonda is started.

But this has a caveat - I do install the patched Anaconda RPMs at runtime, after switching to desktop from GIS. So I'm wondering if perhaps this way some desktop file database is already generated and the new version of the desktop file perhaps gets ignored ? I'll try to build a full Live image with the change to see if it still behaves the same.

**Comment by halfline** [comment]
> But this has a caveat - I do install the patched Anaconda RPMs at runtime, after switching to desktop from GIS. So I'm wondering if perhaps this way some desktop file database is already generated and the new version of the desktop file perhaps gets ignored ? I'll try to build a full Live image with the change to see if it still behaves the same.

Yea the livecd scripts rename the desktop file to anaconda.desktop so just installing the rpm at runtime won't work

**Comment by M4rtinK** [comment]
> Yea the livecd scripts rename the desktop file to anaconda.desktop so just installing the rpm at runtime won't work

Oh well, then I guess we will just keep that line in place & hope it works as expected after a properly composed image is created on the Fedora infra.

I've tried to build a Live ISO using the Github Workflow we have for that, but unfortunately it does not work - it gets stuck showing the desktop at the moment when Gnome Initial Setup should show up. :P @jkonecny12 @VladimirSlavik

**Comment by M4rtinK** [comment]
Looks like getty is blocked, possibly by Gnome Initial Setup failing to start/getting stuck, so I can't even check what's going on. :P

**Comment by M4rtinK** [comment]
OK, so I've manually edited the generated `anaconda.desktop` & added `StartupWMClass=liveinst` and now it works:

Screenshot_fedora-rawhide_2023-09-07_14:01:24

And it should work also on regular images, where the liveinst.desktop (which we change) gets mangled into anaconda.desktop. :)

**Review by rvykydal — APPROVED** [review]
Looks good to me.
I had one concern - the situation with blivet-gui window open - if it wouldn't be harder to deal with possibly lost (hidden behind installer when clicking accidentally on installer window off the blivet-gui which is not fullscreen) blivet-gui window without the titlebar, but that is probably something to be addressed separately.

**Pull request merged**
