### PR TITLE
Revert "Add our repository with the new annobin package (#infra)"

### PR DESCRIPTION
**Pull request by KKoukiou**
This reverts commit bf5bccc6040835f7e3754f861cb31394e05240b9.

The bugzilla is long time fixed.

### CODE REVIEW

**Comment by KKoukiou** [comment]
This is currently blocked on dnf5 breakage.

**Comment by VladimirSlavik** [comment]
Sounds a bit contradictory. To fix the "bz no longer a problem", you want to remove the package from the repo, not remove the repo, I think. Maybe we don't need the repo as well, but then it might be better to write that instead?

**Review by VladimirSlavik — COMMENTED** [review]
Thank you, lgtm. I'm not in the chat so I will leave acking to somebody more in the loop, but no objections from me.

**Comment by VladimirSlavik** [comment]
@KKoukiou are you still interested in this? I just randomly stumbled on the same repo in packit config...

**Review by jkonecny12 — APPROVED** [review]
We did not used this option much so I guess we should remove it instead of keeping it around.

**Comment by VladimirSlavik** [comment]
It might be useful to grep for the repo in docs, I think.

**Pull request merged**
