### PR TITLE
Use RHEL9_SshKeyData to fix sshkey quoting problem

### PR DESCRIPTION
**Pull request by bcl**
Resolves: rhbz#2149362

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by jkonecny12** [comment]
I'm looking on the tests.

**Review by jkonecny12 — APPROVED** [review]
Sure, the tests are failing because new pykickstart is not in the repository yet.

**Comment by jkonecny12** [comment]
@bcl do you want to release Pykickstart and Anaconda together or (my preference) release pykickstart first and Anaconda after we run through the tests?

**Comment by jkonecny12** [comment]
Bug is ACKed now.

**Comment by bcl** [comment]
> @bcl do you want to release Pykickstart and Anaconda together or (my preference) release pykickstart first and Anaconda after we run through the tests?

I'm fine with releasing pykickstart first. It won't break anything since the old class is still present.

**Comment by jkonecny12** [comment]
We are now waiting till the pyckistart gets into nightly repositories.

**Comment by jstodola** [comment]
pykickstart-3.32.9-1.el9 from bug [2121877](https://bugzilla.redhat.com/show_bug.cgi?id=2121877) is now in RHEL-9.2 nightly.

**Comment by jkonecny12** [comment]
Thanks everyone for your help! It's ready for merge.

**Review by VladimirSlavik — APPROVED** [review]

**Comment by M4rtinK** [comment]
So I think I see some of these issues on my PR #4471 - issues with PYkickstart SSH command. So could we merge this now ?

**Pull request merged**
