### PR TITLE
Remove workflows for webui integration tests

### PR DESCRIPTION
**Pull request by VladimirSlavik**
These are not used any more, they are in the webui repo and merged with the regular tests.

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
I thought we want to maintain the status badges for the moved workflows to the new repository, just with adjusted links. See cockpit-lib-update.

As far the webui e2e tests workflow deletion, it's a bit unknown ground, as in the new repository there is not any script that builds ISOs, which these tests used to use.

But I agree, these dont belong here anymore.

**Comment by VladimirSlavik** [comment]
Right, I'll re-add the badge under a new heading.

**Review by KKoukiou — APPROVED** [review]
These do not run some months now, and when/if they are going to be reintroduced let's do that in the anaconda-webui repository.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Pull request merged**
