### PR TITLE
Show suggestions for an error caused by inconsistent sector sizes (#1955514)

### PR DESCRIPTION
**Pull request by poncovka**
Improve the error message caused by inconsistent sector sizes.

(cherry-picked from a commit 9927497)

Resolves: rhbz#1955514

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Pull request merged**
