### PR TITLE
Bump Cockpit version of testlib to 266

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Let's see what this does...

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
Cockpit testlib now includes https://github.com/cockpit-project/cockpit/commit/8284618023806c35edbde8ab654310a8ac16a54e 

This removed the need for the expect_load call, our tests need to be adjusted the same way this linked commit does adjust the tests.

**Review by KKoukiou — APPROVED** [review]
Waiting for the tests to confirm but this looks enough! Thanks!

**Comment by VladimirSlavik** [comment]
No kickstart tests for us today, I'm afraid.

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Comment by KKoukiou** [comment]
Copying from IRC: 

(08:34:20 AM) kkoukiou: vslavik[m]: Kalimera :) I need to merge your testlib bump PR as i need to bump testlib even more for [https://github.com](https://github.com/rhinstaller/anaconda/pull/4007)

**Pull request merged**
