### PR TITLE
infra: Remove scripts not usable with JIRA

### PR DESCRIPTION
**Pull request by jkonecny12**
These scripts would have to dramatically change and to my knowledge they are not used by anyone.

### CODE REVIEW

**Review by jstodola — APPROVED** [review]

**Review by VladimirSlavik — APPROVED** [review]
I don't use these, so no problem there. Others might have a different reply...

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Comment by jkonecny12** [comment]
I have confirmation from all the team members that these are not used. Let's safe us trouble and just drop these.

**Pull request merged**
