### PR TITLE
Add support for disabling modules via module --disable

### PR DESCRIPTION
**Pull request by M4rtinK**
Make it possible to disable modules via the module command --disable option.

Cherry-picked from: 1a01b7e33655de1bb4f95ceab8ae59c9008a75ac

### CODE REVIEW

**Comment by M4rtinK** [comment]
**NOTE:** Do not merge before Pykickstart PR https://github.com/dcantrell/pykickstart/pull/274 is merged and Pykickstart 3.21-1 is released for Fedora.

**Comment by M4rtinK** [comment]
I've looked at the CI failures and both are caused by PyKickstart PR not yet being merged and released.

**Comment by M4rtinK** [comment]
@dcantrell Looks like we are ready to go to have this merged & new release for Fedora created. Thanks in advance! :)

**Comment by dcantrell** [comment]
I am back in the office after traveling to Brno and then to Budapest for Flock.  I have been in the office now for 30 minutes and will get to this when I can today.  If not today, then another day later this week.  We do have DevConf this week so that may cause delays for me.

**Comment by M4rtinK** [comment]
@dcantrell Thanks for the build! :)

**Comment by M4rtinK** [comment]
jenkins, test this please

**Pull request merged**
