### PR TITLE
Fix bad IP checker in text installation

### PR DESCRIPTION
**Pull request by jkonecny12**
Fix for crash in text anaconda when user set illegal IP address.
Fix bad warning message when illegal IP is set.
Nameservers option can be now set with whitespaces.

*Updated PR https://github.com/rhinstaller/anaconda/pull/98.*
*Resolves bug (#1217393)*

### CODE REVIEW

**Comment by vpodzime** [comment]
Two things:
  1) we should avoid using ``map()`` as it is dangerous in combination with the switch from Python 2 to 
      Python3 -- use list/generator expressions instead

  2) the "invalid user name" error message should be specific for the *user* spoke and we should
      provide some generic error message about invalid input in the generic class

**Comment by jkonecny12** [comment]
1) ok I will change it with Martin as supervisor :)
2) I think you are right but IMHO it would be better to do it in special commit because it's not related to this issue (to change general message). I change only the network because it's related to this bug. It think it would be better to create special PR with this change.

**Comment by vpodzime** [comment]
Works for me.

**Comment by jkonecny12** [comment]
PR was updated. 
I consulted this with Martin and we think the list comprehensions is valid alternative here so map commands was replaced by this.

**Comment by vpodzime** [comment]
Looks good to me now. Thanks

**Comment by jkonecny12** [comment]
Pushed to master.
Thank you @vpodzime for your help.

**Pull request closed without merging**
