### PR TITLE
Create swap by default in RHEL-based installations (#1915297)

### PR DESCRIPTION
**Pull request by poncovka**
Don't apply changes from the commit 2c2feb4 to RHEL-based products.

Resolves: rhbz#1915297

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me and seems to work fine:
rhel_swap
Thanks a lot! :)

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Pull request merged**
