### PR TITLE
Port from RHEL9: Replace the deprecated syspurpose CLI tool with SetSysrpose DBus call

### PR DESCRIPTION
**Pull request by M4rtinK**
Use the SetSysrpose() RHSM DBus API method instead of the deprecated
syspurpose CLI tool.

(cherry picked from commit 992997f75e21dba61efea2774b911e3fd80201e4)

Resolves: rhbz#1939708

### CODE REVIEW

**Comment by M4rtinK** [comment]
Original RHEL 9 PR: #3412

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
