### PR TITLE
CI: Check that no commits forgot infra-reload (#infra)

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This will ensure that after each commit, state of the rendered files and templates is consistent.

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by VladimirSlavik** [comment]
Rebased.

**Comment by VladimirSlavik** [comment]
Now it works:
- successful run: https://github.com/VladimirSlavik/anaconda/actions/runs/3097848349/jobs/5015013264
- correctly failed run: https://github.com/VladimirSlavik/anaconda/actions/runs/3097822010/jobs/5014954345

**Pull request merged**
