### PR TITLE
Enforce /boot as separate partition on Silverblue

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Resolves: [rhbz#1862784](https://bugzilla.redhat.com/show_bug.cgi?id=1862784)

Many thanks to Vendy who told me what needs changing!

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Review by jkonecny12 — APPROVED** [review]
Looks great to me!

**Comment by poncovka** [comment]
It might be fixed in ostree.

**Comment by bam80** [comment]
I'm not happy with enforcing /boot as mount point. It's a serious drawback. So +1 for ostree solution or whatever..

**Comment by VladimirSlavik** [comment]
Jenkins, test this please.

**Comment by VladimirSlavik** [comment]
@cgwalters is this actually needed? @cmurf pointed [in the BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1862784#c10) to https://github.com/ostreedev/ostree/pull/2149 as possible fix...

**Comment by cgwalters** [comment]
Yes, it shouldn't be required anymore but it isn't heavily tested either yet.

**Comment by VladimirSlavik** [comment]
Thanks! I read that as: Ostree handles /boot on / now, and this PR is not needed anymore. Is that correct for rawhide, f33, both, or neither?

**Pull request closed without merging**
