### PR TITLE
Always set system purpose from the GUI

### PR DESCRIPTION
**Pull request by M4rtinK**
Fix the issue of system purpose not being set if the system is re-registered - registered first without system purpose being set, unregistered and registered again with system purpose *being* set.

Also fixup some outdated system purpose related strings I've noticed when looking into this.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]
Looks good to me.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Comment by M4rtinK** [comment]
Port to Fedora: #4314

**Pull request merged**
