### PR TITLE
Port rhel 38451 bond port profiles rhel 10

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Comment by rvykydal** [comment]
The test `/kickstart-test --kstest-pr 1262 --testtype network` passed:
https://github.com/rhinstaller/anaconda/actions/runs/10061395227/job/27811367822

**Review by jkonecny12 — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Pull request merged**
