### PR TITLE
webui: improve custom mountpoint assigment

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
This is wrong - no need to review- will think more about it on monday.

**Comment by rvykydal** [comment]
The four commits related to LUKS look good to me. I think it would be easier to get them in and open (rebase) a separate PR for the fifth (the requests) on top of them? Anyway, I'll look at the requests as well.

**Review by rvykydal — APPROVED** [review]
Looks good to me. Both the LUKS and requests parts.

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Pull request merged**
