### PR TITLE
Clean up the DNF payload class

### PR DESCRIPTION
**Pull request by poncovka**
Move or remove some parts of the DNF payload class.

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

However, I don't really agree with the last commit to remove ``needs_storage_configuration``. I understand why you are doing this hence I won't block this PR but it's much harder to read the code now.

**Comment by poncovka** [comment]
> However, I don't really agree with the last commit to remove `needs_storage_configuration`. I understand why you are doing this hence I won't block this PR but it's much harder to read the code now.

It is not ideal, but its just a temporary solution. Eventually, this should be solved via dependencies between tasks.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by poncovka** [comment]
Rebased.

**Pull request merged**
