### PR TITLE
Move the support for FIPS to the Security module

### PR DESCRIPTION
**Pull request by poncovka**
Run new installation tasks of the Security module to set up the FIPS mode.

### CODE REVIEW

**Review by VladimirSlavik — DISMISSED** [review]
Looks good to me. Thank you!

**Review by jkonecny12 — DISMISSED** [review]
LGTM!

**Comment by poncovka** [comment]
Rebased and tested.

**Review by jkonecny12 — APPROVED** [review]
Still looks good to me!

**Pull request merged**
