### PR TITLE
Added optional [/prefix] as pattern

### PR DESCRIPTION
**Pull request by KosiehBarter**
Resolves rhbz#1267353

Signed-off-by: Karel Valek <kvalek@redhat.com>

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by jkonecny12** [comment]
To stay consistent please change the RHBZ to lowercase.

**Comment by bcl** [comment]
> To stay consistent please change the RHBZ to lowercase.
>  Hide all checks

It isn't just consistency, our scripts actually only allow lower case.

**Comment by jkonecny12** [comment]
Ahh actually, it's nice to know.

**Comment by dashea** [comment]
Closing the PR since this was pushed as 4de2e850a067d65ac05afe2e2655a5755b94c558. Cherry-picked to master while I was at it.

**Pull request closed without merging**
