### PR TITLE
Add support for booting installation media with plain SquashFS

### PR DESCRIPTION
**Pull request by bkhomuts**
This patch allows booting the image even if it's SquashFS images/install.img
does not contain the embedded rootfs.img in it.
In dracut documentation, this is called direct compression of the root filesystem.

In case the plain SquashFS is found, the filesystem is mounted as overlay.
Otherwise, the current method of mounting the /dev/mapper/live-rw applies.

An example of a netinstall image with the plain SquashFS:
https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20200828.n.0/compose/Server/x86_64/iso/Fedora-Server-netinst-x86_64-Rawhide-20200828.n.0.iso

The following problem is solved by this change:
```
Starting dracut mount hook...
dracut-mount: mount /sysroot: special device /dev/mapper/live-rw does not exist
Entering emergency mode...
```

The simplest way you can test this change is by interrupting the boot process,
And editing the /usr/lib/anaconda-lib.sh
You can interrupt the boot process by adding rd.break=pre-udev kernel argument.

The plain SquashFS is already supported if the image is Live. But because non-Live images
use a different code path for mounting the root filesystem, this change is needed.

The following patch relates to the following change proposal:
https://fedoraproject.org/wiki/Changes/OptimizeSquashFS

### CODE REVIEW

**Comment by poncovka** [comment]
Jenkins, test this please.

**Review by poncovka — COMMENTED** [review]
The code looks good to me. Thanks!

**Comment by jkonecny12** [comment]
Test fail is solved by https://github.com/rhinstaller/anaconda/pull/2824 .

**Review by jkonecny12 — COMMENTED** [review]
Looks good to me too. Thanks for this improvement!

**Comment by jkonecny12** [comment]
I see that you have the change set on F33 but it's not accepted. I guess this should be changed to F34 but if you really want to add this to F33 then please change target branch to f33-devel.

**Review by bcl — APPROVED** [review]
Looks good to me. I've built a new boot.iso using this and it boots and installs just fine. Also tested building a non-squashfs-only iso which continues to work as before. Thanks!

**Comment by jkonecny12** [comment]
Thanks a lot for testing this @bcl !

**Comment by jkonecny12** [comment]
jenkins, test this please

**Review by jkonecny12 — APPROVED** [review]
I believe @bcl tested it properly and the code looks good to me so from my PoV  we are free with the merge here.

**Comment by bkhomuts** [comment]
> I guess this should be changed to F34 but if you really want to add this to F33 then please change target branch to f33-devel.
@jkonecny12 , I'd like this change to be included in both master and Fedora 33 (if possible).

Just in case, I filed a separate pull request for f33-devel: https://github.com/rhinstaller/anaconda/pull/2829

**Comment by jkonecny12** [comment]
The ``f33-devel`` branch is automatically merged to ``master`` so you don't have to have two PR's created.

However, until this is accepted as F33 change I would avoid closing this PR or merging ``f33-devel`` one to avoid confusion on re-opening/closing issues. So for now, let's wait on FESCO and please ping us here when the change will have result.

**Comment by bkhomuts** [comment]
@jkonecny12 , I see. Thanks for explaining.

I'd like to share my perspective: this patch relates https://fedoraproject.org/wiki/Changes/OptimizeSquashFS, but does not depend on it.

Therefore I'd recommend merging this change if the merge window is still open for Fedora 33. This is because the user might try building the image using `--squashfs-only` option of `lorax` or `livemedia-creator`. Without this patch in place, the user will find the resulting ISO unbootable.

Also, this patch does not affect existing behavior of Anaconda, so even if the Change proposal is not accepted in Fedora, nothing will change for the end user.

**Comment by jkonecny12** [comment]
Thanks a lot for explanation. Seems reasonable to me. If it's just for people who creates image manually and not the default I don't see a reason to block this. 

Closing this PR because as explained above the f33 branch will be merged to master so merging both would just create unnecessary commit duplication.

**Pull request closed without merging**
