### PR TITLE
Remove support for the LUKS version selection from GUI

### PR DESCRIPTION
**Pull request by poncovka**
All widgets for the LUKS version selection were removed from the "Manual Partitioning"
screen of the GTK-based graphical user interface. The installer will use the ``luks2``
version by default for all new devices and keep the LUKS version of existing ones. Use
the kickstart support or Blivet GUI to select the LUKS version.

### CODE REVIEW

**Comment by poncovka** [comment]
Here are screenshots with the changes:
luks_version_standard
luks_version_container

**Comment by poncovka** [comment]
I have fixed the position of the "Encrypt" checkbox in the Container dialog. It looks better this way:
luks_version_container

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Review by jkonecny12 — APPROVED** [review]
Looks great to me. Thanks!

**Pull request merged**
