### PR TITLE
kickstart: "clearpart --list" does not work (#1410335)

### PR DESCRIPTION
**Pull request by mtelka**
Resolves: rhbz#1410335

### CODE REVIEW

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by jkonecny12** [comment]
Thanks for your contribution but to be able to merge this to RHEL we need a bug in bugzilla on RHEL. Without that we can't merge that. 
Bug you have in your commit is filed on Fedora and that is not enough.

**Comment by mtelka** [comment]
Cloned 1410335 as 1561930 for RHEL.

**Comment by mtelka** [comment]
Done. Thanks.

**Pull request merged**
