### PR TITLE
Fix issues with fetching pull requests.

### PR DESCRIPTION
**Pull request by dashea**
The "base" SHA is not actually where the pull request branched from,
though that would be pretty handy. Instead of trying to find a point to
branch from, just fetch the PR branch into a new local branch and rebase
that onto the destination branch.

### CODE REVIEW

**Comment by vpodzime** [comment]
Fixes the issue I had with merging PR #46. Thanks!

**Comment by vpodzime** [comment]
> Fixes the issue I had with merging PR #46. Thanks!
On the other hand ``$ scripts/merge-pr https://github.com/rhinstaller/anaconda/pull/46`` now does nothing in my git repo

**Comment by vpodzime** [comment]
The changes look good to me. So if we still want it, let's rebase and push it.

**Comment by dashea** [comment]
There was some issue with this last version but I can't remember what it is anymore. I'll take a look at it next week or so.

**Comment by dashea** [comment]
I'm going to stop pretending I'm about to work on this any time soon. There was some issue with the commit id I was using for the base of the merge/rebase, and if I ever fix that I'll open a new PR.

**Pull request closed without merging**
