### PR TITLE
Rpmostreepayload honor nosslverify

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by cgwalters** [comment]
I should note that these patches were based on the `anaconda-22.16-1` branch as that's the latest package I had in an ISO build.  But not too much relevant to this has changed on master AFAICS.

**Comment by dashea** [comment]
Rebased onto master and merged

**Comment by adityashah1212** [comment]
Can you please backport this to rhel7?

**Comment by jkonecny12** [comment]
Hello, @adityashah1212 , the same as I wrote you in the issue. To be able to backport this you need to create bug on bugzilla.

**Pull request closed without merging**
