### PR TITLE
Mark error message for missing usable disks for partitioning as translatable

### PR DESCRIPTION
**Pull request by KKoukiou**
To start translating this notification.

Screen Shot 2022-03-31 at 09 55 12

### CODE REVIEW

**Comment by KKoukiou** [comment]
Now that i think of it, a more proper way would be to disable the 'next" button if no disks are selected.

**Review by poncovka — APPROVED** [review]
Thank you!

**Comment by KKoukiou** [comment]
Hmm this does not work https://logs.cockpit-project.org/logs/pull-3997-20220331-130205-bcaf65f2-fedora-rawhide-boot/TestStorage-testLocalStandardDisks-fedora-rawhide-boot-127.0.0.2-2501-FAIL.png

**Review by poncovka — APPROVED** [review]

**Pull request merged**
