### PR TITLE
widgets: disable glade in RHEL builds

### PR DESCRIPTION
**Pull request by yselkowitz**
* [ ] [**Code conventions**](https://anaconda-installer.readthedocs.io/en/latest/contributing.html#code-conventions). tl;dr: Follow PEP8, wrap at 100 chars, and provide docstrings.
* [ ] [**Commit message conventions**](https://anaconda-installer.readthedocs.io/en/latest/commit-log.html). tl;dr: Heading, empty line, longer explanations, all wrapped manually. If in doubt, write a longer commit message with more details.
* [ ] **Tests** pass and cover your changes. You can [run tests locally manually](https://anaconda-installer.readthedocs.io/en/latest/testing.html), or have them run as part of the PR. A team member will have to enable tests manually after inspecting the PR.
* [ ] [**Release notes**](https://anaconda-installer.readthedocs.io/en/latest/contributing.html#release-notes) and **docs** if the PR adds something major or changes existing behavior.
* [ ] **RHEL** rules: If your PR is for a `rhel-*` branch, pay special attention to commit messages. Make sure **all** commit messages include a line linking the commit to a bug, such as `Resolves: rhbz#123456`. For more information, see [the complete rules](https://anaconda-installer.readthedocs.io/en/latest/commit-log.html).

glade is unwanted in RHEL 10: https://github.com/minimization/content-resolver-input/pull/996

ELN scratch build: https://koji.fedoraproject.org/koji/taskinfo?taskID=108369615

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Thank you. Is the widgets-devel package useful for anything, if glade is missing?

**Comment by yselkowitz** [comment]
Yes, compiling and linking against libAnacondaWidgets.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by jkonecny12 — APPROVED** [review]
Looks good to me from the code perspective. Thanks for the change.

**Pull request merged**
