### PR TITLE
Use the LUKS device for swap in fstab

### PR DESCRIPTION
**Pull request by dashea**
This is a cherry-pick of 46ecba5aff140cd13bebce483e2dcecd3cd7dbca to rhel7-branch.

### CODE REVIEW

**Comment by dwlehman** [comment]
Shouldn't there be a similar change to `RaidData`?

**Comment by dashea** [comment]
Yeah. I suppose I ought to create a couple of kickstart tests for this, too

**Comment by dashea** [comment]
Added a commit for RaidData which is also needed on master.

**Comment by dwlehman** [comment]
Looks good t o me. I'm jealous of whoever will get the honor of rewriting the storage bits of `pyanaconda.kickstart` one day.

**Comment by dashea** [comment]
Pushed, and cherry-picked the second commit to master.

**Pull request closed without merging**
