### PR TITLE
Configure the multilib policy of the target system (#1962026)

### PR DESCRIPTION
**Pull request by poncovka**
Write the multilib policy into the DNF configuration of the target system.

Resolves: rhbz#1962026

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by poncovka** [comment]
Implemented tests.

**Comment by poncovka** [comment]
Ported in https://github.com/rhinstaller/anaconda/pull/3487.

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Pull request merged**
