### PR TITLE
dockerfile: stop using non-existing po-pull target (#infra)

### PR DESCRIPTION
**Pull request by KKoukiou**
Commit 593adf59204a81dd45d76a11e53acf21f725a001 removed this
target. No po files are pulled automatically on make dist.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by jkonecny12 — APPROVED** [review]
Looks great to me. Thanks!

**Review by jkonecny12 — APPROVED** [review]
Although, please add `(#infra)` to end of the commit header.

**Pull request merged**
