### PR TITLE
Fallback to Wayland if Xorg is not available

### PR DESCRIPTION
**Pull request by M4rtinK**
In environments where Anaconda handles the overall GUI environment setup (eq. netinst/boot.iso) try to use Wayland compositor if Xorg server is not found.

Also add support for a (temporary?) boot inst.wayland boot option, that can be used to force Wayland compositor to be used. This makes it possible to check if Waland can be used in the given environment even if the given installation image still contains Xorg.

**Very preliminary PR at the moment**

**TODO**

- [ ] find out why `gnome-kiosk` exits with RC == 1 without logging any errors
- [ ] resolve all #FIXME lines

### CODE REVIEW

**Comment by M4rtinK** [comment]
gnome_kiosk_rc_1
Not sure what's going on right now - haven't found any error messages in the logs from gnome-kiosk. It is invoked like this: `gnome-kiosk --wayland-display :1 --sm-disable --wayland`

**Comment by M4rtinK** [comment]
Lets try adding `gnome-session` as a dependency & build a boot iso with that. :)

**Comment by M4rtinK** [comment]
Try adding python3-pam to the image.

**Comment by M4rtinK** [comment]
Looks like XWayland (xorg-x11-server-Xwayland) is not installed on the boot.iso - lets pull that in. :)

**Comment by M4rtinK** [comment]
Lets add a temporary script from @halfline & a PAM profile to the Anaconda package temporarily, so that we can build a self-contained image containing all this. This should help Ray & others with debugging this thing without setting up the full updates image tooling.

**Comment by M4rtinK** [comment]
Lets temporarily bump generated boot iso size to make gdb debugging possible.

**Comment by aleasto** [comment]
You don't need a `run-in-new-session.py` script as systemd has the infrastructure to create sessions using logind and pam.

See how I proposed doing it for initial-setup: https://github.com/rhinstaller/initial-setup/pull/149/files#diff-308726e1612232677c7e116a42550a8f3e3f66e326bcc4f32863d93fec9d9c06

This is [documented](https://wayland.pages.freedesktop.org/weston/toc/running-weston.html#running-weston-from-a-systemd-service) in the weston wiki, although arguably a bit overcomplicated

**Pull request closed without merging**
