### PR TITLE
Add efi_dir to the BaseInstallClass (#1412391)

### PR DESCRIPTION
**Pull request by poncovka**
Attribute efi_dir should be defined in BaseInstallClass as well.

Also, it doesn't make sense to use hidden install classes. If we cannot
use a visible install class, we should raise an exception.

Resolves: rhbz#1412391

### CODE REVIEW

**Comment by poncovka** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by M4rtinK** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
Please fix the failing test.

**Comment by poncovka** [comment]
Fixed tests and added a default install class.

**Pull request merged**
