### PR TITLE
webui: tests: extend storage test to validate the disk table rows content

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
Please ignore this for now, I am trying to resolve some issue on the tests.

**Comment by KKoukiou** [comment]
This fixes the reason webui tests on other PRs are broken right now. For example https://github.com/rhinstaller/anaconda/pull/4014

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Pull request merged**
