### PR TITLE
test: Update pixel references to current Fedora

### PR DESCRIPTION
**Pull request by martinpitt**
tasks container got updated to current Fedora in https://github.com/cockpit-project/cockpituous/pull/532 which updated font rendering. This causes some jitter in the reference images.

-----

See https://github.com/cockpit-project/bots/pull/4076

### CODE REVIEW

**Comment by martinpitt** [comment]
Hmm, apparently I did that wrong? I used `test/common/pixel-tests push`, which said
```
❱❱❱ test/common/pixel-tests push
M	TestInstallationProgress-testBasic-installation-progress-step-fail-pixels.png
M	TestLanguage-testLanguageSwitching-language-step-basic-pixels.png
M	TestReview-testBasic-review-step-basic-pixels.png
M	TestStorage-testLocalStandardDisks-storage-step-basic-pixels.png
From https://github.com/rhinstaller/pixel-test-reference
 * [new branch]      empty      -> empty
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 205.18 KiB | 2.14 MiB/s, done.
Total 7 (delta 0), reused 2 (delta 0), pack-reused 0
To github.com:cockpit-project/pixel-test-reference
 * [new tag]         sha-9038848d25127e48276549f7fea27ec8a83db236 -> sha-9038848d25127e48276549f7fea27ec8a83db236

The test/reference link has changed.  The next step is to commit and
push this change, just like any other change to a file.
```

That's the only change required by other cockpit projects. But indeed the [diff link](https://github.com/rhinstaller/pixel-test-reference/compare/f11334dea1b897716d6c479a07f930c2cb462ba3..9038848d25127e48276549f7fea27ec8a83db236) here does not work and says "nothing to compare". How to update pixel references in anaconda?

**Comment by martinpitt** [comment]
Oh, I think I know why -- It pushed the pixel refs to *cockpit-project*/pixel-test-reference, not *rhinstaller*/. And I can't:
```
❱❱❱ git push git@github.com:rhinstaller/pixel-test-reference sha-9038848d25127e48276549f7fea27ec8a83db236
ERROR: Permission to rhinstaller/pixel-test-reference.git denied to martinpitt.
```

Sorry, someone else needs to do that:

    test/common/pixel-tests fetch https://cockpit-logs.us-east-1.linodeobjects.com/pull-4076-20221117-224539-55b7624d-fedora-rawhide-boot-rhinstaller-anaconda/

and then push it to Anaconda.

@M4rtinK , @KKoukiou can you help? Thanks!

**Comment by jkonecny12** [comment]
Hi @martinpitt you should have an invite to the project.

**Comment by martinpitt** [comment]
Thanks @jkonecny12 ! Pushed the refs, and the test is happy now. @M4rtinK, @jkonecny12 , @KKoukiou , can you please trigger the remaining required tests and land this? This is quite urgent, as it blocks every other Anaconda PR. Thanks!

**Review by KKoukiou — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Pull request merged**
