### PR TITLE
Enable COPR build for Fedora 35

### PR DESCRIPTION
**Pull request by jkonecny12**
We would like to have daily builds of the Anaconda for f35-devel branch. Packit will handle that.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by jkonecny12** [comment]
* Fix packit configuration file.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by poncovka — APPROVED** [review]

**Pull request merged**
