### PR TITLE
Fix a problem introduced by a cherry-pick

### PR DESCRIPTION
**Pull request by dashea**
Resolves: rhbz#1317558

### CODE REVIEW

**Comment by jkonecny12** [comment]
Could you please (for my curiosity) show me which cherry-pick introduced this problem?

**Comment by dashea** [comment]
b12b57192f1d3b9eefc81413c96ffdfeb85a2092

So this could also be pushed as Related 1274855

**Comment by jkonecny12** [comment]
Yes please, it would be nice for transparent history.

**Comment by dashea** [comment]
Pushed.

**Pull request closed without merging**
