### PR TITLE
Remove all support of the built-in help system

### PR DESCRIPTION
**Pull request by poncovka**
The support of the built-in help accessible from spokes and hubs of all user interfaces is removed. The `help_directory` Anaconda configuration option is deprecated and removed. The `anaconda-user-help` package will be deprecated and removed.

Anaconda will aim to make user interfaces self-descriptive and encourage users to use the official documentation of specific Linux distributions available on-line.

**Additional notes:**

* The Fedora built-in help content was outdated. Last change of the content happened six years ago (see the `anaconda-user-help` repository) and there is no process for keeping the help content up to date.

* The RHEL built-in help content was generated from the official on-line installation guide. However, the release process of this content wasn't always straightforward and there were issues with the scripts that generated this content.

* The built-in help content was displayed by the `yelp` tool. This tool was a common source of bugs, so it is desirable to drop this dependency.

Resolves: #INSTALLER-3758

**TODO:**

- [x] Write a release note.
- [x] Verify the impact on Anaconda add-ons, Anaconda Initial Setup and Blivet GUI. 
- [x] Test the changes.

### CODE REVIEW

**Comment by poncovka** [comment]
@AdamWill Just a heads up, it might break the Fedora QA tests.

**Review by KKoukiou — APPROVED** [review]
Dont forget to deprecate the package:
https://docs.fedoraproject.org/en-US/packaging-guidelines/deprecating-packages/#_marking_a_package_deprecated
https://src.fedoraproject.org/rpms/anaconda-user-help/blob/rawhide/f/anaconda-user-help.spec

**Comment by AdamWill** [comment]
Release criteria updated, wiki test case marked obsolete, openQA test case removed.

**Pull request merged**
