### PR TITLE
Add centos module to pyanaconda

### PR DESCRIPTION
**Pull request by jaymzh**
No reason for this to be patched in by centos or anyone else,
that's why it's modular!

### CODE REVIEW

**Comment by jkonecny12** [comment]
Hello @jaymzh , 

I don't know exactly which CentOS version you are targeting but in case you don't know this workflow. 
If you want this patches to CentOS 7, you need to create this PRs for the rhel7-branch too and also create bugs in https://bugzilla.redhat.com/ to get this patches to a RHEL release. 
All the RHEL commits then must have ``Related: rhbz#<bz-number>`` or ``Resolves: rhbz#<bz-number>`` in the commit message.

Thank you for your patches.

**Comment by jaymzh** [comment]
@jkonecny12  - we only need it in master. This is part of the work we're doing with Redhat to get master to be able to install older versions. You can talk to @vathpela or @dcantrell about it for extra context.

**Comment by jkonecny12** [comment]
Ahh OK, then you can ignore it ;)

**Comment by snbueno** [comment]
This looks ok to me, but I want at least one other person on the team to add their ack as well.

**Pull request merged**
