### PR TITLE
Update makebumpver for current process

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by jstodola — APPROVED** [review]

**Comment by VladimirSlavik** [comment]
Do you want to tag this PR as infrastructure too?

**Comment by rvykydal** [comment]
> Do you want to tag this PR as infrastructure too?

Yes, it is intentional:)

**Comment by VladimirSlavik** [comment]
Oh, I meant this... ^ But I might have missed something?

**Pull request merged**
