### PR TITLE
rpmostreepayload: Rework binds to be recursive

### PR DESCRIPTION
**Pull request by cgwalters**
Our hardcoded list of mount points missed critical ones
like `/sys/firmware/efi/efivars`, which broke installation
on EFI.

I started to add that to the list, but then I realized there's a much
simpler solution - make the binds recursive and let `mount` do the
work for us.  This is a bit more risky of a change, but it'll
clearly be more maintainable long term.

Down the line...we may want to simply walk over all the toplevel mount
points in `/mnt/sysimage`, but I doubt anyone is going to add anything
new that's not a subdirectory of `/sys`.

See https://pagure.io/atomic-wg/issue/185

### CODE REVIEW

**Comment by cgwalters** [comment]
`updates.img` for this:

```
curl -L -O 'https://fedorapeople.org/~walters/updates.img{,.asc}'
gpg2 --verify updates.img.asc
```

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by rvykydal** [comment]
Looks good to me.

**Comment by dustymabe** [comment]
can we get this merged? - we'd like to get things fixed so our next two week release of Atomic Host has a fix for this.

**Comment by dustymabe** [comment]
can we get this merged in for f25 as well?

**Pull request merged**
