### PR TITLE
Add a uninstall hook for the renamed anaconda

### PR DESCRIPTION
**Pull request by dashea**

### CODE REVIEW

**Comment by jkonecny12** [comment]
Looks good to me

**Comment by vpodzime** [comment]
Looking at this I feel like autotools must already have a solution for this. Installing a file with a different file name is not an uncommon thing.

**Comment by dashea** [comment]
> Looking at this I feel like autotools must already have a solution for this.

Not really. You can apply a sed expression to every filename at install time, which is broader of a brush than is helpful for this (not renaming pyanaconda/anaconda.py, for example, would probably be tricky), or you can create a copy in the build directory with the new name.

**Comment by dashea** [comment]
Pushed.

**Pull request closed without merging**
