### PR TITLE
Stop kickstart when space check fails (#1320436)

### PR DESCRIPTION
**Pull request by bcl**
Text mode kickstart behavior was inconsistent, it would allow an
installation to continue even though the space check failed. Every other
install method stops, letting the user add more space before continuing.

Resolves: rhbz#1320436

### CODE REVIEW

**Comment by jkonecny12** [comment]
I don't think we want this, or if we really do then we need to have something like this https://github.com/rhinstaller/anaconda/pull/472 .

The space check requires always more space than you really need and for some special use cases it's almost impossible to create even good space check. If you want really small installation you can't do it with this patch any way.
I always thought this KS behavior is on purpose.

**Comment by bcl** [comment]
The problem is that we have inconsistent behavior, only available in a text kickstart. GUI install always stops, as does interactive text installations. We should make things consistent and then reevaluate #472 and the size calculation code.

**Comment by jkonecny12** [comment]
OK but this should be added with the solution to disable space check or similar solution before a release.
I don't want to see f24 or RHEL7 with this patch but without an option to skip the check.

I'm giving you ACK for this one now and I'm waiting for the related later.

**Comment by bcl** [comment]
New patch with another twist on this. In GUI mode if the kickstart didn't include an environment it wasn't running the software check thread so the size estimate could stay at the default of 3000MiB.

I still don't think we need a way to override this. We should depend on what information we have, and with this change I can make small / partitions that will pass the check and later fail during installation, needing a few extra megs.

**Comment by jkonecny12** [comment]
> I still don't think we need a way to override this. We should depend on what information we have, and with this change I can make small / partitions that will pass the check and later fail during installation, needing a few extra megs.

Did you test it on RHEL or Fedora? RHEL is using old space check but the Rawhide and the Fedora 24 using new more strict test.

**Comment by bcl** [comment]
> Did you test it on RHEL or Fedora? RHEL is using old space check but the Rawhide and the Fedora 24 using new more strict test now.

I've been testing on RHEL7.3

**Comment by jkonecny12** [comment]
Yes this happening only on RHEL, but not on Fedora. On Fedora you always need min required space + some percent of space as a bonus. On Fedora you can't create small partition which will fail during installation. You even can't create small partition which will work during installation but it's practically unusable for normal purpose, but it could be useful for abnormal purpose.

Try this test on Fedora and see what is the minimal amount of space needed compared to minimal on RHEL.

Also on RHEL it could be nice to do some test with only ``@core`` or even ``--nocore`` installation.

**Comment by bcl** [comment]
For now how about we limit this change to RHEL7?

**Comment by jkonecny12** [comment]
I'm only thinking if you can create minimal Docker install (``--nocore`` if I'm right) but you have better understanding then me on this so I leave this to you.
In other words it's fine with me.

**Comment by bcl** [comment]
Good idea. GUI works great with small (450M or so) / but TUI isn't updating the estimate.

**Comment by bcl** [comment]
Ok, NOW it works consistently everywhere. I had to add checking software selection in tui kickstart using the execute() method on the software spoke. And further testing revealed a problem with GUI and network up, it tried running checkSoftwareSelection without a baseRepo setup so I added a check for that and re-tested all the variations (enough space, not enough space, nocore+nobase, minimal) for both GUI and TUI kickstarts as well as interactive.

**Comment by jkonecny12** [comment]
Looks good to me again :).

**Comment by bcl** [comment]
Thanks, pushed.

**Pull request closed without merging**
