### PR TITLE
Replace IPy package by ipaddress

### PR DESCRIPTION
**Pull request by jkonecny12**
ipaddress function is from python 3 standard library.
The IPy package requirement from anaconda was removed.

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me too, but the ``check_ip_address`` is a good candidate for unit tests, I think.

**Comment by jkonecny12** [comment]
The test was added. I hope this is enough.

**Comment by vpodzime** [comment]
> The test was added. I hope this is enough.

Absolutely. Thanks!

**Comment by jkonecny12** [comment]
Pushed.
Thank you

**Pull request closed without merging**
