### PR TITLE
webui: tests: temporarilly pin down firefox to unbreak CI

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]

**Comment by KKoukiou** [comment]
This happens only on boot.iso not on live image.

**Comment by martinpitt** [comment]
This also seems to break the f-39 branch, see https://github.com/cockpit-project/bots/pull/5346 . Can this be backported?

**Comment by KKoukiou** [comment]
> This also seems to break the f-39 branch, see [cockpit-project/bots#5346](https://github.com/cockpit-project/bots/pull/5346) . Can this be backported?

f-39 branch should not be tested anymore for anaconda, since we dont ship webui there. WIll send a PR to remove.

**Pull request merged**
