### PR TITLE
webui: minor code cleanups

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by vojtechtrefny — APPROVED** [review]

**Review by VladimirSlavik — APPROVED** [review]
Thanks! Not sure about some of the better names, but you know that better.

**Comment by KKoukiou** [comment]
> Thanks! Not sure about some of the better names, but you know that better.

open for suggestions! Which one you don't like?

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Review by rvykydal — APPROVED** [review]
Looks good to me. Given we already use "Scenario" term it is way more consistent now.

(I wouldn't try to find something better at this point. Now it maybe close to "Method" but in the future we might really get to implementing guided partitioning scenarios? (or how to call it), like "Reuse home", "Install along existing system"...

**Pull request merged**
