### PR TITLE
Update the kickstart data for iSCSI and NVDIMM during the installation

### PR DESCRIPTION
**Pull request by poncovka**
We don't need to update the kickstart data for iSCSI and NVDIMM after
every partitioning. Let's move the code to the update_storage_ksdata
function that we run during the installation.

This code should be eventually moved to the Storage module.

### CODE REVIEW

**Comment by poncovka** [comment]
@rvykydal, could you help me with testing, please?

**Comment by rvykydal** [comment]
Yes I can, I think we just need to test that
- nvdimm device reconfigured in GUI (or selected in GUI if it is already in sector mode - if we want more testing)
- iscsi device attached in GUI
ends up in generated kickstart as nvdimm or iscsi command
I can do the testing for you.

**Comment by poncovka** [comment]
@rvykydal, I have figured out how to test the NVDIMM device (Anaconda had to forget that the device was reconfigured), so I need help only with iSCSI.

**Comment by rvykydal** [comment]
I tested the patch with iscsi target added in GUI and the commands seem to be still generated correctly /root/anaconda-ks.cfg

**Comment by poncovka** [comment]
@rvykydal, thanks!

**Pull request merged**
