### PR TITLE
Clean up ISO option in source selection spoke

### PR DESCRIPTION
**Pull request by OndrejZobal**
Update ISO option in the source selection spoke as suggested by Vendula Poncova here: https://github.com/rhinstaller/anaconda/discussions/4257

obrazek

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Looks good me. Thank you! Btw. does the tooltip work on its own? It would be good to confirm that users can still access a full device description since that label is ellipsized now.

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well. :)

**Comment by OndrejZobal** [comment]
> Looks good me. Thank you! Btw. does the tooltip work on its own? It would be good to confirm that users can still access a full device description since that label is ellipsized now.

@poncovka  Sorry, I have goldfish memory. I updated the pull request with the tooltip code. You might want to review it again. Thanks a lot for catching this.

**Review by poncovka — APPROVED** [review]
Thank you!

**Pull request merged**
