### PR TITLE
Do not display curl 404 errors that can be safely ignored

### PR DESCRIPTION
**Pull request by vojtechtrefny**
Hide curl 404 errors while downloading updates.img/product.img/.treeinfo from repository.

Resolves: rhbz#1182776

### CODE REVIEW

**Comment by vpodzime** [comment]
I think this commit needs a comment in the commit message or in the code that ``info`` is supposed to only print the message with debugging turned on. Otherwise it looks like this commit makes no difference.

Looks good to me other than the minor issue described above.

**Comment by bcl** [comment]
Nice!

I'm pretty sure info always prints the message.

**Comment by vojtechtrefny** [comment]
Actually warn prints the message during "normal" boot and info should print the message only in debug mode (= with rd.debug or rd.info arguments). Or at least I assume this should work this way from the code -- https://git.kernel.org/cgit/boot/dracut/dracut.git/tree/modules.d/99base/dracut-lib.sh -- because in debug mode both info and warn messages are NOT displayed (or added to the log). I need to file a bug against dracut...

**Comment by vojtechtrefny** [comment]
Commit msg updated.

**Comment by vpodzime** [comment]
> Commit msg updated.

Thanks! *"dracuts"* in *"...in debug mode using dracuts 'info'"* should be *"dracut's"*, but other than that this is perfect.

**Comment by vojtechtrefny** [comment]
Fixed locally.

**Comment by vojtechtrefny** [comment]
Pushed

**Pull request closed without merging**
