### PR TITLE
webui: bring storage step wizard body closer to the design suggested by mockups

### PR DESCRIPTION
**Pull request by KKoukiou**
It now will look like this:
Screen Shot 2022-03-22 at 14 26 12

Previously:
Screen Shot 2022-03-22 at 14 27 18

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by KKoukiou** [comment]
Just force pushed because the rpm-build tests where not running.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me as far as I can tell :).

**Pull request merged**
