### PR TITLE
Update requirements for fips - update-crypto-policies script

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: rhbz#1841471

### CODE REVIEW

**Comment by t184256** [comment]
Please specify both crypto-policies and crypto-policies-scripts, I find it more explicit and it depends on both.

**Comment by t8m** [comment]
> Please specify both crypto-policies and crypto-policies-scripts, I find it more explicit and it depends on both.

Except if for any catastrophical reason we are forced to revert the package split anaconda will have to be updated again.

**Comment by t8m** [comment]
So the best is:
Requires: crypto-policies 
Requires: /usr/bin/update-crypto-policies

**Comment by t184256** [comment]
no objections

**Comment by rvykydal** [comment]
> So the best is:
> Requires: crypto-policies
> Requires: /usr/bin/update-crypto-policies

PR updated

**Pull request merged**
