### PR TITLE
bootupd: call bootupctl with --update-firmware

### PR DESCRIPTION
**Pull request by AdamWill**
This is required to write an entry to the EFI boot manager, which we ought to do (anaconda does it when installing the bootloader itself). Without this, boot of the installed system will only work if it's configured to try and boot from the hard disk using the fallback path.

### CODE REVIEW

**Comment by AdamWill** [comment]
I haven't tested this yet, but wanted to file it as a way to flag the issue. It seems like images that use bootupd (Silverblue and IoT) do not boot after install on UEFI in openQA. I believe this is why: they don't actually write an EFI boot manager entry (I modified one openQA test to run `efibootmgr` after install was complete, and it showed no Fedora entry in the list). The system will still sometimes boot okay, but only by relying on boot from the hard disk using the EFI fallback path, which is really meant to be an emergency backstop, and does not work in all cases.

I'm running a test build of a Silverblue image with anaconda patched with this patch ATM, and will try and get openQA to test a UEFI install and boot with it once it's done.

**Comment by AdamWill** [comment]
@pcdubs @travier @jmarrero

**Comment by travier** [comment]
CC @cgwalters

**Review by travier — APPROVED** [review]
This LGTM. We indeed need to do this for Atomic Desktops.

Investigation in https://pagure.io/workstation-ostree-config/pull-request/453#comment-199664

**Comment by cgwalters** [comment]
> but only by relying on boot from the hard disk using the EFI fallback path, which is really meant to be an emergency backstop, and does not work in all cases.

Yeah, though this is how all FCOS (and derivatives) installs work by default; https://github.com/coreos/fedora-coreos-tracker/issues/946 has a lot of related bits.  This also relates to the general idea of having the operating system work like cloud instances, which always start from a disk image.  (This is how booting in AWS/GCP/qemu-with-uefi work etc.)

But yes, it does probably make sense to do this.  That said, we could also use Anaconda's code for this.   If this works it's probably simplest, but the equivalent bootupd logic here is currently way less battle-tested than Anaconda's, to state the obvious.  (We *are* testing it though in at least AWS instances with UEFI)

**Comment by AdamWill** [comment]
Yeah, I think it's an environmental thing; for FCOS it's sensible since the target environment is one where we know fallback path boot works and is commonly relied upon. But this isn't really the case for desktop spins, obviously; they get installed into, er, extremely heterogeneous firmware environments ;) IoT I guess is somewhere in the middle.

Yeah, there's definitely some subtlety to this beyond "does it work". It seems like it [*does* work](https://openqa.stg.fedoraproject.org/tests/3649324#) to fix boot of a clean Silverblue install in openQA, at least. But questions I can think of: what does it call the efibootmgr entry it creates? What does it do if one with the same name already exists? How do attempts to dual boot between an anaconda-bootloader-code install and a bootupd-bootloader-code install work out?

BTW, on the FCOS topic - it looks like the openQA FCOS tests don't run into this because they're all run on BIOS...maybe I should flip them to UEFI...

**Comment by jkonecny12** [comment]
If it is environment dependent than it could be resolved by Anaconda configuration files

**Comment by AdamWill** [comment]
I don't think we really need to *not do* this in some environments (unless Colin disagrees), it shouldn't cause any harm at all in cloud environments. It's just not really *necessary*.

For the `bootloader` kickstart command - I guess you're considering the `--leavebootorder` option, right? That's documented as telling anaconda to *not* do this. So, yes, I suppose we should respect that, I'll see if I can add it.

**Comment by AdamWill** [comment]
I'm not sure you could manage "don't install a bootloader at all" that way, though.

Don't get me wrong - when I say "complete rewrite" I mean "we should probably get rid of like 75% of them and tell people to live with it". :D But as long as they all exist, I guess, we should at least configure the interface; at a minimum we could update the pykickstart docs to flag which options are intentionally not implemented for the bootupd path, and maybe log warnings if they're passed in the kickstart for such an install?

But that seems rather beyond the scope of this PR. Given that we're already not implementing lots of other args, I'm not sure if implementing that arg should block this PR, especially if it needs changes to bootupd first?

**Comment by AdamWill** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=2268505 and proposed as a Beta blocker for the IoT case; it may not really be serious enough to make it a blocker, but I figured we could discuss it at least, and should at least make it an FE for the Atomic Desktops case.

**Comment by jkonecny12** [comment]
Good point. I agree for leaving bootloader kickstart out of this and document that.

**Comment by AdamWill** [comment]
So looking into how bootupd *names* the entry, it seems that it calls its own `find_efi_vendordir()` function and names the entry for whatever that returns. So it is, I think, expecting to find `/boot/efi/EFI/fedora` and name the entry "fedora". But the `find_efi_vendordir()` implementation seems a bit naive - it seems to just take the first directory it finds under the EFI directory (`/boot/efi/EFI`) which isn't called `BOOT`.

This worries me a bit, because on my system, I have:

    [adamw@xps13a bootupd (main)]$ sudo ls /boot/efi/EFI
    BOOT  dell  fedora

Note, "dell". Which alphabetically comes before "fedora". so...er, yeah, that seems like it may cause some issues. It kinda looks like that would break creating the EFI boot manager entry (it doesn't just use the vendor dir it finds as the name of the entry, it also looks in that directory for a shim file for the entry to point to), and installing `grub-static-efi.cfg` in `grubconfigs.rs` `install()`.

anyhow, aside from that, it seems like at least bootupd's *intent* is to call the entry "fedora". Which is not quite the same as "Fedora", which is what anaconda calls the entry when it makes it itself (for Fedora, anyway; it actually uses `get_product_name().split("-")[0]`).

When anaconda is handling the efibootmgr install, it removes existing entries before creating its new one (unless `--leavebootorder` is set). But it only looks for existing entries with the *exact same* label, so it will not remove any 'fedora' entries created by bootupd. Not sure how much of a problem we think that is.

It doesn't look like either bootupd itself or the anaconda bootupd integration code make any attempt to remove existing entries (of either naming style) before creating a new one.

**Comment by jkonecny12** [comment]
That looks like an RFE on bootupd project to me.

**Comment by travier** [comment]
Given all of what you wrote, it feels like we should be using a subset of the logic in Anaconda as this is going to be a lot of changes on the bootupd side otherwise. So we might as well share the "efibootmanager" logic here instead of duplicating it in bootupd and having to test it all again.

**Comment by AdamWill** [comment]
Yeah, so far as efibootmgr invocations go that kinda sounds sensible to me. But then should we try and move that code out somewhere for anaconda and bootupd to share? pyanaconda is probably a pretty heavy dependency for bootupd, no?

**Comment by cgwalters** [comment]
I can't imagine it'd be a problem for the anaconda environment to depend on bootupd?  Or dunno, we could split out a distinct helper binary.  But anyways, this is in some distant future because as you say there's some not-small risk from touching the Anaconda code here I suspect.

**Comment by cgwalters** [comment]
>  So we might as well share the "efibootmgr" logic here instead of duplicating it in bootupd and having to test it all again.

To be clear, the rationale for bootupd having this is around supporting `bootc install` - where a container can act like a self-extracting zip file and support installing itself to a disk (for basic scenarios) without any external infrastructure at all required.  More in https://containers.github.io/bootc/bootc-install.html#using-bootc-install-to-filesystem---replacealongside

(It'd *also* make sense to support running anaconda as a container for these types of flows, installing the target OS container...or I guess via `dnf install anaconda` too.)

What I would like to do is get https://github.com/rhinstaller/anaconda/pull/5285 merged, then we can flesh out using bootc as part of anaconda more, which will help drive some deduplication too hopefully.

**Comment by travier** [comment]
I agree that ideally we would have a shared tool doing that setup for us but in the meantime, in oder to make this ready for F40 (beta ideally), could we re-add some of the logic from Anaconda around EFI boot entry setup (likely things that have been skipped in https://github.com/rhinstaller/anaconda/pull/5342)? @jkonecny12

**Comment by jkonecny12** [comment]
I can't help myself but I have a bad feeling about mixing together Anaconda and bootupd approaches. Anyway, I guess we should at least try.

Are we talking here about F40 or F41 solution?

**Comment by travier** [comment]
Ideally, if we can get something low risk in F40 that would be great, otherwise we'll have to postpone the bootupd inclusion in Fedora Atomic Desktops again to Fedora 41.

**Comment by travier** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2268505#c7

**Comment by jkonecny12** [comment]
Honestly, every bootloader change is high risk for me but mainly because this is not our domain of expertise. Unfortunately, I'm not sure if we have a time to spent on this right now :(

**Comment by travier** [comment]
If we don't get a fix for this in F40, another option to not completely loose bootupd support is to remove it from the ISO so that Anaconda does a normal installation and then add the package to the Atomic desktops after the release to let users update their systems.

**Comment by jkonecny12** [comment]
The second option seems good to me. I don't think we are in position to do such a last minute fixes to the bootloader code on Fedora 40.

**Comment by cgwalters** [comment]
> another option to not completely loose bootupd support is to remove it from the ISO so that Anaconda does a normal installation and then add the package to the Atomic desktops after the release to let users update their systems.

Hmmm...that's going to lead to a state where the bootloader state isn't tracked by bootupd, so it'd need to be an adopt workflow.  And actually more generally, it stops using static grub configs and reverts all the way back to dynamic `grub2-mkconfig` style flows then, right?

Arguably of course we should still support decoupling these things but personally I'd like to go as far as we can towards static configs.

I don't have a sense of how serious this problem is.  Maybe what would be easiest is to add an opt-in knob to do what this PR is doing.

> Note, "dell". Which alphabetically comes before "fedora". so...er, yeah, that seems like it may cause some issues. It kinda looks like that would break creating the EFI boot manager entry (it doesn't just use the vendor dir it finds as the name of the entry, it also looks in that directory for a shim file for the entry to point to), 

Hmm you're right that the bootupd installation logic is not ready to handle this and it definitely should.

**Comment by AdamWill** [comment]
> I don't have a sense of how serious this problem is. Maybe what would be easiest is to add an opt-in knob to do what this PR is doing.

I mean, to me it is clearly the case that when doing a permanent OS installation to an end-user system - as is the case for things like the Atomic desktops - the OS should write an EFI boot manager entry and make it the new default. That's the expected behaviour. It does not seem right to me that we should expect to be able to rely on the fallback path to boot the installed system. We could ask folks like pjones and mjg59 for more opinions, I guess.

I totally agree that it would be best to support kickstart options that are intended to modify this behaviour where they exist, but that does seem like the most appropriate 'default path' behaviour to me. It's what we have done for years on the existing codepaths.

**Comment by jkonecny12** [comment]
I'm closing this PR as it has unfortunate side-effects. The solution is currently tracked: https://github.com/coreos/bootupd/issues/658

**Comment by cgwalters** [comment]
> I'm closing this PR as it has unfortunate side-effects.

What are those?

**Comment by cgwalters** [comment]
Note that https://github.com/coreos/bootupd/pull/650 landed which should greatly improve the semantics for dealing with existing files in the ESP.

**Comment by travier** [comment]
Next step is https://github.com/coreos/bootupd/issues/658 and then we should re-open this one.

**Comment by cgwalters** [comment]
@jkonecny12 See https://github.com/coreos/bootupd/pull/665#issuecomment-2155353631 - yes ?

**Comment by jkonecny12** [comment]
If you see this as the best option I don't see a reason to block it.

We can merge this on Monday and have release on Tuesday if you want. Is that fine @cgwalters ?

**Comment by cgwalters** [comment]
> We can merge this on Monday and have release on Tuesday if you want. Is that fine @cgwalters ?

In rawhide, yes?  Seems fine to me, the blast radius is quite low.  And having pre-generated ISOs to use with remote payloads would be helpful.

Can you speak a little bit to the overall question of how to make this stuff a bit more configurable at a low level?  I'm sure this has come up before in the context of Anaconda.  Making things configurable via kickstart works...and in this case, `bootloader --no-firmware` could even make sense.

But that's a high level interface; it'd be nice to have "low level debugging/escape hatch" tools via say environment variables - if we could do things that way.  A different thought I had is that we could try to structure some of the things Anaconda does as systemd units.  For example, one could imagine doing `systemctl mask anaconda-bootloader.service`...
Any other ideas around making it easy for people to tweak what is currently this hardcoded argument/phase on or off?

**Comment by AdamWill** [comment]
I'd say the most 'normal' way to do that with anaconda is kernel args. We have a ton of them. https://anaconda-installer.readthedocs.io/en/latest/boot-options.html

**Comment by jkonecny12** [comment]
Yes, basically Anaconda is using three ways to configure this:
* kernel boot options - I agree with @AdamWill that this seems to be the best shot
* kickstart file - probably not something I would like to introduce until someone request it, also not best for debugging
* Anaconda configuration files - that is mostly focused on differences between the images (Fedora Workstation, Fedora IoT, RHEL...)

From these options I would prefer kernel boot options. We can introduce one which is then passed to the tooling. Ideally if you give us suggestion of what exactly you want us to do. We now have [inst.sdboot](https://docs.google.com/document/d/1kOHlz_1ANA7BYlcgyxHwS6Vb7KlQA2c445CbKUngCmo/edit), so maybe something similar to bootupd/bootc. Maybe something like `inst.booupd.no-firmware`?

Please give us a list of what you would like to achieve with this.

**Comment by jkonecny12** [comment]
**Updated:**
- I renamed this PR (removed the DO NOT MERGE part)
- Rebased

**Comment by travier** [comment]
I think that ideally we would have Anaconda support the following for the bootupd case:

- `bootloader --leavebootorder`: Calls to bootupd without the `--update-firmware` option from this PR.

**Comment by travier** [comment]
The main issue that we have right now is that as soon as we add bootupd to the images, this enables the bootupd code path in Anaconda and there is no way to use the other path.

If we could have a variable that force one or the other that would be helpful as well.

**Comment by cgwalters** [comment]
> bootloader --leavebootorder: Calls to bootupd without the --update-firmware option from this PR.

Agreed!

**Comment by jkonecny12** [comment]
I've added the requested code. It needs to be tested though.

**Review by cgwalters — APPROVED** [review]
Looks sane to me!

**Review by KKoukiou — APPROVED** [review]

**Comment by jkonecny12** [comment]
@jikortus @cgwalters  do we want to backport this to RHEL branches too?

**Comment by cgwalters** [comment]
> Are you fine to wait for next build Tuesday or do you want me to do extra build for this change during the week?

If there was anything that couldn't wait a week we'd be sure to flag that I think.

> @jikortus @cgwalters do we want to backport this to RHEL branches too?

Should definitely go into c10s relatively quickly, and let's do verification of things there, then target c9s probably too.

**Comment by jikortus** [comment]
@jkonecny12 ACK for backporting this feature RHEL-10, it looks useful for non-cloud use-cases. Just note that, to my best knowledge, we'll be only able to test the installation with a CS10 bootc image at this point.

**Comment by jkonecny12** [comment]
For testing upstream I used fedora:eln container which we are using in KS tests.

**Comment by travier** [comment]
Thanks for the code @jkonecny12 ! Could we get this in Rawhide? I'll push an updated bootupd & re-enable it for the Atomic Desktops in Rawhide as well.

**Comment by jkonecny12** [comment]
Yes, sorry we missed yesterday release because there is a fix we would like to get out. We will try to get this out today.

**Pull request merged**
