### PR TITLE
Replace the deprecated syspurpose CLI tool with SetSysrpose DBus call

### PR DESCRIPTION
**Pull request by M4rtinK**
Use the SetSysrpose() RHSM DBus API method instead of the deprecated
syspurpose CLI tool.

Resolves: rhbz#1939708

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]
Looks good to me.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me!

**Comment by M4rtinK** [comment]
Port to Fedora: #3690

**Pull request merged**
