### PR TITLE
Remove threading compatibility layer

### PR DESCRIPTION
**Pull request by KKoukiou**
We cannot have a module called 'threading', otherwise the build will fail with
the traceback below. Remove this file as it was anyhow meant to be an
intermediate compatibility solution.

The traceback from the build:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib64/python3.12/py_compile.py", line 9, in <module>
    import importlib.util
  File "<frozen importlib.util>", line 16, in <module>
  File "/builddir/build/BUILD/anaconda-41.10/pyanaconda/threading.py", line 21, in <module>
    from pyanaconda.core.threads import thread_manager as threadMgr
ModuleNotFoundError: No module named 'pyanaconda'

Resolves: rhbz#2275279

Blocked by:
- [x] :  https://github.com/rhinstaller/initial-setup/pull/152
- [x] : release initial setup

### CODE REVIEW

**Comment by jkonecny12** [comment]
`custom_threads` is not a good name. First, it doesn't mean anything. Second, it's too generic that I wouldn't be surprised by another collision in the future.

If we want to do this, I would rather like to see something like `anaconda_threads`. However, I'm not sure about this solution in overall. Python is namespaced already by `pyanaconda` package. Issues we see is a tooling issue not language one.

**Comment by jkonecny12** [comment]
Also I see only removal of file in this PR, isn't there something missed here?

**Comment by M4rtinK** [comment]
> If we want to do this, I would rather like to see something like `anaconda_threads`. However, I'm not sure about this solution in overall. Python is namespaced already by `pyanaconda` package. Issues we see is a tooling issue not language one.

Agreed that if this is about a naming collision, a replacement should have "anaconda" in its name to fix it for good. Provided we really need it.

The suggestion from Miro on the bug to stop using this weird pycompile script also sounds interesting: https://bugzilla.redhat.com/show_bug.cgi?id=2275279#c15

But indeed, hard to tell how hard it it is to change it now & what other unexpected side effects it might have (maybe something depends on the pyc files in a weird way in our CI & might break if they are not there (in built but unpackaged code) ?).

**Comment by jkonecny12** [comment]
More prefered solution to this issue: https://github.com/rhinstaller/anaconda/pull/5574

Thanks a lot @KKoukiou for such a quick reaction ;)

**Comment by KKoukiou** [comment]
@jkonecny12 I think we can merge this now that inital setup released. Checked kdump for possible breackable - seemed not affected. If some other plugin will be affected, it's fine - we will fix it.

**Comment by jkonecny12** [comment]
I think we should also propose fix for oscap addon before doing this:
https://github.com/search?q=repo%3AOpenSCAP%2Foscap-anaconda-addon%20threading&type=code

**Comment by M4rtinK** [comment]
> I think we should also propose fix for oscap addon before doing this:
> https://github.com/search?q=repo%3AOpenSCAP%2Foscap-anaconda-addon%20threading&type=code

Did we check the Anaconda kdump addon is compatible with the new thing ?
https://github.com/rhinstaller/kdump-anaconda-addon

**Comment by VladimirSlavik** [comment]
Thanks for pushing forward with this! It's one of those eternal todos...

**Pull request merged**
