### PR TITLE
Handle subprocess disallowing preexec during shutdown

### PR DESCRIPTION
**Pull request by AdamWill**
In Python 3.12, you cannot pass a preexec_fn to subprocess.Popen during interpreter shutdown:

https://github.com/python/cpython/pull/104826

This avoids the problem by giving startProgram an arg to not use a preexec_fn, and passing that all the way from anaconda's exitHandler through execWithRedirect and _run_program.

### CODE REVIEW

**Comment by AdamWill** [comment]
This works OK in openQA testing.

A possible alternative is just to have the exit handler call subprocess directly; I don't think all these wrappers around it are *doing* much of any use on this path. But that seemed a slightly bigger change than this, so I went with this to start with.

**Comment by AdamWill** [comment]
This (or a different fix) must be merged before the next release, because Python 3.12 has been merged into Rawhide. If a new release is made without this bug fixed, it'll be built in Rawhide by packit, and that build will be broken. (Fortunately, now gating is enabled, it should be blocked by gating rather than getting in and breaking the compose).

Also, today's compose testing indicates this needs extending to the VNC shutdown code:

https://openqa.fedoraproject.org/tests/2005161#step/_boot_to_anaconda/5

I'm on vacation without a laptop, so if someone else can do that, it'd be great.

**Comment by VladimirSlavik** [comment]
Just a note, I thought of the following alternatives constrained to changes only in `startProgram`:
- Check dynamically if preexec should happen based on `sys.is_finalizing()` . This appears as a silent side effect, so not really desirable.
- Check if preexec is really needed - the function body is all conditionals - by testing all the clauses. Unfortunately this does not solve the problem, because `reset_handlers` is always `True` in the call path from `execWithRedirect`.
- Propagate the `reset_handlers` flag instead of `do_preexec` - mostly the same problem as above, does not really explain that it's preexec that should not happen.

So I think this is the only way.

**Review by VladimirSlavik — APPROVED** [review]

**Comment by VladimirSlavik** [comment]
Needs:
- fix the VNC code path above too
- tests

Working on that.

**Comment by AdamWill** [comment]
Thanks! What did you think of the 'just have the exit handlers call subprocess directly' idea?

**Comment by VladimirSlavik** [comment]
Ah, I missed that one. I think this way is better - we have all the logging and such in place for these calls, and will likely expect the logs to look the same for this.

I also feel that worrying too much about this might be premature optimization. The exit-ing code paths need modularization, soonish, and the exec* family of functions is also one of the areas that are known to need rewriting for contemporary Python. So this might not live too long anyway...

**Pull request merged**
