### PR TITLE
Redirect everything that was spamming TTY1 to Journal

### PR DESCRIPTION
**Pull request by M4rtinK**
~So far unsuccessfully. :P~

Works now. :)

### CODE REVIEW

**Comment by M4rtinK** [comment]
redirect_mk1
redrect_mk1_tty1

**Comment by M4rtinK** [comment]
Should be working now:
solved_tui
This is how RDP client connecting and disconnecting looks like in Journal:
solved

**Comment by M4rtinK** [comment]
Thanks a lot to @halfline & @jstodola for helping to track down the root cause of this! :)

**Comment by M4rtinK** [comment]
Turns out the accelerators fix was hitting an issue with some dodgy GTK API (`Gtk.AccelGroup.query()` - have not been able to find authoritative docs for Python & GTK for this), so I've dropped that commit for now. Given all the redirections to Journal, this commit is not totally necessary to keep TTY1 clean. :)

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. However, it's problematic that we don't have test coverage for anything here.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by M4rtinK** [comment]
> Looks good to me. However, it's problematic that we don't have test coverage for anything here.

Yeah - not sure about the `run-in-new-session` script itself for example, given the amount of black magic involved - hopefully we can make the installation environment more sane over time & make it unnecessary. :)

But for display.py or gnome_remote_desktop.py - that definitely could and should be covered by unit tests. Definitely something to keep in mind going forward. :)

**Comment by jkonecny12** [comment]
It's now forwardported to Fedora in https://github.com/rhinstaller/anaconda/pull/5829

**Pull request merged**
