### PR TITLE
Add noautodefault boot option

### PR DESCRIPTION
**Pull request by rvykydal**
Kickstart test: https://github.com/rhinstaller/kickstart-tests/pull/693

### CODE REVIEW

**Review by poncovka — APPROVED** [review]
Looks good to me. I guess the option should be documented and maybe it is also a good candidate for [release notes](https://github.com/rhinstaller/anaconda/blob/master/CONTRIBUTING.rst#release-notes) .

**Review by VladimirSlavik — COMMENTED** [review]
This should:
- be added to `docs/boot-options.rst`
- have a release note in `docs/release-notes`
- have the notable change label on PR, probably

Unless this is meant to be an internal implementation detail?

**Review by poncovka — APPROVED** [review]

**Pull request merged**
