### PR TITLE
webui: start using useReducer for managing complicated state objects centrally

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Thank you. I think it is definitely useful to have such managed central state. We may need to be careful about what should go to the state, to what level and scope it could reflect/cache the state of the backend and when/if it is better to communicate directly with the backend on lower level? (especially storage may be tricky if we have more features, screens, etc?). But these are rather vague concerns that may arise from me not grasping the concept of the reducer with thunk fully yet.

**Comment by KKoukiou** [comment]
> Thank you. I think it is definitely useful to have such managed central state. We may need to be careful about what should go to the state, to what level and scope it could reflect/cache the state of the backend and when/if it is better to communicate directly with the backend on lower level? (especially storage may be tricky if we have more features, screens, etc?). But these are rather vague concerns that may arise from me not grasping the concept of the reducer with thunk fully yet.


So the idea if that you can trigger actions to update the store (global state) from anywhere in the project. And then every component has access to the same store. That solved the problem that different pages might use different version of the backend data.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by KKoukiou** [comment]
Still dnf5 breakage on testing farm.

**Pull request merged**
