### PR TITLE
Make RHEL the default (fallback) product

### PR DESCRIPTION
**Pull request by VladimirSlavik**

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
I see [this](https://github.com/rhinstaller/anaconda/blob/master/tests/nosetests/pyanaconda_tests/product_test.py#L84) which seems related, but has an identical RHEL thing below, so not really sure.

The tests are dominated by RHEL8 btrfs import failure, maybe that masks the intended test failure.

**Comment by poncovka** [comment]
Hmm, it looks like we don't have tests for `set_from_product`, so don't worry about it.

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by VladimirSlavik** [comment]
Jenkins, test this please.

**Comment by rvykydal** [comment]
jenkins, test this please

**Pull request merged**
