### PR TITLE
webui: group devices in mount point assigment device selector

### PR DESCRIPTION
**Pull request by KKoukiou**
Screen Shot 2023-09-14 at 11 04 36

Screen Shot 2023-09-14 at 12 31 24

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
How do we want want to show devices that are allocated on two (or more) disks? I tried with a VG spanning two drives (`vda` and `vdb`) and the logical volumes (`fedora-root` and `fedora-home`) are shown below `vdb` only:

image

**Comment by KKoukiou** [comment]
@vojtechtrefny that's a very good scenario. Also for raid the same. Blocking this change for discussion.

**Comment by garrett** [comment]
At this level, in this UI: I'd say, don't tie it to the disk itself in grouping, but say it comes from a "volume group".

**Comment by KKoukiou** [comment]
> At this level, in this UI: I'd say, don't tie it to the disk itself in grouping, but say it comes from a "volume group".

Alternatively can we consider something like this? https://www.patternfly.org/components/menus/menu#with-drilldown-breadcrumbs

**Comment by rvykydal** [comment]
Maybe we could just present all ancestors / group by all ancestors? Like:
vda
vda1
-----------
vda, vdb
fedora-root
fedora-home

**Pull request closed without merging**
