### PR TITLE
RHEL-9: Update workflows from master

### PR DESCRIPTION
**Pull request by adamkankovsky**
backported: https://github.com/rhinstaller/anaconda/pull/5618

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
I think the change is correct as we talked over in the chat, however, this needs commit description change :)

**Review by KKoukiou — COMMENTED** [review]
This looks good - but please change the PR name, commit message and description to specify the backport PR

**Review by jkonecny12 — APPROVED** [review]
I like this. I think it should work in theory.

Also a note that commit name has a soft limit which is used by Git UI tools.

**Review by jkonecny12 — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Pull request merged**
