### PR TITLE
Provides compatibility with DNF-2.0

### PR DESCRIPTION
**Pull request by j-mracek**
We try to help dnf api users to make kompatible theirs product with upcoming dnf-2.0. With this major release there are some api changes in dnf.

It would be also nice to mark anaconda without the patch as dnf-2.0.0 incompatible.

### CODE REVIEW

**Comment by j-mracek** [comment]
Anaconda can be tested with last upstream version of DNF using copr repo: https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf-nightly/

**Comment by jkonecny12** [comment]
jenkins, ok to test

**Comment by jkonecny12** [comment]
jenkins, ok to test

**Comment by jkonecny12** [comment]
Sorry for spamming. The PR looks good to me and I wanted to check the tests before I'll build images and do a deeply testing. However the Jenkins is doing what he wants, it's like a cat :D .

**Comment by j-mracek** [comment]
Request: Please we have a bug report related to dnf/anaconda group mark as installed (https://bugzilla.redhat.com/show_bug.cgi?id=1313240). Because marking of group was refactored in DNF-2.0 I believe that the problem was solve. But it is out of my reach to test it. Please can you be so kind and investigate the problem with this PR and upstream dnf version? Thanks a lot

**Comment by jkonecny12** [comment]
@j-mracek I'll test it, it should not be so much of a problem. However it would be nice if you can look on https://github.com/rhinstaller/anaconda/pull/755 and tell me if everything looks good from DNF point of view. It's mainly because the test will be placed on that PR and without it I can't even test it.

**Comment by jkonecny12** [comment]
PR https://github.com/rhinstaller/anaconda/pull/759 marks actual Anaconda as DNF-2.0 incompatible.

**Comment by jkonecny12** [comment]
I did the testing and wrote comment on bugzilla. I also did small fix to this and created the new PR with this commit and my fix on top of that.

I'm closing this PR now because content here is in PR https://github.com/rhinstaller/anaconda/issues/763.

**Pull request closed without merging**
