### PR TITLE
Add better explanation what the `make admin user` means (#1803251)

### PR DESCRIPTION
**Pull request by jkonecny12**
It could be hard to understand concept of the admin user (wheel group) for a
user new to the Linux. Let's try to make this clear by a tooltip explanation.

anaconda-tooltip

*Resolves: rhbz#1803251*
*Suggested-by: jjasghar@gmail.com*

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
I didn't think about it too much, but maybe it should mention some more details - what can the user do, how, what is the mechanism... eg.:  ```Allow this user to perform administration tasks with the 'sudo' command by adding the user to the 'wheel' group.```

**Comment by jkonecny12** [comment]
Thanks for great suggestion @VladimirSlavik . Implemented!

anaconda-tooltip

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
