### PR TITLE
Rhel 9 port Xorg start fix

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Port of #3304 to RHEL 9. Resolves [rhbz#1955306](https://bugzilla.redhat.com/show_bug.cgi?id=1955306).

Do I need to adjust commit messages for the RHEL bz number?

### CODE REVIEW

**Comment by jkonecny12** [comment]
> Do I need to adjust commit messages for the RHEL bz number?

Yes please.

**Review by jkonecny12 — APPROVED** [review]
Great work! Pretty complicated what is happening and thanks to you now well documented in commit messages and code.

**Comment by VladimirSlavik** [comment]
Thank you, commit messages changed.

**Review by poncovka — APPROVED** [review]
Looks good to me.

**Pull request merged**
