### PR TITLE
Rhel9 covscan fixes (2)

### PR DESCRIPTION
**Pull request by VladimirSlavik**
WIP with less critical changes in python code.

Related to #3277, fixes some of [rhbz#1938677](https://bugzilla.redhat.com/show_bug.cgi?id=1938677).

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
I approved the first two commits in https://github.com/rhinstaller/anaconda/pull/3436
The other two look good to me as well.

**Review by M4rtinK — APPROVED** [review]
Looks good to me as well, thanks! :)

**Review by poncovka — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by VladimirSlavik** [comment]
I have checked all [currently known] covscan warnings related to python code and declare this PR to be complete [for current code].

* The two commits here were the only two detections that were actionable.
* There is one more with a redundant check for `Null`, but I think we can survive this.
* There is another "important" find, but it's a false positive; not sure how to waive that one.
```
Error: COPY_PASTE_ERROR (CWE-398):
anaconda-34.24.3/pyanaconda/ui/tui/spokes/storage.py:445: original: "self._init_mode" looks like the original copy.
anaconda-34.24.3/pyanaconda/ui/tui/spokes/storage.py:454: copy_paste_error: "_init_mode" in "self._init_mode" looks like a copy-paste error.
anaconda-34.24.3/pyanaconda/ui/tui/spokes/storage.py:454: remediation: Should it say "_part_method" instead?
#  452|   
#  453|           if self._part_method == PARTITIONING_METHOD_MANUAL:
#  454|->             self._init_mode = CLEAR_PARTITIONS_NONE
#  455|   
#  456|       @property
```

**Comment by jkonecny12** [comment]
Are you sure that your first commit message has a correct name?

**Comment by poncovka** [comment]
@VladimirSlavik, could you try something like this? Btw. it is not tested.

```

        # Choose the partitioning method.
        self._storage_module = storage_module
        self._partitioning = partitioning
        self._orig_part_method = self._partitioning.PartitioningMethod
        self._part_method = self._orig_part_method

        # Choose the initialization mode.
        self._disk_init_proxy = STORAGE.get_proxy(DISK_INITIALIZATION)
        self._orig_init_mode = self._disk_init_proxy.InitializationMode
        self._init_mode_list = sorted(INIT_MODES.keys())
        self._init_mode = self._get_init_mode()

    def _get_init_mode(self):
        """Return the initial value of the initialization mode."""

        if self._orig_part_method == PARTITIONING_METHOD_MANUAL:
            return CLEAR_PARTITIONS_NONE

        if self._orig_init_mode == CLEAR_PARTITIONS_DEFAULT:
            return CLEAR_PARTITIONS_ALL

        return self._orig_init_mode

```

**Comment by VladimirSlavik** [comment]
I could, but I don't want to. Rewrite two lines of code into additional function just because someone else's tool guessed wrong? Let's add a disable for the warning instead.

**Comment by poncovka** [comment]
> I could, but I don't want to. Rewrite two lines of code into additional function just because someone else's tool guessed wrong? Let's add a disable for the warning instead.

Well, the new code is more readable.

**Comment by poncovka** [comment]
@VladimirSlavik, I have opened a pull request for upstream: https://github.com/rhinstaller/anaconda/pull/3454

**Comment by VladimirSlavik** [comment]
Thank you!

**Pull request merged**
