### PR TITLE
Remove container refresh workaround for ELN

### PR DESCRIPTION
**Pull request by jkonecny12**
They updated runners day before I merged this PR. So let's remove this, sight :(.

Unfortunately, not all runners have the new version but I don't think we want to solve that on our side. Just wait until they will update everything.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Thank you anyway :)

**Comment by jkonecny12** [comment]
Seems that GitHub runners update is a slow process. Right now, it's luck if we get new or old one. Let's leave this workaround a while and merge this later.

**Comment by jkonecny12** [comment]
Last four days went with only the newer VMs. Let's merge this to remove our workaround and speed up the execution.

**Comment by jkonecny12** [comment]
Rebased.

**Pull request merged**
