### PR TITLE
Prefer GPT instead of legacy MBR

### PR DESCRIPTION
**Pull request by poncovka**
Use the `inst.disklabel` boot option to specify a preferred disk label type. Specify
`gpt` to prefer creation of GPT disk labels. Specify `mbr` to prefer creation of MBR
disk labels if supported. The `inst.gpt` boot option is deprecated and will be removed
in future releases.

The default value of the preferred disk label type is specified by the `disk_label_type`
option in the Anaconda configuration files. The `gpt` configuration option is no longer
supported.

Fedora Linux systems installed on legacy x86 BIOS systems should get GPT partitioning by
default instead of legacy MBR partitioning. This should be a new default for all products.

See: https://fedoraproject.org/wiki/Changes/GPTforBIOSbyDefault

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
This looks good, but is there a reason we want Anaconda's core default to remain MBR?

**Review by M4rtinK — APPROVED** [review]
Looks good to me code-wise, thanks! :)

**Review by Conan-Kudo — APPROVED** [review]
Oh, I see. We now use Blivet's setting by default.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Comment by poncovka** [comment]
> This looks good, but is there a reason we want Anaconda's core default to remain MBR?

No idea. @jkonecny12? @jstodola?

**Comment by jstodola** [comment]
I'm not aware of any reason why MBR should remain the default. IMO, it makes sense to make GPT the default for all future products, not just Fedora. The disk label would be unified across all systems with all disk sizes.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me and I'm approving this. Thanks!

**Comment by poncovka** [comment]
Updated and tested.

**Comment by AdamWill** [comment]
This PR arguably does rather a lot more than was actually requested, and broke at least one thing. See https://bugzilla.redhat.com/show_bug.cgi?id=2092091#c6 and https://bugzilla.redhat.com/show_bug.cgi?id=2209760 . Why was this implemented this way, instead of by just tweaking the existing logic in blivet?

**Comment by poncovka** [comment]
> This PR arguably does rather a lot more than was actually requested, and broke at least one thing. See https://bugzilla.redhat.com/show_bug.cgi?id=2092091#c6 and https://bugzilla.redhat.com/show_bug.cgi?id=2209760 . Why was this implemented this way, instead of by just tweaking the existing logic in blivet?

@AdamWill I don't remember all details, but this was the original proposal https://github.com/rhinstaller/anaconda/pull/4104, so we just went from there. It looks like @vojtechtrefny actually suggested to change the order of disk labels in Blivet at https://github.com/rhinstaller/anaconda/pull/4104#issuecomment-1127254303, but we never followed up on that. I don't know why.

Anyway, it should be pretty straightforward to fix this. If Blivet changes the order of disk labels, Anaconda can re-enable Blivet's defaults in the Anaconda configuration file via the `disk_label_type` option. @AdamWill @vojtechtrefny Would it make sense now?

**Pull request merged**
